### ISSUE TITLE
Mixtral training is not correctly implemented in the Transformers version specified

### ISSUE THREAD

**Issue by kalomaze** [axolotl-ai-cloud/axolotl#1024]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/OpenAccess-AI-Collective/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

Mixtral is supposed to be trained in a way that penalizes the loss if the use of experts isn't even.\
This was fixed in the Transformers library in this pull request:
https://github.com/huggingface/transformers/pull/28115

I am having to manually swap in the latest commits for the Mixtral folder of that repository into my RunPod instance to get the expected behavior.

More information here:
https://www.reddit.com/r/LocalLLaMA/comments/18u0ax5/axolotls_mixtral_finetuning_is_currently_broken/

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by RicardoDominguez** [comment]
@winglian is the current Mixtral implementation up to date? There was a [quite recent fix](https://github.com/huggingface/transformers/pull/28256) to the transformers implementation.

**Comment by winglian** [comment]
> @winglian is the current Mixtral implementation up to date? There was a quite recent fix to the transformers implementation.

You can test it by simply updating your transformers install to latest main. The comments in that PR indicted they were planning on cutting a new release last week, so I was holding off updating our requirements to wait on that. In retrospect we should probably pin transformers in our requirements for now to the latest main.

**Comment by winglian** [comment]
the referenced PR upstream has been merged back on Jan 11
