### ISSUE TITLE
GPTQ vs QLoRA

### ISSUE THREAD

**Issue by winglian** [axolotl-ai-cloud/axolotl#103]
GPTQ and QLoRA are mutually exclusive when it comes to the PEFT dependency. see https://github.com/winglian/alpaca_lora_4bit/blob/main/requirements.txt#L9 vs QLoRA basically needing `main`. It's probably worth removing the `[int4]` part of the install from the docker container, and simply doing a basic install. We'll also need to update the docs for those people who want to use GPTQ that they will need to `pip uninstall peft` and `pip install .[int4]`. Also, the caveat for them is they need to uninstall peft again if they want to switch back to qlora.

**Comment by winglian** [comment]
code change and basic documentation added with https://github.com/OpenAccess-AI-Collective/axolotl/pull/108, but we should still flesh out the rest of the docs about re-installing peft

**Comment by NanoCode012** [comment]
Should be somewhat closed by https://github.com/OpenAccess-AI-Collective/axolotl/pull/161 .

This PR tells user to install peft separately in Readme for normal installation. In int4, it will just install the pinned version.
