### ISSUE TITLE
Full-fine-tuning is shutdown due to  torch multiprocessing

### ISSUE THREAD

**Issue by hahmad2008** [axolotl-ai-cloud/axolotl#1041]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/OpenAccess-AI-Collective/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

I am doing full fine-tuning using deepspeed. However the process is shut down before even start training! 

### Current behaviour

I have 3 machines each one with two GPUs. here are the configurations i used:

fine-tunning-config.yaml:
```


deepspeed: deepspeed/zero2.json

```

Command:
`accelerate launch  axolotl/scripts/finetune.py fine-tunning-config.yaml --deepspeed deepspeed/zero2.json`

Error:

```
Completed store-based barrier for key:store_based_barrier_key:2 with 6 nodes.
host:729:768 [0] NCCL INFO Using network Socket
host:730:767 [1] NCCL INFO Trees [0] 2/-1/-1->5->4 [1] -1/-1/-1->5->4
host:729:768 [0] NCCL INFO Trees [0] 5/-1/-1->4->0 [1] 5/-1/-1->4->1
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 729 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Unable to shutdown process 729 via 15, forcefully exiting via 9
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -7) local_rank: 1 (pid: 730) of binary: /opt/conda/bin/python3
Traceback (most recent call last):
  File "/opt/conda/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/opt/conda/lib/python3.10/site-packages/accelerate/commands/launch.py", line 977, in launch_command
    multi_gpu_launcher(args)
  File "/opt/conda/lib/python3.10/site-packages/accelerate/commands/launch.py", line 646, in multi_gpu_launcher
    distrib_run.run(args)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
axolotl/scripts/finetune.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-01-04_19:53:55
  host      : host
  rank      : 5 (local_rank: 1)
  exitcode  : -7 (pid: 730)
  error_file: <N/A>
  traceback : Signal 7 (SIGBUS) received by PID 730
============================================================
```

### Steps to reproduce

I have 3 machines each one with two GPUs. here are the configurations i used:

fine-tunning-config.yaml:
```


deepspeed: deepspeed/zero2.json

```

Command:
`accelerate launch  axolotl/scripts/finetune.py fine-tunning-config.yaml --deepspeed deepspeed/zero2.json`

### Which Operating Systems are you using?

- [X] Linux
- [ ] macOS
- [ ] Windows

### Python Version

Python 3.10.13

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by winglian** [comment]
Is this for multi-node training? or single node w multi-gpu?

**Comment by hahmad2008** [comment]
@winglian multi-node training and each node with 2 GPUs.
I tried the qlora fine-tuning on the same node and it worked.

**Comment by winglian** [comment]
> I tried the qlora fine-tuning on the same node and it worked.

you mean using the artidoro/qlora repo? just trying to understand the success and failure scenarios. thanks!

**Comment by hahmad2008** [comment]
@winglian I used the same configuration to finetune qlora and without deepspeed that succeeded however when I used deepspeed with full training (adapter is empty) that failed and cause the error I posted in this issue.

**Comment by winglian** [comment]
Are you running these in docker containers on each node? bare metal? Unfortunately I don't have access to multi-node multi-gpu systems, so I can't really do any troubleshooting to replicate the issue.

**Comment by hahmad2008** [comment]
@winglian yes I am running it using docker containers on multi-node multi-gpu systems.

**Comment by hahmad2008** [comment]
@winglian could you please provide any resources to start using FSDP and deepspeed with axolotl?

**Comment by hahmad2008** [comment]
@winglian  I full-finetune using deepspeed with zero2 config, I observe that the generated model is 2G however the model on the hugging face is 4G!! why this difference?

**Comment by winglian** [comment]
> @winglian  I full-finetune using deepspeed with zero2 config, I observe that the generated model is 2G however the model on the hugging face is 4G!! why this difference? 

What base model?

**Comment by hahmad2008** [comment]
@winglian  
base model is `TinyLlama`
generated model from full-finetunining:

**Comment by winglian** [comment]
the tiny llama base model is in float32, so they take 32 bits -> 4 bytes per parameter. 1.1B parameters X 4 bytes -> 4.4GB
whereas the fine-tuned model outputs are float16 or bfloat16 which are 2 bytes per parameter.

**Comment by hahmad2008** [comment]
@winglian could you please help me in the following issue:

For full-finetuned the TinyLlama model (4.4G), The size of the model generated using deepspeed with zeros2 (**2.1G**) and zero3 (**760K**) are different.

### Zero2
- ` accelerate launch  axolotl/scripts/finetune.py fine-tunning-config.yaml --deepspeed deepspeed/zero2.json`
- size of the model with zero2 (**2.1G**):

```
ls -lh full-finetune-zero2/
total 2.1G
-rw-r--r-- 1 root root 1.9K Jan  9 17:58 README.md
-rw-r--r-- 1 root root   42 Jan  9 14:49 added_tokens.json
drwxr-xr-x 3 root root 4.0K Jan  9 16:17 checkpoint-1032
drwxr-xr-x 3 root root 4.0K Jan  9 17:44 checkpoint-2064
-rw-r--r-- 1 root root  674 Jan  9 17:57 config.json
-rw-r--r-- 1 root root  129 Jan  9 17:57 generation_config.json
-rw-r--r-- 1 root root 2.1G Jan  9 17:58 pytorch_model.bin
-rw-r--r-- 1 root root   95 Jan  9 14:49 special_tokens_map.json
-rw-r--r-- 1 root root 489K Jan  9 14:49 tokenizer.model
-rw-r--r-- 1 root root 1.2K Jan  9 14:49 tokenizer_config.json
```

### Zero3
- ` accelerate launch  axolotl/scripts/finetune.py fine-tunning-config.yaml --deepspeed deepspeed/zero3.json`
- size of the model with zero3 (**760K**):


```
ls -lh full-finetune-zero3/
total 760K
-rw-r--r-- 1 root root 1.9K Jan 11 16:14 README.md
-rw-r--r-- 1 root root   42 Jan 11 13:17 added_tokens.json
drwxr-xr-x 3 root root 4.0K Jan 11 10:51 checkpoint-1032
drwxr-xr-x 3 root root 4.0K Jan 11 12:14 checkpoint-2064
-rw-r--r-- 1 root root  674 Jan 11 16:14 config.json
-rw-r--r-- 1 root root  129 Jan 11 16:14 generation_config.json
-rw-r--r-- 1 root root 235K Jan 11 16:14 pytorch_model.bin
-rw-r--r-- 1 root root   95 Jan 11 13:17 special_tokens_map.json
-rw-r--r-- 1 root root 489K Jan 11 13:17 tokenizer.model
-rw-r--r-- 1 root root 1.2K Jan 11 13:17 tokenizer_config.json
```

### Load the model
- Try to load the model using: `model = AutoModelForCausalLM.from_pretrained`
-  1- Load the generated model successfully (zero2)
-  2- Can't load generated model (zero3), error:
```
File "/usr/local/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 563, in from_pretrained
    return model_class.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/transformers/modeling_utils.py", line 3175, in from_pretrained
    ) = cls._load_pretrained_model(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/transformers/modeling_utils.py", line 3563, in _load_pretrained_model
    new_error_msgs, offload_index, state_dict_index = _load_state_dict_into_meta_model(
                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/transformers/modeling_utils.py", line 745, in _load_state_dict_into_meta_model
    set_module_tensor_to_device(model, param_name, param_device, **set_module_kwargs)
  File "/usr/local/lib/python3.11/site-packages/accelerate/utils/modeling.py", line 281, in set_module_tensor_to_device
    raise ValueError(
ValueError: Trying to set a tensor of shape torch.Size([0]) in "weight" (which has shape torch.Size([32000, 2048])), this look incorrec
```

**Comment by hahmad2008** [comment]
@winglian the configuration I used:

```
base_model: TinyLlama/TinyLlama-1.1B-step-50K-105b
base_model_config: TinyLlama/TinyLlama-1.1B-step-50K-105b
model_type: LlamaForCausalLM
tokenizer_type: LlamaTokenizer
tokenizer_legacy: false
is_llama_derived_model: true

load_in_8bit: false
load_in_4bit: true
strict: false

datasets:
  - path: data.jsonl
    type: completion
    field: text

dataset_prepared_path: 
val_set_size: 0.08
output_dir: full-finetune-zero3/

adapter: 
lora_model_dir:

sequence_len: 512
sample_packing: false
pad_to_sequence_len: true

lora_r: 32
lora_alpha: 16
lora_dropout: 0.05
lora_target_modules:
lora_target_linear: true
lora_fan_in_fan_out:
wandb_project:
wandb_entity:
wandb_watch:
wandb_name:
wandb_log_model:

gradient_accumulation_steps: 4
eval_accumulation_steps: 1
micro_batch_size: 1
num_epochs: 2
optimizer: adamw_torch
lr_scheduler: cosine
learning_rate: 0.0002

train_on_inputs: false
group_by_length: false
bf16: false
fp16: true
tf32: false

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint: 
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: false

warmup_steps: 10
evals_per_epoch: 1
eval_table_size:
saves_per_epoch: 1
debug:
deepspeed: deepspeed/zero3.json
weight_decay: 0.0
fsdp:
fsdp_config:
special_tokens:
  bos_token: "<s>"
  eos_token: "</s>"
  unk_token: "<unk>"
```
