### ISSUE TITLE
[Solution] `_make_sliding_window_causal_mask() Expected a value of type 'int' for argument 'sliding_window' but instead found type 'NoneType'.` in mistral instruct v0.2

### ISSUE THREAD

**Issue by NanoCode012** [axolotl-ai-cloud/axolotl#1047]
Edit: This should now be fixed by Dream. You do not need this anymore!

---

### What piece of documentation is affected?

If you get this error in title, it's because mistral instruct v0.2 does not provide value for `sliding_window: null` . It is necessary to override this value for sample packing + FA to work.

### What part(s) of the article would you like to see updated?

Add to yaml
```yml
model_config:
  sliding_window: 4096
```

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by DreamGenX** [comment]
I don't think this is a correct solution. This re-enables sliding-window attention, which is explicitly disabled in instruct. This might lead to some impact on quality.
