### ISSUE TITLE
Support python 3.10 and higher

### ISSUE THREAD

**Issue by ehartford** [axolotl-ai-cloud/axolotl#107]
Currently axolotl requires python 3.9
Python 3.10 and 3.11 will fail due to dependency issue
Can you please update the dependencies so that axolotl will work in 3.10 and 3.11

**Comment by fredi-python** [comment]
That would be awesome.

**Comment by winglian** [comment]
this fix should unblock py3.10 https://github.com/OpenAccess-AI-Collective/axolotl/pull/90

**Comment by winglian** [comment]
will add an image for py310 here: https://github.com/OpenAccess-AI-Collective/axolotl/pull/115
