### ISSUE TITLE
Mistral default prompt format

### ISSUE THREAD

**Issue by infopz** [axolotl-ai-cloud/axolotl#1109]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/OpenAccess-AI-Collective/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

I was just looking at the config examples and i notice that in the mistral folder, every file uses the "alpaca" dataset format.
In order to be trained properly, is not better to use the default suggested prompt format?

### Current behaviour

The examples uses the alpaca format

### Steps to reproduce

look at files

### Which Operating Systems are you using?

- [ ] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.10

### axolotl branch-commit

main

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by SicariusSicariiStuff** [comment]
its not a bug. you can use any format. i use sharegpt.
