### ISSUE TITLE
MistralForCausalLM crashes when using pre-tokenized dataset

### ISSUE THREAD

**Issue by calclavia** [axolotl-ai-cloud/axolotl#1143]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/OpenAccess-AI-Collective/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

Mistral 7B fine tuning should work with pretokenized dataset.

### Current behaviour

Currently, training crashes if I use a pre-tokenized dataset:

```
[2024-01-18 15:46:58,587] [ERROR] [axolotl.load_model:544] [PID:29] [RANK:1] MistralForCausalLM.__init__() got an unexpected keyword argument 'attn_implementation'
Traceback (most recent call last):
  File "/workspace/axolotl/src/axolotl/utils/models.py", line 502, in load_model
    model = getattr(transformers, model_type).from_pretrained(
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3316, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 459, in wrapper
    f(module, *args, **kwargs)
TypeError: MistralForCausalLM.__init__() got an unexpected keyword argument 'attn_implementation'

```

### Steps to reproduce

1. Create a pretokenized dataset with "input_ids", "labels" and "attention_mask"
2. Train with the attached config

### Config yaml

```yaml
base_model: mistralai/Mistral-7B-v0.1
model_type: MistralForCausalLM
tokenizer_type: LlamaTokenizer
is_mistral_derived_model: true

load_in_8bit: false
load_in_4bit: false
strict: false

datasets:
  - path: dataset.jsonl

dataset_prepared_path:
val_set_size: 0.04
output_dir: ./out

sequence_len: 8192
sample_packing: true
eval_sample_packing: true
pad_to_sequence_len: true

gradient_accumulation_steps: 4
micro_batch_size: 2
num_epochs: 1
optimizer: adamw_bnb_8bit
lr_scheduler: cosine
learning_rate: 0.000005

bf16: true
fp16: false
tf32: false
train_on_inputs: false
group_by_length: false

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true

warmup_steps: 10
save_steps:
debug:
deepspeed: /root/axolotl/deepspeed/zero3.json
weight_decay: 0.0
fsdp:
fsdp_config:
special_tokens:
  bos_token: "<s>"
  eos_token: "</s>"
  unk_token: "<unk>"
```

### Which Operating Systems are you using?

- [X] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.10

### axolotl branch-commit

axolotl:main-py3.10-cu118-2.0.1

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by winglian** [comment]
How old of a version of transformers are you using? Can you try updating to latest transformers from main?

**Comment by calclavia** [comment]
@winglian Updating fixed it. Thanks!
