### ISSUE TITLE
import flash_attn_2_cuda as flash_attn_cuda ImportError

### ISSUE THREAD

**Issue by SoniCoder** [axolotl-ai-cloud/axolotl#1157]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/OpenAccess-AI-Collective/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

Should work

### Current behaviour

Getting the following error in axolotl while doing LLM training:

    import flash_attn_2_cuda as flash_attn_cuda
import flash_attn_2_cuda as flash_attn_cuda
ImportError: ImportError/home/phoenix/anaconda3/envs/axo/lib/python3.11/site-packages/flash_attn_2_cuda.cpython-311-x86_64-linux-gnu.so: undefined 
symbol: _ZN3c104cuda9SetDeviceEi:
/home/phoenix/anaconda3/envs/axo/lib/python3.11/site-packages/flash_attn_2_cuda.cpython-311-x86_64-linux-gnu.so: undefined symbol: _ZN3c104cuda9SetDeviceEi
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 1274) of binary: /home/phoenix/anaconda3/envs/axo/bin/python

### Steps to reproduce

accelerate launch -m axolotl.cli.train examples/openllama-3b/qlora.yml

### Which Operating Systems are you using?

- [X] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.11

### axolotl branch-commit

2ce5c0d68a9cf1db1fa9a7861c6ed3bb117c5f8b

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by SoniCoder** [comment]
Solved this by reinstalling matching versions of pytorch's cuda, etc.

**Comment by SLR722** [comment]
@SoniCoder 'Matching versions of pytorch's cuda', do you mean cuda and pytorch-cuda versions are matched?
