### ISSUE TITLE
Warn user if hub_model_id is set without setting save_steps or saves_per_epoch

### ISSUE THREAD

**Issue by winglian** [axolotl-ai-cloud/axolotl#1193]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/OpenAccess-AI-Collective/axolotl/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/OpenAccess-AI-Collective/axolotl/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

The model doesn't get saved if save steps aren't explicitly defined. If the user is setting hub_model_id, they probably have the expectation it should save. 

### ✔️ Solution

in validate_config function, let's raise a ValueError with a message that they should set one of the various save settings.

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by JohanWork** [comment]
@winglian believe you can close this one :)
