### ISSUE TITLE
[Bug] xformer requires alpaca_lora_4bit install even if we don't use gptq

### ISSUE THREAD

**Issue by NanoCode012** [axolotl-ai-cloud/axolotl#122]
If we turn on xformer but don't need gptq (only qlora for example), it will not work as it imports from alpaca_lora_4bit.

Discord user faced this as well: https://discord.com/channels/1104757954588196865/1111279858136383509/1113300840913055764

Move https://github.com/johnsmith0031/alpaca_lora_4bit/blob/main/monkeypatch/llama_attn_hijack_xformers.py to repo

**Comment by utensil** [comment]
#124 is addressing this.

Before the fix, training qlora with xformer disabled confirms to work with a smaller `micro_batch_size`, e.g. decrease from 12 to 8

**Comment by NanoCode012** [comment]
Fixed by https://github.com/OpenAccess-AI-Collective/axolotl/pull/124
