### ISSUE TITLE
Conflicting dependencies in version 0.4.0

### ISSUE THREAD

**Issue by eryk-mazus** [axolotl-ai-cloud/axolotl#1238]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/OpenAccess-AI-Collective/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

I tried to install axolotl by following instructions for developers from README:
```
git clone https://github.com/OpenAccess-AI-Collective/axolotl
cd axolotl

pip3 install packaging
pip3 install -e '.[flash-attn,deepspeed]'
```
and then in alternative way:
```
pip3 install "axolotl[flash-attn,deepspeed] @ git+https://github.com/OpenAccess-AI-Collective/axolotl"
```

In both cases I get the error attached below:

### Current behaviour

```
ERROR: Cannot install axolotl and axolotl[deepspeed,flash-attn]==0.4.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    axolotl[deepspeed,flash-attn] 0.4.0 depends on torch==2.1.0
    accelerate 0.26.1 depends on torch>=1.10.0
    flash-attn 2.5.0 depends on torch
    optimum 1.16.2 depends on torch>=1.11
    deepspeed 0.13.1 depends on torch
    trl 0.7.9 depends on torch>=1.4.0
    xformers 0.0.24 depends on torch==2.2.0
    axolotl[deepspeed,flash-attn] 0.4.0 depends on torch==2.1.0
    accelerate 0.26.1 depends on torch>=1.10.0
    flash-attn 2.5.0 depends on torch
    optimum 1.16.2 depends on torch>=1.11
    deepspeed 0.13.1 depends on torch
    trl 0.7.9 depends on torch>=1.4.0
    xformers 0.0.23.post1 depends on torch==2.1.2
    axolotl[deepspeed,flash-attn] 0.4.0 depends on torch==2.1.0
    accelerate 0.26.1 depends on torch>=1.10.0
    flash-attn 2.5.0 depends on torch
    optimum 1.16.2 depends on torch>=1.11
    deepspeed 0.13.1 depends on torch
    trl 0.7.9 depends on torch>=1.4.0
    xformers 0.0.23 depends on torch==2.1.1

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

### Steps to reproduce

I just followed the instructions on fresh instance.

### Which Operating Systems are you using?

- [X] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.10.13

### axolotl branch-commit

main

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by winglian** [comment]
Might be related to xformers. I haven't seen this issue with our automated ci builds, but some of the problem arises from the latest torch 2.2.0 release

**Comment by winglian** [comment]
@eryk-mazus what version of torch do you already have installed?

**Comment by eryk-mazus** [comment]
I'm using a docker image with pytorch 2.1.0

**Comment by winglian** [comment]
Have you tried the axolotl images? https://hub.docker.com/r/winglian/axolotl/tags

**Comment by dctanner** [comment]
Just bumped into this issue today on a fresh ubuntu 22.04 using today's main branch.

**Comment by winglian** [comment]
Try upgrading to torch 2.1.2. I think torch 2.1.1 may be unsupported in the current dependency tree.

**Comment by dctanner** [comment]
The issue seems to be caused by a new version of xformers released yesterday.

I fixed it by first installing torch==2.1.1. manualy
Edited setup.py line to be 0.0.23:
```
            _install_requires.append("xformers==0.0.23")
```
pip3 install -e '.[flash-attn,deepspeed]'

**Comment by HenryNewcomer** [comment]
> The issue seems to be caused by a new version of xformers released yesterday.
> 
> I fixed it by first installing torch==2.1.1. manualy Edited setup.py line to be 0.0.23:
> 
> ```
>             _install_requires.append("xformers==0.0.23")
> ```
> 
> pip3 install -e '.[flash-attn,deepspeed]'

I tried with `!pip install torch==2.1.1+cu118 -f https://download.pytorch.org/whl/torch_stable.html` but now when I run `accelerate launch -m axolotl.cli.train finetune.yml`, I'm getting:

> False
> 
> ===================================BUG REPORT===================================
> /usr/local/lib/python3.10/dist-packages/bitsandbytes/cuda_setup/main.py:167: UserWarning: Welcome to bitsandbytes. For bug reports, please run
> 
> python -m bitsandbytes
> 
> 
>   warn(msg)
> ================================================================================
> /usr/local/lib/python3.10/dist-packages/bitsandbytes/cuda_setup/main.py:167: UserWarning: /usr/lib64-nvidia did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
>   warn(msg)
> The following directories listed in your path were found to be non-existent: {PosixPath('/sys/fs/cgroup/memory.events /var/colab/cgroup/jupyter-children/memory.events')}
> The following directories listed in your path were found to be non-existent: {PosixPath('//172.28.0.1'), PosixPath('8013'), PosixPath('http')}
> The following directories listed in your path were found to be non-existent: {PosixPath('//colab.research.google.com/tun/m/cc48301118ce562b961b3c22d803539adc1e0c19/gpu-a100-s-2y74nmlgj53wz --tunnel_background_save_delay=10s --tunnel_periodic_background_save_frequency=30m0s --enable_output_coalescing=true --output_coalescing_required=true'), PosixPath('--logtostderr --listen_host=172.28.0.12 --target_host=172.28.0.12 --tunnel_background_save_url=https')}
> The following directories listed in your path were found to be non-existent: {PosixPath('/datalab/web/pyright/typeshed-fallback/stdlib,/usr/local/lib/python3.10/dist-packages')}
> The following directories listed in your path were found to be non-existent: {PosixPath('/env/python')}
> The following directories listed in your path were found to be non-existent: {PosixPath('module'), PosixPath('//ipykernel.pylab.backend_inline')}
> CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
> DEBUG: Possible options found for libcudart.so: {PosixPath('/usr/local/cuda/lib64/libcudart.so')}
> CUDA SETUP: PyTorch settings found: CUDA_VERSION=118, Highest Compute Capability: 8.0.
> CUDA SETUP: To manually override the PyTorch CUDA version please see:https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
> CUDA SETUP: Loading binary /usr/local/lib/python3.10/dist-packages/bitsandbytes/libbitsandbytes_cuda118.so...
> libcusparse.so.11: cannot open shared object file: No such file or directory
> CUDA SETUP: Something unexpected happened. Please compile from source:
> git clone https://github.com/TimDettmers/bitsandbytes.git
> cd bitsandbytes
> CUDA_VERSION=118 make cuda11x
> python setup.py install
> Traceback (most recent call last):
>   File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
>     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
>   File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
>     __import__(pkg_name)
>   File "/content/axolotl/src/axolotl/cli/__init__.py", line 24, in <module>
>     from axolotl.common.cli import TrainerCliArgs, load_model_and_tokenizer
>   File "/content/axolotl/src/axolotl/common/cli.py", line 12, in <module>
>     from axolotl.utils.models import load_model, load_tokenizer
>   File "/content/axolotl/src/axolotl/utils/models.py", line 8, in <module>
>     import bitsandbytes as bnb
>   File "/usr/local/lib/python3.10/dist-packages/bitsandbytes/__init__.py", line 6, in <module>
>     from . import cuda_setup, utils, research
>   File "/usr/local/lib/python3.10/dist-packages/bitsandbytes/research/__init__.py", line 1, in <module>
>     from . import nn
>   File "/usr/local/lib/python3.10/dist-packages/bitsandbytes/research/nn/__init__.py", line 1, in <module>
>     from .modules import LinearFP8Mixed, LinearFP8Global
>   File "/usr/local/lib/python3.10/dist-packages/bitsandbytes/research/nn/modules.py", line 8, in <module>
>     from bitsandbytes.optim import GlobalOptimManager
>   File "/usr/local/lib/python3.10/dist-packages/bitsandbytes/optim/__init__.py", line 6, in <module>
>     from bitsandbytes.cextension import COMPILED_WITH_CUDA
>   File "/usr/local/lib/python3.10/dist-packages/bitsandbytes/cextension.py", line 20, in <module>
>     raise RuntimeError('''
> RuntimeError: 
>         CUDA Setup failed despite GPU being available. Please run the following command to get more information:
> 
>         python -m bitsandbytes
> 
>         Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
>         to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
>         and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues
> Traceback (most recent call last):
>   File "/usr/local/bin/accelerate", line 8, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/accelerate_cli.py", line 47, in main
>     args.func(args)
>   File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 1023, in launch_command
>     simple_launcher(args)
>   File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 643, in simple_launcher
>     raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
> subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'axolotl.cli.train', 'finetune.yml']' returned non-zero exit status 1.

Thoughts/suggestions? Torch.__version__ is showing `2.1.1+cu118`.

**Comment by eryk-mazus** [comment]
> Have you tried the axolotl images? https://hub.docker.com/r/winglian/axolotl/tags

I can confirm that 'winglian/axolotl:main-py3.10-cu121-2.1.1' works without any issues.

**Comment by OlivierH71** [comment]
> ### Please check that this issue hasn't been reported before.
> * [x]  I searched previous [Bug Reports](https://github.com/OpenAccess-AI-Collective/axolotl/labels/bug) didn't find any similar reports.
> 
> ### Expected Behavior
> I tried to install axolotl by following instructions for developers from README:
> 
> ```
> git clone https://github.com/OpenAccess-AI-Collective/axolotl
> cd axolotl
> 
> pip3 install packaging
> pip3 install -e '.[flash-attn,deepspeed]'
> ```
> 
> and then in alternative way:
> 
> ```
> pip3 install "axolotl[flash-attn,deepspeed] @ git+https://github.com/OpenAccess-AI-Collective/axolotl"
> ```
> 
> In both cases I get the error attached below:
> 
> ### Current behaviour
> ```
> ERROR: Cannot install axolotl and axolotl[deepspeed,flash-attn]==0.4.0 because these package versions have conflicting dependencies.
> 
> The conflict is caused by:
>     axolotl[deepspeed,flash-attn] 0.4.0 depends on torch==2.1.0
>     accelerate 0.26.1 depends on torch>=1.10.0
>     flash-attn 2.5.0 depends on torch
>     optimum 1.16.2 depends on torch>=1.11
>     deepspeed 0.13.1 depends on torch
>     trl 0.7.9 depends on torch>=1.4.0
>     xformers 0.0.24 depends on torch==2.2.0
>     axolotl[deepspeed,flash-attn] 0.4.0 depends on torch==2.1.0
>     accelerate 0.26.1 depends on torch>=1.10.0
>     flash-attn 2.5.0 depends on torch
>     optimum 1.16.2 depends on torch>=1.11
>     deepspeed 0.13.1 depends on torch
>     trl 0.7.9 depends on torch>=1.4.0
>     xformers 0.0.23.post1 depends on torch==2.1.2
>     axolotl[deepspeed,flash-attn] 0.4.0 depends on torch==2.1.0
>     accelerate 0.26.1 depends on torch>=1.10.0
>     flash-attn 2.5.0 depends on torch
>     optimum 1.16.2 depends on torch>=1.11
>     deepspeed 0.13.1 depends on torch
>     trl 0.7.9 depends on torch>=1.4.0
>     xformers 0.0.23 depends on torch==2.1.1
> 
> To fix this you could try to:
> 1. loosen the range of package versions you've specified
> 2. remove package versions to allow pip attempt to solve the dependency conflict
> 
> ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
> ```
> 
> ### Steps to reproduce
> I just followed the instructions on fresh instance.
> 
> ### Config yaml
> _No response_
> 
> ### Possible solution
> _No response_
> 
> ### Which Operating Systems are you using?
> * [x]  Linux
> * [ ]  macOS
> * [ ]  Windows
> 
> ### Python Version
> 3.10.13
> 
> ### axolotl branch-commit
> main
> 
> ### Acknowledgements
> * [x]  My issue title is concise, descriptive, and in title casing.
> * [x]  I have searched the existing issues to make sure this bug has not been reported yet.
> * [x]  I am using the latest version of axolotl.
> * [x]  I have provided enough information for the maintainers to reproduce and diagnose the issue.

in my case, I ended-up with commenting the install requires of torch here:
#_install_requires.append(f"torch=={torch_version}")
That sound crazy as if there is a previous version installed of torch, THIS installed version it is considered as required but may be incompatible with other library requirements.

**Comment by OlivierH71** [comment]
in my case, I ended-up with commenting the install_requires of torch in setup.py like this:
```
torch_version = version("torch")
#_install_requires.append(f"torch=={torch_version}")
```
That command sounds crazy as if there is a previous version installed of torch, THIS installed version it is considered as required but may be incompatible with other library requirements and forbid its install/upgrade.

**Comment by winglian** [comment]
What version of torch did you originally have installed? We try to pin the existing version of torch otherwise it always tries to upgrade everyone to 2.4.0.
