### ISSUE TITLE
[Feature] Automatic Rebase

### ISSUE THREAD

**Issue by NanoCode012** [axolotl-ai-cloud/axolotl#125]
For a cleaner tree

https://github.com/marketplace/actions/automatic-rebase

**Comment by winglian** [comment]
my main concern is the use of a secret GitHub token or pat token on the repo level. Could someone submit a PR with a malicious payload that abuses the token?

**Comment by NanoCode012** [comment]
That is a great point. I believe that is why for new PRs by newcomers do not run workflows by default until Approved.

More info: https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#stealing-the-jobs-github_token

Since I do not have a safe solution, we can close this Issue for now until there is a good way to mitigate this.
