### ISSUE TITLE
More save strategies for DPO training.

### ISSUE THREAD

**Issue by PhilipMay** [axolotl-ai-cloud/axolotl#1253]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/OpenAccess-AI-Collective/axolotl/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/OpenAccess-AI-Collective/axolotl/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

When I do DPO training it only allows steps save strategy.
This is because it is hard wired here:

https://github.com/OpenAccess-AI-Collective/axolotl/blob/2d65f470d54986f2df542cb8332e31113c04112d/src/axolotl/core/trainer_builder.py#L1095

The consequence is that it is not possible to specify "epoch" strategy and it is almost
impossible to save after the last step.

### ✔️ Solution

Make save_strategy configurable like in `HFCausalTrainerBuilder`.

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by filippo82** [comment]
Hi @PhilipMay, are you willing to start working on a PR to improve this issue?

**Comment by PhilipMay** [comment]
> Hi @PhilipMay, are you willing to start working on a PR to improve this issue?

I can do.

**Comment by PhilipMay** [comment]
@filippo82 see #1255 - can you approve the workflows please?

**Comment by filippo82** [comment]
Hi @PhilipMay, I'll review this as soon as I can.

**Comment by filippo82** [comment]
@PhilipMay the corresponding PR was merged. Hence, you can close this issue.

**Comment by PhilipMay** [comment]
> @PhilipMay the corresponding PR was merged. Hence, you can close this issue.

thanks
