### ISSUE TITLE
AttributeError: 'Qwen2TokenizerFast' object has no attribute 'eod_id'

### ISSUE THREAD

**Issue by interstellarninja** [axolotl-ai-cloud/axolotl#1260]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/OpenAccess-AI-Collective/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

when i run axolotl.cli.preprocess with qwen models i get this attribute error with 'Qwen2TokenizerFast' instead of tokenizing the dataset.

### Current behaviour

here's the full stacktrace:
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/nous/llm-projects/axolotl/src/axolotl/cli/preprocess.py", line 55, in <module>
    fire.Fire(do_cli)
  File "/home/nous/.local/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/nous/.local/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/nous/.local/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/nous/llm-projects/axolotl/src/axolotl/cli/preprocess.py", line 46, in do_cli
    _ = load_datasets(cfg=parsed_cfg, cli_args=parsed_cli_args)
  File "/home/nous/llm-projects/axolotl/src/axolotl/cli/__init__.py", line 310, in load_datasets
    tokenizer = load_tokenizer(cfg)
  File "/home/nous/llm-projects/axolotl/src/axolotl/utils/models.py", line 152, in load_tokenizer
    setattr(tokenizer, attr_name, tokenizer.eod_id)
AttributeError: 'Qwen2TokenizerFast' object has no attribute 'eod_id'
```

### Steps to reproduce

python3 -m axolotl.cli.preprocess path/to/config.yaml --debug

### Config yaml

base_model: Qwen/Qwen1.5-1.8B
model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer
is_qwen_derived_model: true
trust_remote_code: true

load_in_8bit: false
load_in_4bit: false
strict: false

datasets:
  - path: NousResearch/mini-hermes-24k
    type: sharegpt
    conversation: chatml

dataset_prepared_path: last_run_prepared
val_set_size: 0.0
output_dir: ./qwen-0_5b-sft

sequence_len: 32768  # supports up to 8192
sample_packing: false
pad_to_sequence_len:

adapter:
lora_model_dir:
lora_r: 32
lora_alpha: 16
lora_dropout: 0.05
lora_target_linear: true
lora_fan_in_fan_out:

wandb_project: qwen-function-calling
wandb_run_id: qwen-0_5-func-calling-1

gradient_accumulation_steps: 4
micro_batch_size: 2
num_epochs: 4
optimizer: adamw_bnb_8bit
lr_scheduler: cosine
learning_rate: 0.0002

train_on_inputs: false
group_by_length: false
bf16: true
fp16: false
tf32: false

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention:

warmup_steps: 100
save_total_limit: 3
saves_per_epoch: 1
debug:
deepspeed: deepspeed/zero1.json
weight_decay: 0.1

fsdp:
fsdp_config:

special_tokens:
  eos_token: "<|im_end|>"
tokens:
  - "<|im_start|>"

hub_model_id: interstellarninja/Qwen-0_5b-func-calling

### Which Operating Systems are you using?

- [X] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.10

### axolotl branch-commit

main

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by winglian** [comment]
@interstellarninja remove `is_qwen_derived_model: true`

**Comment by interstellarninja** [comment]
I've removed it but it still hasn't solved the issue

**Comment by interstellarninja** [comment]
thanks removing it and git pull solved the issue

**Comment by deltawi** [comment]
I am still facing this issue if I want to finetune Qwen models using the script `finetune/finetune_lora_single_gpu.sh` I get the error: 
```
Traceback (most recent call last):
  File "/Qwentuning/Qwen/finetune.py", line 374, in <module>
    train()
  File "/Qwentuning/Qwen/finetune.py", line 328, in train
    tokenizer.pad_token_id = tokenizer.eod_id
AttributeError: 'Qwen2Tokenizer' object has no attribute 'eod_id'
```

**Comment by interstellarninja** [comment]
have you tried is_qwen_derived_model: true?

**Comment by winglian** [comment]
> I am still facing this issue if I want to finetune Qwen models using the script `finetune/finetune_lora_single_gpu.sh` I get the error: 
> 
> ```
> 
> Traceback (most recent call last):
> 
>   File "/Qwentuning/Qwen/finetune.py", line 374, in <module>
> 
>     train()
> 
>   File "/Qwentuning/Qwen/finetune.py", line 328, in train
> 
>     tokenizer.pad_token_id = tokenizer.eod_id
> 
> AttributeError: 'Qwen2Tokenizer' object has no attribute 'eod_id'
> 
> ```

Those don't seem like scripts from axolotl. Are you using the correct project?

**Comment by deltawi** [comment]
Guys my apologies, yes I am using the script for finetuning Qwen model from the official repo. Not this project.
