### ISSUE TITLE
Request: Good Qwen 1.5 examples

### ISSUE THREAD

**Issue by Taytay** [axolotl-ai-cloud/axolotl#1266]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/OpenAccess-AI-Collective/axolotl/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/OpenAccess-AI-Collective/axolotl/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

I'd love to have a definitive example to train one of the new Qwen1.5 models: https://github.com/QwenLM/Qwen1.5

### ✔️ Solution

I am trying to use the Qwen examples to train the new Qwen1.5, and ran into this error: https://github.com/OpenAccess-AI-Collective/axolotl/issues/1260
My training was also pretty slow, my chat format appears incorrect, and I hit a gptq error as well. All that is to say, I am pretty sure my settings aren't ideal. If anyone has written a good example for fine tuning one of the new Qwen1.5 models (like say, oh @interstellarninja), it would be awesome to have one in this repo.

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by interstellarninja** [comment]
please remove `is_qwen_derived_model: true` as suggested by @winglian and pull the latest code

**Comment by NanoCode012** [comment]
I've also made a PR to remove this config from all examples, so this issue should be resolved? You may use the current qwen examples since winglian added better qwen2 integration.

**Comment by adi-kmt** [comment]
Hey @NanoCode012 @interstellarninja, so i don't have to set eos, bos and other tokens? like in the code?

**Comment by NanoCode012** [comment]
You may use the current example with that config mentioned above removed.
