### ISSUE TITLE
EvalFirstStepCallback only happens when eval_steps < 1.0

### ISSUE THREAD

**Issue by LeonardoEmili** [axolotl-ai-cloud/axolotl#1279]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/OpenAccess-AI-Collective/axolotl/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/OpenAccess-AI-Collective/axolotl/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

I found it odd to discover that validation always happens on first step which is great for sanity/baseline, but this is only true when `eval_steps` is expressed as a fraction of total steps, eliminating the cases when a custom validation set is provided or when `eval_steps` is simply given as a number. Maybe trivial but I don't see why limit this feature to this narrow use-case. Shall we set as a practice to always perform validation on step 1 (other frameworks as PL do something similar too).

### ✔️ Solution

Simply remove L65 from [file](https://github.com/OpenAccess-AI-Collective/axolotl/blob/1daecd161ec40f9496059572483d85247baa370e/src/axolotl/utils/callbacks.py#L65).

### 📝 Additional Context

Nothing more to add, thanks for the great project, keep up the good work!

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by LeonardoEmili** [comment]
Maybe @winglian could help here?

**Comment by NanoCode012** [comment]
Hey, could you make a PR on this? I think this sounds good.
