### ISSUE TITLE
RunPod Docker Link is broken

### ISSUE THREAD

**Issue by Stillerman** [axolotl-ai-cloud/axolotl#1318]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/OpenAccess-AI-Collective/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

Clicking the link should open RunPod with the template selected. It worked a few days ago.

### Current behaviour

It does not

### Steps to reproduce

Click the link.

### Which Operating Systems are you using?

- [ ] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.10

### axolotl branch-commit

main

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by NanoCode012** [comment]
Hm, I just tested a few times, and it seems to work for me.

**Comment by Aillian** [comment]
facing the same issue, i'm running this template `winglian/axolotl-runpod:main-py3.10-cu118–2.0.1`

**Comment by bursteratom** [comment]
Closing this as our recent tests of different templates are all working and there have been no newer reports of similar issues
