### ISSUE TITLE
DoRA Support

### ISSUE THREAD

**Issue by fakerybakery** [axolotl-ai-cloud/axolotl#1328]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/OpenAccess-AI-Collective/axolotl/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/OpenAccess-AI-Collective/axolotl/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

Add DoRA

### ✔️ Solution

Add [DoRA](https://arxiv.org/abs/2402.09353) for training, preferably with quantized support similar to QLoRA.

### ❓ Alternatives

LoRA, but DoRA outperforms

### 📝 Additional Context

No official implementation, but several unofficial ones:

* https://github.com/catid/dora
* https://github.com/rasbt/dora-from-scratch

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by younesbelkada** [comment]
DoRA is now added in PEFT main: https://github.com/huggingface/peft/pull/1474 you just need to pass `use_dora=True` in `LoraConfig`
