### ISSUE TITLE
Train without eos token?

### ISSUE THREAD

**Issue by StableFluffy** [axolotl-ai-cloud/axolotl#1330]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/OpenAccess-AI-Collective/axolotl/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/OpenAccess-AI-Collective/axolotl/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

Add feature to train without eos tokens

### ✔️ Solution

I try to train raw corpus but i can't find a way to disable eos token.

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by StableFluffy** [comment]
So, when i set the type 'completion' it works as intended. (no eos)
But when with custom prompt template there's no option to disable eos.
The reason why i use custom template is to mask some tokens.

**Comment by NanoCode012** [comment]
@StableFluffy , I believe there is eos for completion? 

You may need to tokenize it yourself otherwise like said in #990 ?

**Comment by StableFluffy** [comment]
Hi, I tried to tokenize on my own. 
It works well. I'll close this issue.
