### ISSUE TITLE
flash_attn breaking, how to disable?

### ISSUE THREAD

**Issue by jabberjabberjabber** [axolotl-ai-cloud/axolotl#1359]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/OpenAccess-AI-Collective/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

It should work

### Current behaviour

Flash attention doesn't support any GPU lower than ampere.

### Steps to reproduce

 accelerate launch -m axolotl.cli.train ./examples/openllama-3b/qlora.yml

### Possible solution

How do I disable flash_attn? I have p40 GPUs and cannot figure out where to do this. If it is so integrated that it won't work otherwise can you please add somewhere that it won't work with GPUs lower than Ampere? 

### Which Operating Systems are you using?

- [ ] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.10

### axolotl branch-commit

main

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by NanoCode012** [comment]
Hey, you can do `flash_attention: false`
