### ISSUE TITLE
[Feature] Add GPU matrix with supported features to Readme

### ISSUE THREAD

**Issue by NanoCode012** [axolotl-ai-cloud/axolotl#136]
It would be nice to see which feature play well on which GPU. This can be crowd contribution.

**Comment by Glavin001** [comment]
This would be so nice for newcomers (like me)!

**Comment by NanoCode012** [comment]
I believe the only features unsupported on older nvidia GPUs would be `bf16`, `tf32`, and `flash_attention:`.
