### ISSUE TITLE
[Feature] Add doc explaining how to add own prompt method

### ISSUE THREAD

**Issue by NanoCode012** [axolotl-ai-cloud/axolotl#137]
Explain how to add custom prompt method under `prompt_strategies` and passing the custom type to `type: `

**Comment by winglian** [comment]
I'd like to refactor all the current strategies into the new way of handling these. That way users don't get confused between the old and new, but that shouldn't prevent this doc from getting written

**Comment by NanoCode012** [comment]
Could you provide an example on how to use (for instance, pygmalion)?

This can be useful for someone to look at this afterward.

Is it 

```yaml
datasets:
  - path: path/to/file
    type: pygmalion
```

I don't quite get the code which parses the strategy.
