### ISSUE TITLE
Can we add rslora?

### ISSUE THREAD

**Issue by kostum123** [axolotl-ai-cloud/axolotl#1383]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/OpenAccess-AI-Collective/axolotl/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/OpenAccess-AI-Collective/axolotl/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

Currently there is no way to pass use_rslora: true to lora config. 

### ✔️ Solution

We should be  able to pass use_rslora: true to lora config.

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by gotzmann** [comment]
It would be nice to have. I've started experimenting with RSLora using LLaMA-Factory

**Comment by winglian** [comment]
Is rslora already integrated into peft? If so it should be simple  like https://github.com/OpenAccess-AI-Collective/axolotl/pull/1363/files
