### ISSUE TITLE
`load_model_and_tokenizer` always merges peft models by default

### ISSUE THREAD

**Issue by chiragjn** [axolotl-ai-cloud/axolotl#1392]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/OpenAccess-AI-Collective/axolotl/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/OpenAccess-AI-Collective/axolotl/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

I was stepping through `do_merge_lora` 
https://github.com/OpenAccess-AI-Collective/axolotl/blob/43265208299242e3bc32690e22efadef79365c9d/src/axolotl/cli/__init__.py#L121-L130

and noticed that `load_model_and_tokenizer` always merges the model 
https://github.com/OpenAccess-AI-Collective/axolotl/blob/43265208299242e3bc32690e22efadef79365c9d/src/axolotl/utils/models.py#L807-L808

Is there a way to keep the model unmerged?

### ✔️ Solution

afaik, There is no harm in trying to merge twice but Maybe `do_merge_lora` should ask `load_model` to strictly return a peft model for validation sake?
Not sure 😅 

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by NanoCode012** [comment]
Hey, the first case is intended. It's only called when you explicitly call the cli
```
python3 -m axolotl.cli.merge_lora your_config.yml --lora_model_dir="./completed-model"
```

The latter is a newer change, which I'll follow up. However, at that point in the code, the lora from `lora_model_dir` is not loaded yet.  It's a bit further down: https://github.com/OpenAccess-AI-Collective/axolotl/blob/43265208299242e3bc32690e22efadef79365c9d/src/axolotl/utils/models.py#L912-L919

**Comment by chiragjn** [comment]
Interesting, in my case I am not passing a lora_model_dir and instead my output dir itself has adapters saved post training.
From the README

> The following command will merge your LORA adapater with your base model. You can optionally pass the argument --lora_model_dir to specify the directory where your LORA adapter was saved, otherwhise, this will be inferred from output_dir in your axolotl config file

My code looks like this:

```
from axolotl.cli.merge_lora import do_cli as axolotl_merge_lora_cli
from axolotl.cli.train import do_cli as axolotl_train_cli
axolotl_train_cli(config=axolotl_config)
# model adapters are now saved in output_dir
axolotl_merge_lora_cli(config=axolotl_config)
```

I think because `AutoModelForCausalLM.from_pretrained` now returns `PeftModelForCausalLM` the merge just happens

**Comment by NanoCode012** [comment]
May I ask what you would like to do? If you do not want to merge, you shouldn't need to call the merge function?

**Comment by chiragjn** [comment]
Nevermind, I messed up my config and passed my output dir as `base_model` which is why it loaded peft model and merged it in `load_model_and_tokenizer`
Apologies for the confusion 🙃
