### ISSUE TITLE
Need an option not to shuffle the merged dataset

### ISSUE THREAD

**Issue by seungduk-yanolja** [axolotl-ai-cloud/axolotl#1393]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/OpenAccess-AI-Collective/axolotl/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/OpenAccess-AI-Collective/axolotl/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

Sometimes, it is a strategy to keep the dataset order as listed in the config. In that case, we need to prevent shuffling the merged dataset.

### ✔️ Solution

Add a config parameter that prevents shuffling.

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by ehartford** [comment]
I agree with the sentiment.

The answer has always been "just comment out the shuffle line in the code"

But really what makes Axolotl stand out among these tools is that it's config based instead of making users change code.

I believe that putting these rich options into the config file will give Axolotl a huge usability advantage.

**Comment by seungduk-yanolja** [comment]
> I agree with the sentiment.
> 
> The answer has always been "just comment out the shuffle line in the code"
> 
> But really what makes Axolotl stand out among these tools is that it's config based instead of making users change code.
> 
> I believe that putting these rich options into the config file will give Axolotl a huge usability advantage.

Thank you for agreeing :)
I have just written a PR addressing this issue. Please take a look when you have a moment.
