### ISSUE TITLE
Flash attention monkey patch should not depend on xformers swiglu

### ISSUE THREAD

**Issue by ehartford** [axolotl-ai-cloud/axolotl#1406]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/OpenAccess-AI-Collective/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

xformers doesn't work on AMD.
flash attention does.
using flash attention should not have a dependency on xformers SWIGlu

### Current behaviour

from xformers.ops import SwiGLU

### Steps to reproduce

1) don't install xformers
2) use flash attention
3) fail

### Which Operating Systems are you using?

- [X] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.12

### axolotl branch-commit

main

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by ehartford** [comment]
here is a hack i did to get around it

```
--- a/src/axolotl/monkeypatch/llama_attn_hijack_flash.py
+++ b/src/axolotl/monkeypatch/llama_attn_hijack_flash.py
@@ -22,7 +22,9 @@ from transformers.models.llama.modeling_llama import (
     apply_rotary_pos_emb,
     repeat_kv,
 )
-from xformers.ops import SwiGLU
+class SwiGLU:
+    def __init__():
+        print("hi")

 from axolotl.monkeypatch.utils import get_cu_seqlens_from_pos_ids, set_module_name

@@ -45,15 +47,7 @@ LOG = logging.getLogger("axolotl")


 def is_xformers_swiglu_available() -> bool:
-    from xformers.ops.common import get_xformers_operator
-
-    try:
-        get_xformers_operator("swiglu_packedw")()
-        return True
-    except RuntimeError as exc:
-        if "No such operator xformers::swiglu_packedw " in str(exc):
-            return False
-        return True
+    return False

```

**Comment by casper-hansen** [comment]
I would like to suggest that we lazy import xformers in this case. So then the import would only be triggered if it's used.

**Comment by bursteratom** [comment]
Hi I just tested flash attention with xformers uninstalled and did not encounter the error. Seem it has already been fixed we just forgot to close the issue. Closing it now.
