### ISSUE TITLE
ERROR: No matching distribution found for bitsandbytes==0.43.0 for macOS 

### ISSUE THREAD

**Issue by chrisammon3000** [axolotl-ai-cloud/axolotl#1436]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/OpenAccess-AI-Collective/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

The command `pip3 install -e '.[flash-attn,deepspeed]'` should succeed and dependencies should be installed.

### Current behaviour

When running `pip3 install -e '.[flash-attn,deepspeed]'` this error output appears:
```sh
Obtaining file:///Users/ammon/Projects/chrisammon3000/training/axolotl/axolotl
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Installing backend dependencies ... done
  Preparing editable metadata (pyproject.toml) ... done
Collecting transformers@ git+https://github.com/huggingface/transformers.git@73a73b415e36f41481369f6129cb4b62bb127a78 (from axolotl==0.4.0)
  Cloning https://github.com/huggingface/transformers.git (to revision 73a73b415e36f41481369f6129cb4b62bb127a78) to /private/var/folders/8s/9sb2nsn913q7b4zz75fd_qf00000gn/T/pip-install-szra5usv/transformers_603c52ccdc0e42f49c9b70270f56871a
  Running command git clone --filter=blob:none --quiet https://github.com/huggingface/transformers.git /private/var/folders/8s/9sb2nsn913q7b4zz75fd_qf00000gn/T/pip-install-szra5usv/transformers_603c52ccdc0e42f49c9b70270f56871a
  Running command git rev-parse -q --verify 'sha^73a73b415e36f41481369f6129cb4b62bb127a78'
  Running command git fetch -q https://github.com/huggingface/transformers.git 73a73b415e36f41481369f6129cb4b62bb127a78
  Running command git checkout -q 73a73b415e36f41481369f6129cb4b62bb127a78
  Resolved https://github.com/huggingface/transformers.git to commit 73a73b415e36f41481369f6129cb4b62bb127a78
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting trl@ git+https://github.com/huggingface/trl.git@304e208f778a5442c30cdda500348226cdc97d90 (from axolotl==0.4.0)
  Cloning https://github.com/huggingface/trl.git (to revision 304e208f778a5442c30cdda500348226cdc97d90) to /private/var/folders/8s/9sb2nsn913q7b4zz75fd_qf00000gn/T/pip-install-szra5usv/trl_1288a1a5e9df448b8b67c6cc7d21a8ba
  Running command git clone --filter=blob:none --quiet https://github.com/huggingface/trl.git /private/var/folders/8s/9sb2nsn913q7b4zz75fd_qf00000gn/T/pip-install-szra5usv/trl_1288a1a5e9df448b8b67c6cc7d21a8ba
  Running command git rev-parse -q --verify 'sha^304e208f778a5442c30cdda500348226cdc97d90'
  Running command git fetch -q https://github.com/huggingface/trl.git 304e208f778a5442c30cdda500348226cdc97d90
  Running command git checkout -q 304e208f778a5442c30cdda500348226cdc97d90
  Resolved https://github.com/huggingface/trl.git to commit 304e208f778a5442c30cdda500348226cdc97d90
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting packaging==23.2 (from axolotl==0.4.0)
  Using cached packaging-23.2-py3-none-any.whl.metadata (3.2 kB)
Collecting peft==0.9.0 (from axolotl==0.4.0)
  Using cached peft-0.9.0-py3-none-any.whl.metadata (13 kB)
Collecting tokenizers==0.15.0 (from axolotl==0.4.0)
  Downloading tokenizers-0.15.0-cp311-cp311-macosx_11_0_arm64.whl.metadata (6.7 kB)
INFO: pip is looking at multiple versions of axolotl to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement bitsandbytes==0.43.0 (from axolotl) (from versions: 0.31.8, 0.32.0, 0.32.1, 0.32.2, 0.32.3, 0.33.0, 0.33.1, 0.34.0, 0.35.0, 0.35.1, 0.35.2, 0.35.3, 0.35.4, 0.36.0, 0.36.0.post1, 0.36.0.post2, 0.37.0, 0.37.1, 0.37.2, 0.38.0, 0.38.0.post1, 0.38.0.post2, 0.38.1, 0.39.0, 0.39.1, 0.40.0, 0.40.0.post1, 0.40.0.post2, 0.40.0.post3, 0.40.0.post4, 0.40.1, 0.40.1.post1, 0.40.2, 0.41.0, 0.41.1, 0.41.2, 0.41.2.post1, 0.41.2.post2, 0.41.3, 0.41.3.post1, 0.41.3.post2, 0.42.0)
ERROR: No matching distribution found for bitsandbytes==0.43.0
```

### Steps to reproduce

1. Run `python3 -m venv .venv`
2. Run `source .venv/bin/activate`
3. Run `pip3 install -e '.[flash-attn,deepspeed]'`

### Config yaml

```yaml
No config yaml used
```

### Possible solution

In requirements.txt, change `bitsandbytes==0.43.0` to a compatible version, or provide an alternative way to install the most recent version (from source for example).

### Which Operating Systems are you using?

- [ ] Linux
- [X] macOS
- [ ] Windows

### Python Version

3.11, 3.12

### axolotl branch-commit

main/34ba634

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by chrisammon3000** [comment]
It looks like this doesn't work on my machine which is a MacBook Air M2.

**Comment by isaac-einhorn** [comment]
Same issue here!

T-T

**Comment by NanoCode012** [comment]
Hey, if you're on macos, I think the way to pip install is different as shown on readme.

**Comment by pacozaa** [comment]
@NanoCode012  Do you mean `pip install -e '.'`? I still got 
```
ERROR: Could not find a version that satisfies the requirement bitsandbytes==0.43.0 (from axolotl) (from versions: 0.31.8, 0.32.0, 0.32.1, 0.32.2, 0.32.3, 0.33.0, 0.33.1, 0.34.0, 0.35.0, 0.35.1, 0.35.2, 0.35.3, 0.35.4, 0.36.0, 0.36.0.post1, 0.36.0.post2, 0.37.0, 0.37.1, 0.37.2, 0.38.0, 0.38.0.post1, 0.38.0.post2, 0.38.1, 0.39.0, 0.39.1, 0.40.0, 0.40.0.post1, 0.40.0.post2, 0.40.0.post3, 0.40.0.post4, 0.40.1, 0.40.1.post1, 0.40.2, 0.41.0, 0.41.1, 0.41.2, 0.41.2.post1, 0.41.2.post2, 0.41.3, 0.41.3.post1, 0.41.3.post2, 0.42.0)
ERROR: No matching distribution found for bitsandbytes==0.43.0
```

**Comment by someshfengde** [comment]
Facing the same error on mac m2

**Comment by uson1x** [comment]
Apparently, `bitsandbytes==0.43.0` does not support Mac M1. Previous releases were incorrectly marked as supporting M series.

The maintainers say they are committed to bring in the support, but timeframe is unclear.

https://github.com/TimDettmers/bitsandbytes/issues/252

**Comment by pacozaa** [comment]
@uson1x  thanks I also see that MacOS is only partially support

**Comment by gregorydickson** [comment]
having same issue on Intel iMac 2017

**Comment by pacozaa** [comment]
Maybe we can try docker version?

**Comment by cristi-zz** [comment]
I had some pesky issues with deepspeed and flash attention. On Ubuntu, with an env where I had only pytorch+huggingface+accelerate.

What I did is re-create the env with cuda, cudatoolkit and cuda version 11.8. Ok, don't know if downgrading to 11.8 "saved" the day, or that I installed both cuda and cudatoolkit. Anyway, here is my mamba command:

```
mamba create --copy -n llm python=3.11 pytorch=2.3.0 torchvision torchaudio pytorch-cuda=11.8 cuda=11.8 cudatoolkit=11.8  pytest pandas matplotlib tensorboard jupyterlab -c pytorch -c nvidia
```

Now, ``pip3 install -e '.[flash-attn,deepspeed]'`` works w/o errors. It takes few minutes though . . .

Apparently Huggingface comes as dependency. Nice!

**Comment by vramirez** [comment]
downgrading to `0.42.0` makes the installation work, but this version lacks m1 support =S

**Comment by happylolonly** [comment]
Facing same issue, will try to use `0.42.0`

**Comment by daproject85** [comment]
any resolution here?

**Comment by NanoCode012** [comment]
Just an update here. 

For those trying to install Axolotl on Mac, we've updated it to skip bnb/triton/packages that don't work on Mac, so running `pip install axolotl` should work.

https://github.com/axolotl-ai-cloud/axolotl/blob/a27b909c5c1c2c561a8d503024b89afcce15226f/requirements.txt#L3-L10

Edit: For those trying to install bitsandbytes on Mac, the current bitsandbytes repo only has Mac support `Under consideration`, so it will not work as expected. The prior wheels do not work. https://github.com/bitsandbytes-foundation/bitsandbytes
