### ISSUE TITLE
Support for finetuning Jamba model (from AI21)

### ISSUE THREAD

**Issue by creatorrr** [axolotl-ai-cloud/axolotl#1449]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/OpenAccess-AI-Collective/axolotl/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/OpenAccess-AI-Collective/axolotl/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

Support for finetuning Jamba

https://huggingface.co/ai21labs/Jamba-v0.1
https://www.ai21.com/blog/announcing-jamba

### ✔️ Solution

Jamba is a new model and interesting hybrid architecture MoE Mamba model that look very promising.

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by PhilipMay** [comment]
This is a Jamba finetuning script. Maybe it helps:
https://github.com/Pleias/Various-Finetuning/blob/main/finetuning_jamba.py

**Comment by maziyarpanahi** [comment]
> This is a Jamba finetuning script. Maybe it helps: https://github.com/Pleias/Various-Finetuning/blob/main/finetuning_jamba.py

I have tried this (you shared via Colab notebook on X). It worked on my local setup with 4 A100 80G. Pretty slow without accelerate and other optimizations, would love to see a Axolotl example for QLoRA, LoRA, and 16bit :)

**Comment by winglian** [comment]
@maziyarpanahi @creatorrr here you go. https://github.com/OpenAccess-AI-Collective/axolotl/tree/main/examples/jamba
