### ISSUE TITLE
[Feature] Allow dataset slicing/max_samples

### ISSUE THREAD

**Issue by ccdv-ai** [axolotl-ai-cloud/axolotl#1499]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/OpenAccess-AI-Collective/axolotl/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/OpenAccess-AI-Collective/axolotl/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

Add the option to select a subset of a dataset through slicing/max_samples
(didn't find a simple way to do it with single/multiple datasets)

### ✔️ Solution

See Huggingface [datasets documention](https://huggingface.co/docs/datasets/loading#slice-splits)

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by SicariusSicariiStuff** [comment]
u can cut it with a simple python script. i got plenty of such mini tools @ my github. this is easily done with chatgpt if u feel lazy. imo there are already tons of moving parts here as it is.

**Comment by NanoCode012** [comment]
Hey, it is already possible to do this. See `shards:` for individual dataset level and `dataset_shard_num: ` & `dataset_shard_idx` for whole dataset scope. https://openaccess-ai-collective.github.io/axolotl/docs/config.html
