### ISSUE TITLE
Peft is not installed via `pip install -e .` causing arbitrary peft issues on user end

### ISSUE THREAD

**Issue by utensil** [axolotl-ai-cloud/axolotl#151]
It takes me quite some time to figure this out.

Users of QLoRA with axolotl are reporting [some issues](https://github.com/OpenAccess-AI-Collective/axolotl/pull/132#issuecomment-1573964588) related to peft but gone in peft git repo HEAD. It's hard to reproduce, even with bisecting peft, until I noticed that axolotl fails to train in a clean Colab environment due to failing to import peft.

I tried and confirmed that axolotl doesn't install peft despite it's specified in `requirements.txt` . Eventually this leads to the following lines in `setup.py`:

```
    # don't include peft yet until we check the int4
    # need to manually install peft for now...
    reqs = [r.strip() for r in requirements_file.readlines() if "peft" not in r]
```
 
So users would be using arbitrary peft version already installed by the user before, which might be before the QLoRA PR to peft or have any other hidden issues.

Could we re-evaluate this int4 situation and fix this somehow or raise a warning during install ?

**Comment by winglian** [comment]
similarly related to https://github.com/OpenAccess-AI-Collective/axolotl/issues/152

**Comment by winglian** [comment]
Maybe we could do some feature validation or version checking in our validation.py based on what is being asked to train, and what they might need.
