### ISSUE TITLE
An Arbitrary Number of Checkpoints are Saved

### ISSUE THREAD

**Issue by Peter-Devine** [axolotl-ai-cloud/axolotl#1520]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/OpenAccess-AI-Collective/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

When I run a training run and I do not specify the number of checkpoints to save in `save_total_limit`, I expected the Axolotl code to save all checkpoints.

### Current behaviour

However, according to this code:

https://github.com/OpenAccess-AI-Collective/axolotl/blob/132eb740f036eff0fa8b239ddaf0b7a359ed1732/src/axolotl/core/trainer_builder.py#L1168C22-L1168C38

the number of checkpoints defaults to 4. This seems arbitrary to me.

### Steps to reproduce

Run the training code without setting `save_total_limit` explicitly.

### Possible solution

 This (in my opinion) is not well documented, so I'd like either some more documentation, or have the default to save all checkpoints.

### Which Operating Systems are you using?

- [X] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.10

### axolotl branch-commit

main

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by NanoCode012** [comment]
Hm, this is a good point. Maybe we should default to None instead like in HF: https://huggingface.co/docs/transformers/v4.40.0/en/main_classes/trainer#transformers.TrainingArguments.save_total_limit

**Comment by winglian** [comment]
Unfortunately we set it to 4 because it's a balance of keeping enough checkpoints and users running out of disk space unexpectedly. If we leave the default as None, the disk ends up filling up for most users and crashing the training.

**Comment by CoaLee** [comment]
It's good to set it 4 for balance, but it should be well documented as @Peter-Devine suggested. Otherwise, users would find their early checkpoints gone unexpectedly, like I just did. :/

Currently in the [Config Reference](https://docs.axolotl.ai/docs/config-reference.html),
```yaml
# Checkpoints saved at a time
save_total_limit: int | None
```

and in [axolotl/utils/schemas/config.py#L827-L829](https://github.com/axolotl-ai-cloud/axolotl/blob/87565ecc05f1b8fd1f8b907dd750d3a5d09adf9a/src/axolotl/utils/schemas/config.py#L827-L829),
```python
    save_total_limit: int | None = Field(
        default=None, json_schema_extra={"description": "Checkpoints saved at a time"}
    )
```

@winglian If you agree on it, I may submit a quick PR setting the default as 4 for this.

**Comment by NanoCode012** [comment]
@CoaLee , I think that will indeed be clearer. Currently, we set fallback in trainer which isn't good for validation. You can create the PR and tag me. I'm not sure whether we have any specific tests against this.
