### ISSUE TITLE
2x RTX 3090 vs 1x RTX 4090 for finetuning LLaMAs?

### ISSUE THREAD

**Issue by gotzmann** [axolotl-ai-cloud/axolotl#154]
I'm going to setup a rig and test axolotl for fine-tuning some experimental models. 

What might work better from your experience: 

- 2x Nvidia 3090 cards (total 48Gb) or 1x Nvidia 4090 (24Gb)? 
- Which model size one might train with those setups?
- Are there a use cases for hardware FP8 / INT8 support available with 4090 Ada architecture?

**Comment by winglian** [comment]
I'd go for more VRAM. more opportunity for larger models.
llama 7B should be good. 13B might fit with some optimizations.
there isn't a lot of good support yet for int8 in the underlying libraries to train with int8
