### ISSUE TITLE
I would like to train a model using the Deepmind/code_contest dataset

### ISSUE THREAD

**Issue by ghost** [axolotl-ai-cloud/axolotl#156]
https://huggingface.co/datasets/deepmind/code_contests

How can I achieve this?

**Comment by NanoCode012** [comment]
You can create your own custom prompters via https://github.com/OpenAccess-AI-Collective/axolotl#dataset

(Expand it and see how to custom prompt at the bottom)

**Comment by ghost** [comment]
Can someone point me to a tutorial or a some guide that will help me train any model using axolotl on a Mac M1?
I think a huge number of people are running on a m1 but I can't seem to get this working.

when I run:
```accelerate launch scripts/finetune.py examples/falcon/config-7b.yml```

I get:
```
Setting ds_accelerator to cuda (auto detect)
The following values were not passed to `accelerate launch` and had defaults used instead:
	`--num_cpu_threads_per_process` was set to `10` to improve out-of-box performance when training on CPUs
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /opt/homebrew/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cpu.so
/opt/homebrew/lib/python3.11/site-packages/bitsandbytes/cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
'NoneType' object has no attribute 'cadam32bit_grad_fp32'
CUDA SETUP: Loading binary /opt/homebrew/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cpu.so...
dlopen(/opt/homebrew/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cpu.so, 0x0006): tried: '/opt/homebrew/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cpu.so' (not a mach-o file)
Setting ds_accelerator to cuda (auto detect)
WARNING:root:batch_size is not recommended. Please use gradient_accumulation_steps instead.
To calculate the equivalent gradient_accumulation_steps, divide batch_size / micro_batch_size / number of gpus.
WARNING:root:`trust_remote_code` is set to true. Please make sure that you reviewed the remote code/model.
INFO:root:loading tokenizer... tiiuae/falcon-7b
Using bos_token, but it is not set yet.
Using pad_token, but it is not set yet.
Using unk_token, but it is not set yet.
INFO:root:Loading prepared dataset from disk at last_run_prepared/75b0aac2c08cbd9c1a9d263e929261aa...
INFO:root:Prepared dataset loaded from disk...
INFO:root:loading model and peft_config...
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:05<00:00,  2.58s/it]
Traceback (most recent call last):
  File "/Users/mario/Downloads/axolotl/scripts/finetune.py", line 295, in <module>
    fire.Fire(train)
  File "/opt/homebrew/lib/python3.11/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mario/Downloads/axolotl/scripts/finetune.py", line 242, in train
    trainer = setup_trainer(cfg, train_dataset, eval_dataset, model, tokenizer)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mario/Downloads/axolotl/src/axolotl/utils/trainer.py", line 112, in setup_trainer
    training_args = transformers.TrainingArguments(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 111, in __init__
  File "/opt/homebrew/lib/python3.11/site-packages/transformers/training_args.py", line 1344, in __post_init__
    raise ValueError(
ValueError: FP16 Mixed precision training with AMP or APEX (`--fp16`) and FP16 half precision evaluation (`--fp16_full_eval`) can only be used on CUDA devices.
Traceback (most recent call last):
  File "/opt/homebrew/bin/accelerate", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/opt/homebrew/lib/python3.11/site-packages/accelerate/commands/launch.py", line 918, in launch_command
    simple_launcher(args)
  File "/opt/homebrew/lib/python3.11/site-packages/accelerate/commands/launch.py", line 580, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/opt/homebrew/opt/python@3.11/bin/python3.11', 'scripts/finetune.py', 'examples/falcon/config-7b.yml']' returned non-zero exit status 1.
```

**Comment by ehartford** [comment]
> Can someone point me to a tutorial or a some guide that will help me train any model using axolotl on a Mac M1?
> I think a huge number of people are running on a m1 but I can't seem to get this working.
> 
> when I run:
> ```accelerate launch scripts/finetune.py examples/falcon/config-7b.yml```
> 
> I get:
> ```
> Setting ds_accelerator to cuda (auto detect)
> The following values were not passed to `accelerate launch` and had defaults used instead:
> 	`--num_cpu_threads_per_process` was set to `10` to improve out-of-box performance when training on CPUs
> To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
> 
> ===================================BUG REPORT===================================
> Welcome to bitsandbytes. For bug reports, please run
> 
> python -m bitsandbytes
> 
>  and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
> ================================================================================
> bin /opt/homebrew/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cpu.so
> /opt/homebrew/lib/python3.11/site-packages/bitsandbytes/cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
>   warn("The installed version of bitsandbytes was compiled without GPU support. "
> 'NoneType' object has no attribute 'cadam32bit_grad_fp32'
> CUDA SETUP: Loading binary /opt/homebrew/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cpu.so...
> dlopen(/opt/homebrew/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cpu.so, 0x0006): tried: '/opt/homebrew/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cpu.so' (not a mach-o file)
> Setting ds_accelerator to cuda (auto detect)
> WARNING:root:batch_size is not recommended. Please use gradient_accumulation_steps instead.
> To calculate the equivalent gradient_accumulation_steps, divide batch_size / micro_batch_size / number of gpus.
> WARNING:root:`trust_remote_code` is set to true. Please make sure that you reviewed the remote code/model.
> INFO:root:loading tokenizer... tiiuae/falcon-7b
> Using bos_token, but it is not set yet.
> Using pad_token, but it is not set yet.
> Using unk_token, but it is not set yet.
> INFO:root:Loading prepared dataset from disk at last_run_prepared/75b0aac2c08cbd9c1a9d263e929261aa...
> INFO:root:Prepared dataset loaded from disk...
> INFO:root:loading model and peft_config...
> Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:05<00:00,  2.58s/it]
> Traceback (most recent call last):
>   File "/Users/mario/Downloads/axolotl/scripts/finetune.py", line 295, in <module>
>     fire.Fire(train)
>   File "/opt/homebrew/lib/python3.11/site-packages/fire/core.py", line 141, in Fire
>     component_trace = _Fire(component, args, parsed_flag_args, context, name)
>                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/homebrew/lib/python3.11/site-packages/fire/core.py", line 475, in _Fire
>     component, remaining_args = _CallAndUpdateTrace(
>                                 ^^^^^^^^^^^^^^^^^^^^
>   File "/opt/homebrew/lib/python3.11/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
>     component = fn(*varargs, **kwargs)
>                 ^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/mario/Downloads/axolotl/scripts/finetune.py", line 242, in train
>     trainer = setup_trainer(cfg, train_dataset, eval_dataset, model, tokenizer)
>               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/mario/Downloads/axolotl/src/axolotl/utils/trainer.py", line 112, in setup_trainer
>     training_args = transformers.TrainingArguments(
>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "<string>", line 111, in __init__
>   File "/opt/homebrew/lib/python3.11/site-packages/transformers/training_args.py", line 1344, in __post_init__
>     raise ValueError(
> ValueError: FP16 Mixed precision training with AMP or APEX (`--fp16`) and FP16 half precision evaluation (`--fp16_full_eval`) can only be used on CUDA devices.
> Traceback (most recent call last):
>   File "/opt/homebrew/bin/accelerate", line 8, in <module>
>     sys.exit(main())
>              ^^^^^^
>   File "/opt/homebrew/lib/python3.11/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
>     args.func(args)
>   File "/opt/homebrew/lib/python3.11/site-packages/accelerate/commands/launch.py", line 918, in launch_command
>     simple_launcher(args)
>   File "/opt/homebrew/lib/python3.11/site-packages/accelerate/commands/launch.py", line 580, in simple_launcher
>     raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
> subprocess.CalledProcessError: Command '['/opt/homebrew/opt/python@3.11/bin/python3.11', 'scripts/finetune.py', 'examples/falcon/config-7b.yml']' returned non-zero exit status 1.
> ```

You need a gpu

**Comment by NanoCode012** [comment]
@devchild  I do not think many are training on m1 Mac. They may be using remote servers, using GPUs as Eric has mentioned. I do see some macOS specific code in the codebase with `mps` backend, however, I don't know if it still works.

As per your error, you can turn off `fp16:` `bf16:`and `tf32:` if you have them on and try again.

Ps: You may consider to close this Issue and reopen a separate one for easy tracking if my previous message solves your initial problem.

**Comment by ehartford** [comment]
My understanding is that CPU needs 32-bit instead of 16
