### ISSUE TITLE
Docker Compose Installation Broken for commit dde02fcb94e16206ab9ec6d3754ddce8d6fcf0d8

### ISSUE THREAD

**Issue by SoniCoder** [axolotl-ai-cloud/axolotl#1590]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/OpenAccess-AI-Collective/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

docker-compose up -d should work

### Current behaviour

88.06 INFO: pip is looking at multiple versions of xformers to determine which version is compatible with other requirements. This could take a while.       
88.08 ERROR: Cannot install axolotl and axolotl[deepspeed,flash-attn,galore,mamba-ssm]==0.4.0 because these package versions have conflicting dependencies.  
88.08                                                                                                                                                        
88.08 The conflict is caused by:                                                                                                                             
88.08     axolotl[deepspeed,flash-attn,galore,mamba-ssm] 0.4.0 depends on torch==2.0.0+cu118                                                                 
88.08     accelerate 0.28.0 depends on torch>=1.10.0                                                                                                         
88.08     bitsandbytes 0.43.0 depends on torch                      

88.08     accelerate 0.28.0 depends on torch>=1.10.0                                                                                                 [36/434]
88.08     bitsandbytes 0.43.0 depends on torch                                                                                                               
88.08     deepspeed 0.13.1 depends on torch                                                                                                                  
88.08     flash-attn 2.5.5 depends on torch                                                                                                                  
88.08     mamba-ssm 1.2.0.post1 depends on torch                                                                                                             
88.08     optimum 1.16.2 depends on torch>=1.11                                                                                                              
88.08     peft 0.10.0 depends on torch>=1.13.0                                                                                                               
88.08     trl 0.8.5 depends on torch>=1.4.0                                                                                                                  
88.08     xformers 0.0.22 depends on torch==2.0.1                                                                                                            
88.08                                                                                                                                                        
88.08 To fix this you could try to:
88.08 1. loosen the range of package versions you've specified
88.08 2. remove package versions to allow pip attempt to solve the dependency conflict
88.08 
88.08 ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

### Steps to reproduce

docker-compose up -d on commit dde02fcb94e16206ab9ec6d3754ddce8d6fcf0d8

### Which Operating Systems are you using?

- [X] Linux
- [ ] macOS
- [ ] Windows

### Python Version

axolotl-base

### axolotl branch-commit

dde02fcb94e16206ab9ec6d3754ddce8d6fcf0d8

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by mbtx2** [comment]
I was able to get this to run by updating the Dockerfile in docker/Dockerfile.  The referenced base tag in the Dockerfile was around a year old.  I updated it to a more recent one.  Then updated the CUDA version ARG.

```
ARG BASE_TAG=main-base-py3.11-cu121-2.1.2
FROM winglian/axolotl-base:$BASE_TAG

ARG TORCH_CUDA_ARCH_LIST="7.0 7.5 8.0 8.6+PTX"
ARG AXOLOTL_EXTRAS=""
ARG AXOLOTL_ARGS=""
ARG CUDA="121"
ENV BNB_CUDA_VERSION=$CUDA
ARG PYTORCH_VERSION="2.1.2"
```

**Comment by SoniCoder** [comment]
Yes updating the tag fixes the issue. I'm using main-base-py3.10-cu118-2.1.1 now on commit cb78a36374252333f1b1534c79d5fee946aec73e

Thanks. Closing
