### ISSUE TITLE
[Bug] accelerate.utils.modeling:The model weights are not tied when pass device_map="auto"

### ISSUE THREAD

**Issue by NanoCode012** [axolotl-ai-cloud/axolotl#160]
```
WARNING:accelerate.utils.modeling:The model weights are not tied. Please use the `tie_weights` method before using the `infer_auto_device` function.
```

https://github.com/huggingface/accelerate/blob/f1e84decc9d1e4f63aa443f8124b4876c79fff81/src/accelerate/utils/modeling.py#L705-L708

branch from current latest https://github.com/OpenAccess-AI-Collective/axolotl/commit/6abfd87d4458f5d1b3f62cfee3f3612cf0cd1fe3

Issue from 

https://github.com/OpenAccess-AI-Collective/axolotl/blob/6abfd87d4458f5d1b3f62cfee3f3612cf0cd1fe3/src/axolotl/utils/models.py#L185-L194

However, I'm not sure how we can add it in since it's created from that function

**Comment by NanoCode012** [comment]
It can be noted that 

https://github.com/OpenAccess-AI-Collective/axolotl/blob/6abfd87d4458f5d1b3f62cfee3f3612cf0cd1fe3/src/axolotl/utils/models.py#L266

calls `.tie_weights`

https://huggingface.co/transformers/v3.0.2/_modules/transformers/modeling_utils.html#PreTrainedModel.resize_token_embeddings

**Comment by mhenrichsen** [comment]
Getting same issue after training a LoRA and trying to inference.

**Comment by codenlighten** [comment]
any fix on this?

> Getting same issue after training a LoRA and trying to inference.

**Comment by NanoCode012** [comment]
It’s actually a problem in transformers. However, this is safe to ignore I assume. You could just use pure huggingface to load from model and get this issue still.
