### ISSUE TITLE
[Fix] Deprecate selecting yaml from list

### ISSUE THREAD

**Issue by NanoCode012** [axolotl-ai-cloud/axolotl#165]
A user is getting this error when using this feature with MULTI-GPU.

https://discord.com/channels/1104757954588196865/1111279858136383509/1116379061875376138

Since the issue comes from passing and not passing the config during CLI, I suspect it's from this feature where only one GPU will be set and others will be waiting.

https://github.com/OpenAccess-AI-Collective/axolotl/blob/81911d112c773739a721032f92f14b53d5f5d852/scripts/finetune.py#L108-L131

**Comment by theobjectivedad** [comment]
Were you thinking about removing it entirely or output a warning message that it will be removed in the future and only works properly with a single GPU?

**Comment by NanoCode012** [comment]
Remove entirely. With the change to use `examples` folder, this even decreases the need of this function as it looks within the old `config` folder.

**Comment by winglian** [comment]
we can still support this w multi gpu now using the broadcast functionality
