### ISSUE TITLE
Add FSDP support to Qwen2-72B model

### ISSUE THREAD

**Issue by maziyarpanahi** [axolotl-ai-cloud/axolotl#1690]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/OpenAccess-AI-Collective/axolotl/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/OpenAccess-AI-Collective/axolotl/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

FSDP can efficiently shard large models into multiple GPUs. This was very successful with Llama-3-70B. However, Qwen2 doesn't have support for FSDP and even QLoRA fails to fit the model in 4 A100 with 80G each.

I have failed to fine-tune Qwen2-72B with QLoRA+DPO on 4 A100 devices.

### ✔️ Solution

Adding FSDP support to Qwen2 should help

### ❓ Alternatives

I have tried DeepSpeed all zero3 strategies (offload params, all, etc.), none of them actually worked in terms of allowing a simple QLoRA+DPO on 4 A100. In theory, each model should be around take around 36G-40G in 4bit. But it gets OOM. Might be failing to load the model correctly in bf16 and leaves some on 32bit.

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by winglian** [comment]
@maziyarpanahi what yaml are you using?

**Comment by maziyarpanahi** [comment]
@winglian I use this one, but changing it to DPO (very simple Intel Orca): https://github.com/OpenAccess-AI-Collective/axolotl/blob/main/examples/qwen/qlora.yml

```
bf16: auto
fp16: false
tf32: false
```

I tried to add DeepSpeed (all zero3 variations), but they all are failing with OOM. I see these right when the training starts, so I was wondering if there are some stuff left on float32 and couldn't cast back. 

```
[2024-06-07 12:43:28,508] [INFO] [axolotl.callbacks.on_train_begin:771] [PID:5276] [RANK:0] The Axolotl config has been saved to the WandB run under files.
  0%|
                                                                         | 0/6430 [00:00<?, ?it/s]The input hidden states seems to be silently casted in float32, this might be related to the fac
t you have upcasted embedding or layer norm layers in float32. We will cast back the input in torch.bfloat16.
The input hidden states seems to be silently casted in float32, this might be related to the fact you have upcasted embedding or layer norm layers in float32. We will cast back the input in torc
h.bfloat16.
The input hidden states seems to be silently casted in float32, this might be related to the fact you have upcasted embedding or layer norm layers in float32. We will cast back the input in torc
h.bfloat16.
The input hidden states seems to be silently casted in float32, this might be related to the fact you have upcasted embedding or layer norm layers in float32. We will cast back the input in torc
h.bfloat16.
```

**Comment by deter3** [comment]
for Qwen/Qwen2-72B , the qwen2-7b fsdp example is not working , out of memory all the time ,even with 7*80GB A100 . for Qwen/Qwen2-7B , the example is working .

**Comment by maziyarpanahi** [comment]
@deter3 I am using the exact same FSDP on 4 A100 GPUs with QLoRA, and it fits. (batch size is 1 though)

I cannot fit FFT of 7B in the same GPUs via FSDP! Are you using QLoRA or FFT?

**Comment by deter3** [comment]
> @deter3 I am using the exact same FSDP on 4 A100 GPUs with QLoRA, and it fits. (batch size is 1 though)
> 
> I cannot fit FFT of 7B in the same GPUs via FSDP! Are you using QLoRA or FFT?

I am using 4 A100 GPUs with QLoRA & FSDP ,or 7 A100 GPUs with QLoRA & FSDP for 72b model , none of them fits . my max length is 9100 . I used my own data (English + Chinese mixed data )  for fine tune , I will double check other dataset , if it is okay or not .

**Comment by deter3** [comment]
i figured out the problem : sequence_len . if sequence_len is 2100 , example qwen2-72b qlora fsdp example is working , out of memory when sequence_len changed to 9100 . do you have any good suggestion , since even i am using 7*a100 80gb is still out of memory .
