### ISSUE TITLE
Add a `chat_template` strategy for DPO datasets

### ISSUE THREAD

**Issue by fozziethebeat** [axolotl-ai-cloud/axolotl#1708]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/OpenAccess-AI-Collective/axolotl/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/OpenAccess-AI-Collective/axolotl/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

This is basically #1660 but for DPO datasets:
* Let users specify a convesations field
* Let users specify role and content fields for each message
* Let the tokenizer chat template turn the conversation messages into the input prompt
* Let the tokenizer chat template turn the `rejected` and `chosen` field content into the right completion prompt
Then boom, easy training on long conversation sequences.

### ✔️ Solution

Replicate the changes in #1660 with minor tweaks for DPO.

### ❓ Alternatives

This can all be done outside of axolotol with the user defined fields but it's a bit messy and risks getting things wrong with the tokenizer chat template.

### 📝 Additional Context

I can do the implementation

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by SicariusSicariiStuff** [comment]
Can we also have ORPO while we're at it? :)

**Comment by ehartford** [comment]
this will require an upstream change to trl
or, it will require automatically splitting the dataset from this:

```
[{prompt1, response1},{prompt2, response2}, {prompt3, response3}]
```

into this

```
{prompt1, accepted1, rejected1}
{prompt1+accepted1+prompt2, accepted2, rejected2}
{prompt1+accepted1+prompt2+accepted2+prompt3, accepted3, rejected3}
{prompt1+accepted1+prompt2+accepted2+prompt3+accepted3+prompt4, accepted4, rejected4}
```

**Comment by fozziethebeat** [comment]
Oof yeah I think ORPO is a separate feature request.  From what I can tell data format support is quite unique for each RL method.

**Comment by fozziethebeat** [comment]
Also, I have a have a [fork](https://github.com/fozziethebeat/axolotl) of this working I just haven't gotten around to unit testing it.  I have manually inspected the tokenization and am satisfied.
