### ISSUE TITLE
Edge case for local dataset loading if its a folder

### ISSUE THREAD

**Issue by ccdv-ai** [axolotl-ai-cloud/axolotl#1830]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/axolotl-ai-cloud/axolotl/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/axolotl-ai-cloud/axolotl/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

Focusing on a case where the local dataset is a **folder** and no `data_files` passed.

`load_from_disk(config_dataset.path)` can fail if the dataset is a **folder** and isn't saved using `datasets.save_to_disk(...)`. 
For instance, it can fail with a cloned dataset.

See [sft.py](https://github.com/axolotl-ai-cloud/axolotl/blob/main/src/axolotl/utils/data/sft.py#L311):
```python
if local_path.exists():
    if local_path.is_dir():
        if config_dataset.data_files:
            ds_type = get_ds_type(config_dataset)
            ds = load_dataset(
                ds_type,
                name=config_dataset.name,
                data_files=config_dataset.data_files,
                streaming=False,
                split=None,
            )
        else:
            ds = load_from_disk(config_dataset.path)
```
In a case where the local dataset is a **folder** and no `data_files` is passed, we fall in 
`ds = load_from_disk(config_dataset.path)`

### ✔️ Solution

Naive solution:

Replace this [line](https://github.com/axolotl-ai-cloud/axolotl/blob/main/src/axolotl/utils/data/sft.py#L311): 
```python 
ds = load_from_disk(config_dataset.path)
```
by:
```python
try:
    ds = load_from_disk(config_dataset.path)
except:
    ds = load_dataset(
        config_dataset.path,
        name=config_dataset.name,
        streaming=False,
        split=None,
    )
```

Note that `load_dataset(...)` can accept `data_files=None`.

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by ccdv-ai** [comment]
@NanoCode012
Still getting this error trying to load a local hf dataset:
> https://github.com/axolotl-ai-cloud/axolotl/blob/8c3a727f9d60ffd3af385f90bcc3fa3a56398fe1/src/axolotl/utils/data/sft.py#L313-L341
```python
FileNotFoundError: Directory /home/user/data/instruct_dataset is neither a `Dataset` directory nor a `DatasetDict` directory.
```
This line is the problem if the dataset has not been saved using `datasets.save_to_disk(...)` which happens in most cases: 
```python
ds = load_from_disk(config_dataset.path)
```

Using `load_dataset(...)` is more reliable:
```python
ds = load_dataset(...)
```

**Comment by NanoCode012** [comment]
@ccdv-ai , thanks for lifting this issue. I wasn't aware that was how to load manually cloned HF repo. Was it not using the `data_dir` path? We seem to not have that config as well. We may need to open it for your case. Is that a better fix?

https://huggingface.co/docs/datasets/loading#manual-download

**Comment by ccdv-ai** [comment]
@NanoCode012 
I'm not sure to understand your question.

What I know is that there are 2 main cases where this problem can happen:
* the dataset is cloned from HF (git clone)
* the dataset has been created manually in a local folder (i.e mkdir, move files, create the config)

`load_dataset(...)` also has the `trust_remote_code`arg which can be useful (see #1829 for instance).

**Comment by NanoCode012** [comment]
@ccdv-ai sorry for the confusion. I just did some testing on this. Your approach is right. I thought `load_dataset(..., data_dir="...")` was the way to go for loading locally downloaded datasets from reading that doc.

Could you please make a PR for this? The solution in the first post looks good. Could you change the `except` to handle only the `FileNotFoundError` to limit the catch? Secondly, could you add a test on this in `tests/test_datasets.py`?
