### ISSUE TITLE
MPT Lora?

### ISSUE THREAD

**Issue by platform-kit** [axolotl-ai-cloud/axolotl#188]
Hi, great project (and great pun in the description!)

Here's my question - what is the reason that MPT doesn't support LORA? Is that a limitation of the model or of this library, and if the latter, what is the blocker?

I am very interested in training MPT with LORA, and curious a) as to a timeline and b) as to whether it's within my skillset to help enable LORA for MPT.

**Comment by winglian** [comment]
Hi @platform-kit, currently, the mpt forward call doesn't currently handle an argument that the PEFT LoRA adapter passes to the layer. This would need to be resolved by mosaic.
