### ISSUE TITLE
Load existing LORA and continue training it

### ISSUE THREAD

**Issue by Nero10578** [axolotl-ai-cloud/axolotl#1887]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/axolotl-ai-cloud/axolotl/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/axolotl-ai-cloud/axolotl/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

As far as I understand specifying the LORA directory only means you're loading the LORA ontop of the base model and then training a new LORA on top of that?

### ✔️ Solution

Be able to load a pre-trained LORA and continue training it. Unless Axolotl already does this and I'm misunderstanding the docs?

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by NanoCode012** [comment]
Hey, I think if you do load, it may work as intended and continue training. I believe I may have done this quite a while back.

Please let us know if my understanding is correct!

**Comment by Nero10578** [comment]
> Hey, I think if you do load, it may work as intended and continue training. I believe I may have done this quite a while back.
> 
> Please let us know if my understanding is correct!

Do you mean it should work by just specifying the lora directory?

**Comment by NanoCode012** [comment]
Yes, it should continue training from that adapter. Please do let me know if there's some issue.

**Comment by winglian** [comment]
@Nero10578 correct, it will load the existing lora and continue training that. https://github.com/axolotl-ai-cloud/axolotl/blob/main/src/axolotl/utils/models.py#L1328-L1341

**Comment by Nero10578** [comment]
> @Nero10578 correct, it will load the existing lora and continue training that. https://github.com/axolotl-ai-cloud/axolotl/blob/main/src/axolotl/utils/models.py#L1328-L1341

Ok cool thanks guys. Just to be clear it has to be a checkpoint that has all the training state files? Can't be just any LORA?

**Comment by NanoCode012** [comment]
@Nero10578 , it can be any lora
