### ISSUE TITLE
Gemma 2 chat template inserts eos_token after every chat turn

### ISSUE THREAD

**Issue by Nero10578** [axolotl-ai-cloud/axolotl#1921]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/axolotl-ai-cloud/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

EOS_token should only be at the end. Not in between turns.

### Current behaviour

EOS_token gets inserted between each turns after the end of turn token. I improvised by just setting eos_token: <end_of_turn> which is hopefully better than adding an eos_token there.

`me(682, 682) .(235265, 235265) <end_of_turn>(107, 107) 
(108, 108) <end_of_turn>(107, 107) <start_of_turn>(-100, 106) user(-100, 1645)`

### Steps to reproduce

Just run tokenization debug on gemma 2 models with sharegpt gemma chat template and this is what happens.

### Which Operating Systems are you using?

- [X] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.11

### axolotl branch-commit

latest main

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by NanoCode012** [comment]
Hey, we just merged an improvement for `chat_template`. If you're still interested, could you try migrate to using `type: chat_template` instead of sharegpt?
