### ISSUE TITLE
neither of the mistral chat templates work

### ISSUE THREAD

**Issue by guillermo-gabrielli-fer** [axolotl-ai-cloud/axolotl#1960]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/axolotl-ai-cloud/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

Either inst or the new mistral templates work as chat template

### Current behaviour

If I use chat_template. inst it will fail with ValueError: Template 'inst' not found.
```
  File "axolotl/src/axolotl/utils/chat_templates.py", line 40, in chat_templates
    raise ValueError(f"Template '{user_choice}' not found.")
```
If I use the new ones (e.g. mistral_v2v3) it will fail with :
```
pydantic_core._pydantic_core.ValidationError: 1 validation error for AxolotlConfigWCapabilities
chat_template
  Input should be 'alpaca', 'chatml', 'inst', 'gemma', 'cohere', 'llama3', 'llama3_2_vision', 'phi_3', 'phi_35', 'deepseek_v2' or 'jamba' [type=enum, input_value='mistral_v2v3', input_type=str]
   
```

https://github.com/axolotl-ai-cloud/axolotl/pull/1927 changed the list of prompt templates but did not update the validation, hence neither inst or mistral_v2v3 are valid.

### Steps to reproduce

Use either inst or mistral_v2v3 as chat_template

### Which Operating Systems are you using?

- [X] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.10

### axolotl branch-commit

main/2fbc6b0c644424feff91abe3d001fa1c6638e118

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by NanoCode012** [comment]
Closed as the PR linked should've fixed this.
