### ISSUE TITLE
Add resize_token_embeddings feature

### ISSUE THREAD

**Issue by ccdv-ai** [axolotl-ai-cloud/axolotl#1965]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/axolotl-ai-cloud/axolotl/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/axolotl-ai-cloud/axolotl/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

Add the option to [resize the token embeddings](https://huggingface.co/docs/transformers/v4.22.2/en/main_classes/model#transformers.PreTrainedModel.resize_token_embeddings):
`PreTrainedModel` has this [method](https://github.com/huggingface/transformers/blob/v4.22.2/src/transformers/modeling_utils.py#L878).

### ✔️ Solution

```python
from transformers import AutoModelForCausalLM

model = AutoModelForCausalLM.from_pretrained(model_id)
model.resize_token_embeddings(num_tokens)
```

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by NanoCode012** [comment]
May I ask what is the use case? We currently resize to the tokenizer's length (or multiple of 32 to it if enabled).

**Comment by ccdv-ai** [comment]
Can be usefull for a tokenizer/custom tokenizer and vocab_size mismatch.
For instance, there is a mismatch for all qwen 2.5 models where they padded the embedding layer for distributed training.

**Comment by NanoCode012** [comment]
@ccdv-ai , just to clarify, would you want a config that lets you specify the new tokenizer vocab size or just to resize?

Axolotl does the latter* under the hood when you add new tokens. https://github.com/axolotl-ai-cloud/axolotl/blob/8c3a727f9d60ffd3af385f90bcc3fa3a56398fe1/src/axolotl/utils/models.py#L1039-L1053

If you enable `resize_token_embeddings_to_32x: true`, it will resize to next multiple of 32.

**Comment by ccdv-ai** [comment]
@NanoCode012 Only the option to choose and resize the token_embeddings to an arbitrary value.
For example, Qwen 2.5 7B tokenizer has 151665 tokens but the embedding layer has 152064.
`resize_token_embeddings_to: 151665` should be possible.


```python
if self.cfg.resize_token_embeddings_to < len(self.tokenizer):
    #Warning or stop
self.model.resize_token_embeddings(self.cfg.resize_token_embeddings_to, **resize_kwargs)
```

**Comment by NanoCode012** [comment]
@ccdv-ai  thanks for clarifying. To add on to your point, we already do resize to tokenizer.

```py
# above code but summarized

embeddings_len = len(self.tokenizer) 

if ( 
     self.model.get_input_embeddings().num_embeddings < embeddings_len 
 ): 
     self.model.resize_token_embeddings(embeddings_len)
```

For resizing to another value (`!=len(self.tokenizer)` ) , I'm not sure I understand the use case as the tokenizer would then mismatch the embedding length and cause an error during training.
