### ISSUE TITLE
initialize your accelerator via `accelerator = Accelerator()` before using any functionality from the `accelerate` library

### ISSUE THREAD

**Issue by lucyknada** [axolotl-ai-cloud/axolotl#1967]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/axolotl-ai-cloud/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

training on qwen2.5-14b based models should work just like it does on upstream vanilla qwen2.5-14b

### Current behaviour

```
[rank1]: Traceback (most recent call last):
[rank1]:   File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
[rank1]:     return _run_code(code, main_globals, None,
[rank1]:   File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
[rank1]:     exec(code, run_globals)
[rank1]:   File "/workspace/axolotl/src/axolotl/cli/train.py", line 77, in <module>
[rank1]:     fire.Fire(do_cli)
[rank1]:   File "/workspace/axolotl/venv/lib/python3.10/site-packages/fire/core.py", line 135, in Fire
[rank1]:     component_trace = _Fire(component, args, parsed_flag_args, context, name)
[rank1]:   File "/workspace/axolotl/venv/lib/python3.10/site-packages/fire/core.py", line 468, in _Fire
[rank1]:     component, remaining_args = _CallAndUpdateTrace(
[rank1]:   File "/workspace/axolotl/venv/lib/python3.10/site-packages/fire/core.py", line 684, in _CallAndUpdateTrace
[rank1]:     component = fn(*varargs, **kwargs)
[rank1]:   File "/workspace/axolotl/src/axolotl/cli/train.py", line 38, in do_cli
[rank1]:     return do_train(parsed_cfg, parsed_cli_args)
[rank1]:   File "/workspace/axolotl/src/axolotl/cli/train.py", line 66, in do_train
[rank1]:     model, tokenizer = train(cfg=cfg, cli_args=cli_args, dataset_meta=dataset_meta)
[rank1]:   File "/workspace/axolotl/src/axolotl/train.py", line 101, in train
[rank1]:     Accelerator()
[rank1]:   File "/workspace/axolotl/venv/lib/python3.10/site-packages/accelerate/accelerator.py", line 292, in __init__
[rank1]:     deepspeed_plugins = AcceleratorState().deepspeed_plugins
[rank1]:   File "/workspace/axolotl/venv/lib/python3.10/site-packages/accelerate/state.py", line 887, in __init__
[rank1]:     raise ValueError(
[rank1]: ValueError: Please make sure to properly initialize your accelerator via `accelerator = Accelerator()` before using any functionality from the `accelerate` library.
```

### Steps to reproduce

1. clone latest axolotl (68b1369de9cc8b77931bc4489899216f40fdb93f)
2. try FFT training on: https://huggingface.co/arcee-ai/SuperNova-Medius (or any other qwen14b based model that was trained on top of it, but NOT the official release itself)
3. stacktrace above no matter what you do

I tried:
- regular transformers from requirements.txt
- latest git transformers
- latest deepspeed
- deepspeed version 0.14.4
- various versions of accelerate
- fresh venv

What makes this work:
- git clone d7eea2ff343e9f0653ce82fc1826b41efa9bc2f6
- pull latest transformers from git
- deepspeed zero 2

without latest transformers (with outdated axolotl), you get:

```
[rank7]: Exception: data did not match any variant of untagged enum ModelWrapper at line 757443 column 3
```

only thing that works without downgrading: 
- removing deepspeed entirely and doing DDP (not an option for most FFT)

### Which Operating Systems are you using?

- [X] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.11, 3.10, 3.12

### axolotl branch-commit

68b1369de9cc8b77931bc4489899216f40fdb93f

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by muellerzr** [comment]
Should be fixed via https://github.com/axolotl-ai-cloud/axolotl/pull/1969 :)

**Comment by winglian** [comment]
@lucyknada  yup, This has been fixed already per the referenced PR.

**Comment by lucyknada** [comment]
awesome thanks!
