### ISSUE TITLE
Add hardware requirements

### ISSUE THREAD

**Issue by OliverKunc** [axolotl-ai-cloud/axolotl#1992]
### What piece of documentation is affected?

README.md

### What part(s) of the article would you like to see updated?

Add hardware requirements.

FlashAttention imposes requirements on the GPU architecture. It is a bad user experience if after the lengthy setup of the software environment the fail turns to be a missed hardware requirement which could have been known in advance.

### Additional Information

https://pypi.org/project/flash-attn

> Support for Turing GPUs (T4, RTX 2080) is coming soon, please use FlashAttention 1.x for Turing GPUs for now.

If I downgrade to 1.x, I am in dependency hell.

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by NanoCode012** [comment]
Hey, would you like to open a small PR to address this in the docs?

We had to deprecate handling of FA1 due to it creating a lot of legacy code. We currently support FA2

**Comment by OliverKunc** [comment]
I could do that. But I am unsure if I am aware of all dependencies. Is there any other library or package that has requirements on hardware architecture?

**Comment by NanoCode012** [comment]
I do not believe so. I think it's mainly FA2 which requires Ampere or higher.

Edit: bf16 and tf32 has same requirements too ampere+
