### ISSUE TITLE
Issue load Llama tokenizer

### ISSUE THREAD

**Issue by NanoCode012** [axolotl-ai-cloud/axolotl#20]
Hello, I'm getting a weird issue loading tokenizer. I've checked that the line of code hasn't changed even on my latest pull. The only difference could be `transformer` source changed something.

https://github.com/winglian/axolotl/blob/7576d85c735e307fa1dbbcb8e0cba8b53bb1fa48/src/axolotl/utils/models.py#L138-L139

```
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00,  7.88it/s]
Repo id must use alphanumeric chars or '-', '_', '.', '--' and '..' are forbidden, '-' and '.' cannot start or end the name, max length is 96: 'LlamaForCausalLM(
  (model): LlamaModel(
    (embed_tokens): Embedding(32000, 4096, padding_idx=0)
    (layers): ModuleList(
      (0-31): 32 x LlamaDecoderLayer(
        (self_attn): LlamaAttention(
          (q_proj): Linear8bitLt(in_features=4096, out_features=4096, bias=False)
          (k_proj): Linear8bitLt(in_features=4096, out_features=4096, bias=False)
          (v_proj): Linear8bitLt(in_features=4096, out_features=4096, bias=False)
          (o_proj): Linear8bitLt(in_features=4096, out_features=4096, bias=False)
          (rotary_emb): LlamaRotaryEmbedding()
        )
        (mlp): LlamaMLP(
          (gate_proj): Linear8bitLt(in_features=4096, out_features=11008, bias=False)
          (down_proj): Linear8bitLt(in_features=11008, out_features=4096, bias=False)
          (up_proj): Linear8bitLt(in_features=4096, out_features=11008, bias=False)
          (act_fn): SiLUActivation()
        )
        (input_layernorm): LlamaRMSNorm()
        (post_attention_layernorm): LlamaRMSNorm()
      )
    )
    (norm): LlamaRMSNorm()
  )
  (lm_head): Linear(in_features=4096, out_features=32000, bias=False)
)'.
Traceback (most recent call last):
  File "/workspace/src/axolotl/utils/models.py", line 140, in load_model
    tokenizer = LlamaTokenizer.from_pretrained(model)
```

**Comment by NanoCode012** [comment]
I can just use `base_model_config`, but I'm curious why this method is failing.

**Comment by winglian** [comment]
are you pointing to a locally downloaded model? I've seen this issue when that's the case.

**Comment by NanoCode012** [comment]
> are you pointing to a locally downloaded model? I've seen this issue when that's the case.

No, I'm point to the HuggingFace repo, but I got it cached locally.

```bash
export HF_DATASETS_CACHE="/workspace/data/huggingface-cache/datasets"
export HUGGINGFACE_HUB_CACHE="/workspace/data/huggingface-cache/hub"
```

Thing is: it was working till I merged latest pulls. Although there were over 31 commits in just a few days, no code touched that line.

**Comment by winglian** [comment]
what are you using as your config for `base_model` and `base_model_config`?

**Comment by NanoCode012** [comment]
> what are you using as your config for `base_model` and `base_model_config`?

I pointed `base_model` to a HG repo and `base_model_config` is empty. 

In the past, this would work. However, for some reason, it does not work anymore despite that line not being changed. I have changed to point both to the same path which works now.
