### ISSUE TITLE
Are single datasets shuffled ?

### ISSUE THREAD

**Issue by ccdv-ai** [axolotl-ai-cloud/axolotl#2005]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/axolotl-ai-cloud/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

I don't see where single datasets are shuffled. I know there is a option to shuffle merged datasets but it isn't triggered for single datasets.

For 1 dataset with a single split, [this condition](https://github.com/axolotl-ai-cloud/axolotl/blob/main/src/axolotl/utils/data/sft.py#L456) is always false:
```python
if len(datasets) > 1: # false for a single dataset with a single split
    if cfg.shuffle_merged_datasets:
        LOG.debug("shuffle merged datasets")
        dataset = dataset.shuffle(seed=seed)
    else:
        LOG.debug("NOT shuffling merged datasets")
```

Solution: remove the condition or add the option to shuffle each dataset individually.

### Current behaviour

No shuffle ?

### Steps to reproduce

Load a dataset with a single split.

### Possible solution

Remove the condition or add the option to shuffle each dataset individually.

### Which Operating Systems are you using?

- [X] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.11

### axolotl branch-commit

main

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by NanoCode012** [comment]
Hm, I believe `len(datasets)` would output number of rows, so it would indeed shuffle.

The full code is below.

https://github.com/axolotl-ai-cloud/axolotl/blob/8c3a727f9d60ffd3af385f90bcc3fa3a56398fe1/src/axolotl/utils/data/sft.py#L450-L461

`datasets` is initially a List of `Dataset`. Given that we load only single dataset, it would then be `datasets: Dataset`. Then, we would get the length.

```bash
>>> d = load_dataset("mlabonne/FineTome-100k", split="train")
>>> len(d)
100000
```

**Comment by ccdv-ai** [comment]
If the split isn't mentionned and there is only a train split then we get `len(d) == 1`:
```python
ds = load_dataset(
            ds_type,
            name=config_dataset.name,
            data_files=config_dataset.path,
            streaming=False,
            split=None,
)
```

**Comment by NanoCode012** [comment]
That's a good point. I would prefer to remove the if condition but let me check further about this.

**Comment by NanoCode012** [comment]
I've got back from wing. He told me that: The reason behind this shuffling is for merging multiple datasets.

Moreover, since the samplers shuffle by default, we don't need to shuffle it here for single datasets.

Therefore, as of now, we don't have plans to change this.
