### ISSUE TITLE
Add Functionality for `chat_template_jinja` to Accept Paths to Template Files

### ISSUE THREAD

**Issue by ckgresla** [axolotl-ai-cloud/axolotl#2008]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/axolotl-ai-cloud/axolotl/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/axolotl-ai-cloud/axolotl/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

The new configuration value: `chat_template_jinja` accepts a chat template as a string, encoded in the yaml. The new feature would update this value to also accept paths to jinja template files on the filesystem a job is started with, circumventing the need to include a chat template in a config yaml.

### ✔️ Solution

When axolotl loads and validates the config file for a training job, we could check if the value of `chat_template_jinja` is a path on the local filesystem when we validate it inside of `check_chat_template_config`. If it is a valid filepath, axolotl could load in that jinja template as the value of the `chat_template_jinja` for the remainder of the training job.

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by NanoCode012** [comment]
This could be an interesting use case. From my perspective, it would make more sense to keep everything in `config.yaml` being source of truth, but I can see where separating in another file could keep things clean.

cc @chiragjn . What do you think?

**Comment by chiragjn** [comment]
I also prefer keeping the template inline, which makes it easy to share and reproduce the config for someone else. Just curious what is the usecase?

Considering config is yaml, formatting should be less of a trouble

```yaml
chat_template_jinja: |-
  ...
```

However, if there is a strong usecase, we can add an option like

```yaml
chat_template_jinja:
  file: ./relative/path/to/my/template.jinja
```

**Comment by ckgresla** [comment]
Thank you both for the perspectives -- the use case for this would be to apply templates from a separate repository inside of an axolotl training job. Using file paths to external templates would probably not be good for reproducibility, in light of that i'll close this issue!
