### ISSUE TITLE
Mismatch between training & inference for chat modesl in do_inference

### ISSUE THREAD

**Issue by gordicaleksa** [axolotl-ai-cloud/axolotl#2014]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/axolotl-ai-cloud/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

There is mismatch bewteen how chat models are trained and their inference - we should implement it the same way as in do_inference_gradio

### Current behaviour

Mismatch

### Steps to reproduce

Just run do_inference to see this

### Config yaml

```yaml
/
```

### Possible solution

copy from do_inference_gradio

### Which Operating Systems are you using?

- [X] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.10

### axolotl branch-commit

main/335027f155b34b569d2d7c106c8797569a8eaa56

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by NanoCode012** [comment]
@gordicaleksa , sorry it took a while. I made a PR which should solve it. Are you able to verify it? https://github.com/axolotl-ai-cloud/axolotl/pull/2019
