### ISSUE TITLE
Unsloth decorators are deprecated

### ISSUE THREAD

**Issue by rationalism** [axolotl-ai-cloud/axolotl#2015]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/axolotl-ai-cloud/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

When importing unsloth.py with a recent version of PyTorch, the code should load without warnings or deprecation messages.

### Current behaviour

Whenever `src/axolotl/utils/gradient_checkpointing/unsloth.py` is imported when a recent version of PyTorch is installed, this deprecation warning appears:

```
10.10.10.2: /home/alyssa/lm_fun/qlora-pipe/axolotl/src/axolotl/utils/gradient_checkpointing/unsloth.py:28: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
10.10.10.2:   @torch.cuda.amp.custom_fwd
10.10.10.2: /home/alyssa/lm_fun/qlora-pipe/axolotl/src/axolotl/utils/gradient_checkpointing/unsloth.py:39: FutureWarning: `torch.cuda.amp.custom_bwd(args...)` is deprecated. Please use `torch.amp.custom_bwd(args..., device_type='cuda')` instead.
10.10.10.2:   @torch.cuda.amp.custom_bwd
```

### Steps to reproduce

```
git clone https://github.com/axolotl-ai-cloud/axolotl.git
cd axolotl/
cd src/axolotl/utils/gradient_checkpointing/
python
import unsloth
```

(if a recent PyTorch is installed the deprecation message will appear)

### Config yaml

```yaml
N/A
```

### Possible solution

Unsloth has an upstream fix here:

https://github.com/unslothai/unsloth/blob/main/unsloth/kernels/utils.py

### Which Operating Systems are you using?

- [X] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.12

### axolotl branch-commit

main

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by bursteratom** [comment]
Hi thank you for bringing this to attention! I am wondering what pytorch version you are using?

**Comment by bursteratom** [comment]
Hi @rationalism , I added [PR#2042](https://github.com/axolotl-ai-cloud/axolotl/pull/2042) which should fix this. Please let me know if this works for you!
