### ISSUE TITLE
Training Progress bar (tqdm steps) missing when training with modal

### ISSUE THREAD

**Issue by femT-data** [axolotl-ai-cloud/axolotl#2062]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/axolotl-ai-cloud/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

I can see the bar when training with Jarvis labs or any other cloud platform but in modal it's not visible.  I am following this repository 

### Current behaviour

The progress bar which shows the number of steps remaining and time is missing. 
![image](https://github.com/user-attachments/assets/d072b880-9931-4c16-b85a-758ab6061a6d)

### Steps to reproduce

I am following the steps in this repository.  [llm-finetuning](https://github.com/modal-labs/llm-finetuning)

### Which Operating Systems are you using?

- [X] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.10

### axolotl branch-commit

main

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by NanoCode012** [comment]
Hey, I don't think we do any platform-specific hiding of tqdm. Since this may be a modal issue, would you try to see if you can open an Issue on the linked repo and see what they say?

**Comment by femT-data** [comment]
Hello, I posted the issue on modal slack and did not get a response, I was worried this might be an installation issue or anything from axolotl side, but good to know it isn't. I'll close this for the moment and reach out to them again. Thanks.
