### ISSUE TITLE
Axolotl vs Llama-Factory?

### ISSUE THREAD

**Issue by fzyzcjy** [axolotl-ai-cloud/axolotl#2125]
### What piece of documentation is affected?

Hi thanks for the library! It seems that https://github.com/hiyouga/LLaMA-Factory has similar features as this lib, so I would appreciate it if I could know comparison between the two libs.

### What part(s) of the article would you like to see updated?

(see above)

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by symlink** [comment]
hi @fzyzcjy 

- Axolotl has rigorous automated integration testing for correctness. 
- Things move fast and upstream changes can break things, and we have much more extensive testing than any other downstream HF Trainer, so we're more likely to catch problems

**Comment by fzyzcjy** [comment]
@symlink Thank you, and that looks pretty important to me (personally speaking)!

**Comment by fzyzcjy** [comment]
@symlink Btw, it would be great to mention this rigorous testing thing in README, since this is really an advantage! For example, another popular library, tianshou, also mentions explicitly about its rigorous testing (https://github.com/thu-ml/tianshou/#reproducible-high-quality-results).

**Comment by fblgit** [comment]
IMHO u are comparing oranges vs apples. A training framework that supports almost any architecture vs a static oriented  implementation.cn that barely anyone uses 😄
if u like the reproducibility part, thats nice. I like more the fact that this is standard across the industry and is always on the front at the time to implement new tech. but hey, submit a PR maybe it goes thru.

**Comment by fzyzcjy** [comment]
> this is standard across the industry and is always on the front at the time to implement new tech

That looks also great :)
