### ISSUE TITLE
Axolotl Crashes At The End Of Training If Base Model Is Local

### ISSUE THREAD

**Issue by FelixSchneiderZoom** [axolotl-ai-cloud/axolotl#2134]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/axolotl-ai-cloud/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

The module should exit normally at the end of training.

### Current behaviour

In https://github.com/axolotl-ai-cloud/axolotl/blob/5726141c4eaeb61433f4da76fee1f023d97573f1/src/axolotl/train.py#L265-L287
we check if the base model is on the hub. However, the `catch` block expects a `(AttributeError, UnicodeDecodeError, RepositoryNotFoundError)`, but Huggingface actually raises `HFValidationError` when `cfg.base_model` is a local absolute path, because the path starts with a `/`, which is an invalid repository format. This error is not caught, and axolotl crashes.

### Steps to reproduce

Train any model where `base_model` points to a local absolute path on your hard drive.

### Which Operating Systems are you using?

- [ ] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.11

### axolotl branch-commit

main/5726141

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by fluentmin** [comment]
Had the same error after training with local model. In my case, it was raised by the code line 268.

```python
hf_api.model_info(cfg.base_model)
```

**Comment by bursteratom** [comment]
@FelixSchneiderZoom Thank you for catching this error. I've started a PR that implements the fix:https://github.com/axolotl-ai-cloud/axolotl/pull/2140 

Pls let me know if it solves the issue.
