### ISSUE TITLE
Different logging frequency to mlflow and to tensorboard

### ISSUE THREAD

**Issue by fzyzcjy** [axolotl-ai-cloud/axolotl#2146]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/axolotl-ai-cloud/axolotl/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/axolotl-ai-cloud/axolotl/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

Hi thanks for the library! It would be great if I can log to tensorboard for *each* step, and log to mlflow for each 100 step.

### ✔️ Solution

(see above)

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by winglian** [comment]
There's not an obvious way to do this as it relies on a callback that globally determines if it should log at the end of each step. It's basically all or nothing with the current trainer callback interface unfortunately

**Comment by fzyzcjy** [comment]
Yes I think so... Thus this is a feature in the willing list :)

**Comment by winglian** [comment]
After a little more thinking, you can likely do this by creating a custom plugin/integration that adds a CustomMLFlowCallback  to the trainer. Your custom callback could simply extend the original MLFlowCallback and override the `on_log` and skip the logging based on the state.global_step count according to your requirements. However, this is likely outside the realm of things we'd build for Axolotl OSS, but we provide the hooks and tools to do this without having to modify or fork axolotl using our plugins/integration feature.

**Comment by fzyzcjy** [comment]
Thanks!
