### ISSUE TITLE
Axolotl Crashes At The End Of Training If All Datasets Are Local Directories

### ISSUE THREAD

**Issue by FelixSchneiderZoom** [axolotl-ai-cloud/axolotl#2159]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/axolotl-ai-cloud/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

Axolotl should exit normally at the end of training.

### Current behaviour

`train.py` tries to create a model card at the end of training. If all datasets are local directories, an empty list will be added to to the `model_card_kwargs` in https://github.com/axolotl-ai-cloud/axolotl/blob/0c25bc07a2eb2dca44b1ea763badb8192bddad5a/src/axolotl/train.py#L268-L276

This causes an error in Huggingface Trainer's `create_model_card()`, see https://github.com/huggingface/transformers/issues/35163

As a result of this crash, the writing of the final checkpoint may be aborted, meaning it cannot be loaded.

### Steps to reproduce

Train any model where all datasets point to a local paths on your hard drive.

### Which Operating Systems are you using?

- [X] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.11

### axolotl branch-commit

main/0c25bc0

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by winglian** [comment]
@FelixSchneiderZoom https://github.com/axolotl-ai-cloud/axolotl/pull/2162 should resolve this
