### ISSUE TITLE
Ability to cache downloaded models in Runpod volumes / persist across pod stop-start

### ISSUE THREAD

**Issue by Glavin001** [axolotl-ai-cloud/axolotl#216]
## Problem

If I understand correctly, when models are downloaded they are stored in Huggingface cache directory (I’m not sure where yet). When this cache directory isn’t configured in Runpod as the persisted volume then Pod stops will delete the downloads and need to be incurred on future runs.

## Proposed Solution

Configure Docker image for Runpod to store cache in a volume. 
I can change the configuration output directory to a directory with a storage volume future runs of the Runpod pod will have the checkpoints/etc.

Therefore, the cache directory should also be configured in a way which can be persisted with a volume.
⚠️ Runpod only allows 1 volume path, so ideally this can be configured so we have 1 big catch all folder for persisted data to include cache and checkpoint outputs, etc.

**Comment by winglian** [comment]
I usually dump these when I login :
```
export HF_DATASETS_CACHE="/workspace/data/huggingface-cache/datasets"
export HUGGINGFACE_HUB_CACHE="/workspace/data/huggingface-cache/hub"
export TRANSFORMERS_CACHE="/workspace/data/huggingface-cache/hub"  
```

would be simple enough to set these as ENV vars I think on the runpod docker image or add them to the .bashrc
