### ISSUE TITLE
ImportError: cannot import name 'set_caching_enabled' from 'datasets'

### ISSUE THREAD

**Issue by sankexin** [axolotl-ai-cloud/axolotl#2173]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/axolotl-ai-cloud/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

enable datasets

### Current behaviour

Traceback (most recent call last):
File "/usr/local/lib/python3.10/runpy.py", line 187, in _run_module_as_main
mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
File "/usr/local/lib/python3.10/runpy.py", line 110, in _get_module_details
import(pkg_name)
File "/home/Medusa/axolotl/src/axolotl/cli/init.py", line 23, in
from axolotl.train import TrainDatasetMeta
File "/home/Medusa/axolotl/src/axolotl/train.py", line 23, in
from axolotl.utils.trainer import setup_trainer
File "/home/Medusa/axolotl/src/axolotl/utils/trainer.py", line 13, in
from datasets import set_caching_enabled
ImportError: cannot import name 'set_caching_enabled' from 'datasets' (/usr/local/lib/python3.10/site-packages/datasets/init.py)

### Steps to reproduce

1、axolotl
2、accelerate launch -m axolotl.cli.train examples/medusa/qwen_lora_stage1.yml

### Config yaml

```yaml
examples/medusa/qwen_lora_stage1.yml
```

### Which Operating Systems are you using?

- [X] Linux
- [ ] macOS
- [ ] Windows

### Python Version

python3.10

### axolotl branch-commit

main/d009ead

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by sankexin** [comment]
need to use:
pip install datasets==2.18.0

**Comment by winglian** [comment]
@sankexin You seem to be using an older version of axolotl. That line was updated about 2 months ago as `set_caching_enabled` was deprecated in the `datasets` library.

https://github.com/axolotl-ai-cloud/axolotl/blame/main/src/axolotl/utils/trainer.py#L14
<img width="858" alt="Screenshot 2024-12-11 at 6 06 04 PM" src="https://github.com/user-attachments/assets/5b960308-a00c-42c4-862c-387854303c02" />
