### ISSUE TITLE
`bf16` vs `bfloat16`?

### ISSUE THREAD

**Issue by fzyzcjy** [axolotl-ai-cloud/axolotl#2186]
### What piece of documentation is affected?

Hi thanks for the library! However I am a bit confused about the section below. Usually, "bf16" is abbreviation of "bfloat16" (similar for fp16 and float16). But from doc they seem to have very different semantics.

Thus I would appreciate it if I could know:

1. What does bf16 and bfloat16 config exactly mean in axolotl?
2. For example, I want to make model weight in 32bit (instead of 16bit), but allow forward/backward computation to utilize the faster 16bit types. Which should I enable? (I guess bf16 but not sure)

![image](https://github.com/user-attachments/assets/41084c3f-7c04-4de5-8642-06ccd7547a6b)

### What part(s) of the article would you like to see updated?

(see above)

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by bursteratom** [comment]
Hi, the difference between bf16 and bfloat16 is that bf16 supports Automatic Mixed precision while bfloat14 does not. For more on Automatic Mixed Precision, torch has a good docs on this: https://pytorch.org/tutorials/recipes/recipes/amp_recipe.html

And for your second question, you would want to set bf16 to `auto` and tf32 to `true`.

**Comment by fzyzcjy** [comment]
@bursteratom Hi thanks for the reply! So if I understand correctly:

* bf16: (1) model is still 32bit (2) use AMP such that things like linear layer use 16bit

So I wonder what `bfloat16` does? If model is still 32bit, and it does not do AMP, then it seems it does nothing...
