### ISSUE TITLE
Huggyllama 7b Model Fails to Speak Turkish Despite Training with Alpaca Subset

### ISSUE THREAD

**Issue by kostum123** [axolotl-ai-cloud/axolotl#223]
I encountered an issue while training the Huggyllama 7b model using the Alpaca subset of 1500 instructions translated into Turkish. Despite training the model for 3 epochs with a context size of 2048, the trained model is unable to generate coherent responses in Turkish. Even simple instructions directly from the training set cannot be followed by the trained model. I have performed tests both before and after merging, and the issue persists.

To troubleshoot this problem, I conducted three training runs using Qlora with different settings and diverse datasets, varying the examples and formats. However, the model's inability to speak Turkish persisted across all training runs.

I suspect that the low number of epochs may be a contributing factor to this issue. However, I am unsure if there might be any other underlying bugs or challenges that I am facing. I kindly request assistance in understanding why the trained model is unable to generate coherent responses in Turkish and any recommendations for resolving this issue.

**Steps to Reproduce:**

1. Train the Huggyllama 7b model using the Alpaca subset of 1500 instructions translated into Turkish.
2. Utilize a context size of 2048 during the training process.
3. Train the model for 3 epochs.
4. Test the trained model by providing simple instructions from the training set.
5. Observe that the trained model fails to follow the instructions and generate coherent responses in Turkish.

**Expected Behavior:**

The Huggyllama 7b model should be able to understand and generate coherent responses in Turkish, specificly when provided with instructions directly from the training set.

**Additional Information:**

- Environment: Colab, Qlora, Python 3.10, cu118, a100 40gb
- Training Runs: 5 Epochs: 3
- Dataset Examples and Formats: Varied across training runs
- Issue Occurrence: Consistently observed across all training runs and testing phases.

Please let me know if any additional information or details are required to diagnose and resolve this issue.

**Comment by ehartford** [comment]
7b is too small for translation
You need 33b or 65b

**Comment by winglian** [comment]
Additionally, qlora doesn't train enough parameters for more advanced instructions

**Comment by kostum123** [comment]
Using the 13b model and another model as a base, I was able to make my model speak Turkish(bad) with 1500 instruction data. I think this is due to the fact that the model did not see much or almost no Turkish content while being trained by Facebook. I couldn't decide whether to continue training on text first and teach it to follow instructions after or to increase the instruction dataset to 15 thousand. Thank you for the advice. Which way do you think I should go?

**Comment by NanoCode012** [comment]
Feel free to join discord since this is a more involved question. My experience on language fine-tuning is that you need to pass a lot of data for fine-tuning. 

A larger model would definitely help as said by others. I'm currently using with lora to some decent results, however, qlora is not so good for me. Fullweights would ideally be best.

**Comment by kostum123** [comment]
Thanks for your advice. I have joined the Discord. Now, I will try the Qlora method one last time, but this time with more instruction answer examples. I will report results on discord.
