### ISSUE TITLE
How to perform fine-tuning programmatically with a custom Python script?

### ISSUE THREAD

**Issue by dydx-git** [axolotl-ai-cloud/axolotl#230]
In the examples, we're using `accelerate launch` to launch the finetune script. How to run this if I don't have access to a terminal? I won't be needing to run the script in a distributed env.

**Comment by NanoCode012** [comment]
Hello @dydx-git! The code in the Readme are all meant to run in the terminal. Sorry if I'm not understanding you correctly. How would you git clone the repo and follow other instructions?

**Comment by dydx-git** [comment]
So I've cloned everything and basically I'll be using the `finetune.py` as a module and calling the relevant function through another python script. So I'd be directly using the `finetune.py` and won't have the terminal access when launching the finetune script.

**Comment by NanoCode012** [comment]
You can call `train` function and pass in the params.

**Comment by dydx-git** [comment]
Alright so I don't need the `accelerate` utility, right?

**Comment by NanoCode012** [comment]
I think you should experiment, but it seems ok.

**Comment by Glavin001** [comment]
> I'll be using the finetune.py as a module and calling the relevant function through another python script

> You can call train function and pass in the params.

So a more appropriate issue title/description would be:
> How to perform fine-tuning programmatically with a custom Python script?


@dydx-git : It's a good question. I recommend updating the original issue details to be clear on your intention and sharing any working sample code or lessons learned for others to follow, too 🎉

**Comment by NanoCode012** [comment]
Hey @dydx-git , did we answer your question? Can we close this issue?

@Glavin001 , thanks for making a good point. @dydx-git , would it be possible to rephrase the title?

**Comment by NanoCode012** [comment]
Hello, thank you for the interest. I have updated the title to be a bit more proper following @Glavin001 's recommendation and will close this issue.
