### ISSUE TITLE
pre-commit-hooks demands python3.9

### ISSUE THREAD

**Issue by utensil** [axolotl-ai-cloud/axolotl#233]
I'd encountered this error last time I used pre-commit in CodeSpace, discussed on discord to confirm this is not required but forgot to log the issue.

```
> git -c user.useConfigOnly=true commit --quiet --allow-empty-message --file -
[INFO] Initializing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Initializing environment for https://github.com/psf/black.
[INFO] Initializing environment for https://github.com/pycqa/isort.
[INFO] Initializing environment for https://github.com/PyCQA/flake8.
[INFO] Initializing environment for https://github.com/PyCQA/pylint.
[INFO] Initializing environment for https://github.com/pre-commit/mirrors-mypy.
[INFO] Initializing environment for https://github.com/pre-commit/mirrors-mypy:types-PyYAML.
[INFO] Initializing environment for https://github.com/PyCQA/bandit.
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/usr/local/python/3.10.8/bin/python', '-mvirtualenv', '/home/codespace/.cache/pre-commit/repog143krr1/py_env-python3.9', '-p', 'python3.9')
return code: 1
stdout:
    RuntimeError: failed to find interpreter for Builtin discover of python_spec='python3.9'
stderr: (none)
Check the log at /home/codespace/.cache/pre-commit/pre-commit.log
```

Bypass this issue by installing python 3.9 for now, yet to investigate where is this from:

```
sudo apt update
sudo apt list python3.9
```

**Comment by NanoCode012** [comment]
Source: https://github.com/OpenAccess-AI-Collective/axolotl/blob/9492d4ebb718568305a7402150733c9617bfc29f/.github/workflows/pre-commit.yml#L14

Not sure if we can make it choose 3.9 or 3.10.

For me, it works in my 3.11 dev env.

**Comment by utensil** [comment]
> For me, it works in my 3.11 dev env.

I guess you also have 3.9 installed on your env so it can select that thus no error?

**Comment by utensil** [comment]
The cause is actually here:

https://github.com/OpenAccess-AI-Collective/axolotl/blob/main/.pre-commit-config.yaml#LL1C1-L2C22

![image](https://github.com/OpenAccess-AI-Collective/axolotl/assets/64258/8bd725de-7e19-47ea-ad42-77f06ae22b6b)

A simple test shows that changing this to `python3` will make it adapt to Python 3.10 environment.
