### ISSUE TITLE
Improve documentation and implementation of W&B options

### ISSUE THREAD

**Issue by utensil** [axolotl-ai-cloud/axolotl#236]
1. These options are essentially mapping to the W&B environment variables, for their usage, users need to search and check https://docs.wandb.ai/guides/track/environment-variables#optional-environment-variables , https://docs.wandb.ai/ref/python/watch etc. It might be good to add this link to the readme, and suggest a common usage
2. The implementation could be optimized to just automatically map anything that starts with `wandb_` to the same env var

discord discussion: https://discord.com/channels/1104757954588196865/1111279858136383509/1121703569029091412

**Comment by NanoCode012** [comment]
We need to make sure to migrate any old/incorrect configs and check for old env within `validate_config`..

**Comment by NanoCode012** [comment]
Improved by https://github.com/OpenAccess-AI-Collective/axolotl/pull/361

**Comment by NanoCode012** [comment]
Sorry, I accidentally closed

**Comment by tcapelle** [comment]
Hello, W&B Eng here, I can help with this. Also we should probably not explicitly set the `id` as it's better if it is autogenerated. We could potentially give the user the option to setup the `run_name`, this is what gets displayed on the UI.
Basically, we replace [this](https://github.com/OpenAccess-AI-Collective/axolotl/blob/ec0958f4f846236ac2703dd644f6dac4365f64b4/src/axolotl/utils/wandb_.py#L19) with the `WANBD_NAME` env variable.

We could probably have something like this:
```python
def setup_wandb_env_vars(cfg):
    for key in cfg.__dict__:
        if key.startswith('wandb_'):
            value = cfg.get(key, "")
            if value and len(value) > 0:
                os.environ[key.upper()] = value
            elif key == 'wandb_mode' and value == "offline":
                os.environ["WANDB_MODE"] = value
            else:
                os.environ["WANDB_DISABLED"] = "true"

    # Enable wandb if project name is present
    if cfg.get('wandb_project', "") and len(cfg.get('wandb_project', "")) > 0:
        cfg.use_wandb = True
```
