### ISSUE TITLE
Using a big dataset make an epoch last for 15 steps only

### ISSUE THREAD

**Issue by flotos** [axolotl-ai-cloud/axolotl#239]
I can not provide the dataset for debugging as it is private, but using a 7.95MB dataset make the training weird, with only 15 step and complete 40 epoch in 40 seconds on a A100 GPU. Splitting the dataset into two JSON works properly however. The training was made on the minotaur-15b base model.
The train/step-per-seconds shows that it hasn't seen all the dataset.

<img width="982" alt="Screenshot 2023-06-25 at 09 52 34" src="https://github.com/OpenAccess-AI-Collective/axolotl/assets/5550556/8ec61a5e-0d87-4c1e-9881-d6023889edee">

**Comment by NanoCode012** [comment]
Please provide config

**Comment by NanoCode012** [comment]
Hey, is this still an issue?

After re-reading this, I have some suspicion it could be related to this bug I found: #341

**Comment by flotos** [comment]
Hi, first sorry for not providing the config as a followup, and I don't have any trace of it left as well as the dataset.
There are chances it is related to 341 indeed, but can't provide more information sadly.

**Comment by NanoCode012** [comment]
Sure! No problem :) . Feel free to reopen if you get this issue again.
