### ISSUE TITLE
Trainer() got multiple values for keyword argument 'callbacks'

### ISSUE THREAD

**Issue by jqueguiner** [axolotl-ai-cloud/axolotl#24]
when running (8xA100 80Gb)
I run into this error:

`  File "/root/axolotl/scripts/finetune.py", line 239, in <module>                    
trainer = setup_trainer(cfg, train_dataset, eval_dataset, model, tokenizer)
  File "/root/axolotl/src/axolotl/utils/trainer.py", line 196, in setup_trainer          
Traceback (most recent call last):           
  File "/root/axolotl/scripts/finetune.py", line 239, in <module>                        
    trainer = transformers.Trainer(          
fire.Fire(train)TypeError                                                                
:   File "/root/.local/share/virtualenvs/axolotl-9mRV-5br/lib/python3.9/site-packages/fir
e/core.py", line 141, in Fire                                                            
transformers.trainer.Trainer() got multiple values for keyword argument 'callbacks'
    fire.Fire(train)                                                                     
  File "/root/.local/share/virtualenvs/axolotl-9mRV-5br/lib/python3.9/site-packages/fire/
core.py", line 141, in Fire                                                              
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/root/.local/share/virtualenvs/axolotl-9mRV-5br/lib/python3.9/site-packages/fire/
core.py", line 475, in _Fire                 
    component_trace = _Fire(component, args, parsed_flag_args, context, name)            
  File "/root/.local/share/virtualenvs/axolotl-9mRV-5br/lib/python3.9/site-packages/fire/
core.py", line 475, in _Fire                                                             
    component, remaining_args = _CallAndUpdateTrace(
  File "/root/.local/share/virtualenvs/axolotl-9mRV-5br/lib/python3.9/site-packages/fire/
core.py", line 691, in _CallAndUpdateTrace   
    component, remaining_args = _CallAndUpdateTrace(                                     
  File "/root/.local/share/virtualenvs/axolotl-9mRV-5br/lib/python3.9/site-packages/fire/
core.py", line 691, in _CallAndUpdateTrace                                               
    component = fn(*varargs, **kwargs)       
  File "/root/axolotl/scripts/finetune.py", line 198, in train                           
    component = fn(*varargs, **kwargs)       
  File "/root/axolotl/scripts/finetune.py", line 198, in train                           
    trainer = setup_trainer(cfg, train_dataset, eval_dataset, model, tokenizer)
  File "/root/axolotl/src/axolotl/utils/trainer.py", line 196, in setup_trainer          
    trainer = setup_trainer(cfg, train_dataset, eval_dataset, model, tokenizer)
  File "/root/axolotl/src/axolotl/utils/trainer.py", line 196, in setup_trainer          
    trainer = transformers.Trainer(          
TypeError:     transformers.trainer.Trainer() got multiple values for keyword argument 'c
allbacks'trainer = transformers.Trainer(   `

**Comment by NanoCode012** [comment]
Oh, I see. It could be the new change for saving lora messing with EarlyStopping.

1) Are you training LORA?
2) Does the same issue happen in single GPU?

Issue lines: 
https://github.com/OpenAccess-AI-Collective/axolotl/blob/a27d594788764e095b7751f4eb5a109655b5f0e6/src/axolotl/utils/trainer.py#L193-L195

and 

https://github.com/OpenAccess-AI-Collective/axolotl/blob/a27d594788764e095b7751f4eb5a109655b5f0e6/src/axolotl/utils/trainer.py#L179-L183

Potential fix:

Could you try the below if it works?

```py
    callbacks = []
    # TODO on_save callback to sync checkpoints to GCP/AWS in background
    if cfg.early_stopping_patience:
        early_stop_cb = EarlyStoppingCallback(
            cfg.early_stopping_patience,
        )
        callbacks.append(early_stop_cb)

    data_collator_kwargs = {
        "padding": True,
    }
    if cfg.collator_pad_to_longest:
        data_collator_kwargs["padding"] = "longest"
    else:
        data_collator_kwargs["pad_to_multiple_of"] = 8

    
    if cfg.local_rank == 0 and cfg.adapter == 'lora': # only save in rank 0
        callbacks.append(SavePeftModelCallback)
```

**Comment by NanoCode012** [comment]
- Can reproduce error.

- Setup: Lora+ early_stopping_patience (not related to multi-gpu)

- Fix above: works

- New bug found: (if running in 8bit with EarlyStoppingCallback)
```
assertionerror: EarlyStoppingCallback requires load_best_model_at_end = True
```
https://github.com/huggingface/transformers/blob/3335724376319a0c453049d0cd883504f530ff52/src/transformers/trainer_callback.py#L558-L559

Edit: I think some testing is needed for `load_best_model_at_end` with 8bit. From my previous tests #16 , running them would conflict. Testing on a different machine with very low runs shows no problem. However, could anyone confirm this?
