### ISSUE TITLE
Any special considerations for training a SuperHOT model? (context > 2048 tokens)

### ISSUE THREAD

**Issue by tensiondriven** [axolotl-ai-cloud/axolotl#245]
As the title suggests, in light of SuperHOT giving us finetunes that support 8k and beyond, are there any special considerations for fine-tuning one of these models, ideally from GPTQ 4bit, for longer context lengths?

**Comment by NanoCode012** [comment]
You can try with https://github.com/OpenAccess-AI-Collective/axolotl/pull/248 by enabling `superhot: true`.

I do not know about using with gptq as it hasn't been tested much recently. I would recommend testing with normal fine-tune or lora first.

Edit: I have been told that 4bit gptq should work following discussion here: https://discord.com/channels/1104757954588196865/1104758010959634503/1123870211502784544

I will also rename the config to something better! Thanks.

**Comment by NanoCode012** [comment]
I have updated it to use `scaled_rope` following advice from VisuallyAdequate. Please do tell how it works!

**Comment by ssmi153** [comment]
Just a note that Huggingface Transformers natively supports this now: https://github.com/huggingface/transformers/commit/34d94094279d2c903d9d8a51a65edb265f22c849. Does this make it an easier implementation on Axolotl?

**Comment by NanoCode012** [comment]
Closed by #342
