### ISSUE TITLE
[Feat] Make save checkpoints pushed to hub be private

### ISSUE THREAD

**Issue by NanoCode012** [axolotl-ai-cloud/axolotl#253]
We should probably turn this by default to True?

`hub_private_repo`

Source config: https://huggingface.co/docs/transformers/v4.30.0/en/main_classes/trainer#transformers.TrainingArguments.hub_private_repo

**Comment by Rexhaif** [comment]
Would be nice to actually make it a separate option in the axolotl config. The reason is that HF now imposes 100GB limit on private repos, so people might want to make their checkpoints public, especially if trained model already weights more than 100GB.

**Comment by NanoCode012** [comment]
@Rexhaif , I am open to making this a config (with default still private). Would you be interested in making a PR?
