### ISSUE TITLE
Finetuning Vicuna - Implementation difference in tokenizing/prompting

### ISSUE THREAD

**Issue by jphme** [axolotl-ai-cloud/axolotl#262]
Hi, I noticed there is a `ShareGPTPromptTokenizingStrategy` implemented but not "real" Vicuna prompt strategy.

When looking at the code, I found some differences - but being still a newbie and having very few experience, I have no idea whether these differences matter or what the reasoning behind them is.

But because tuning is expensive and I am still learning, I figured I'd at least ask here before going with the offical repo. 
I like the idea and interface of Axolotl and already used it successfully for a test run tuning an Alpaca instruct model.

## Conversation Templates
[Vicuna 1.1+](https://github.com/lm-sys/FastChat/blob/da0641e567cf93756b0978ab5a6b092e96f06240/fastchat/conversation.py#L286)
```python
# Vicuna v1.1 template
register_conv_template(
    Conversation(
        name="vicuna_v1.1",
        system="A chat between a curious user and an artificial intelligence assistant. "
        "The assistant gives helpful, detailed, and polite answers to the user's questions.",
        roles=("USER", "ASSISTANT"),
        messages=(),
        offset=0,
        sep_style=SeparatorStyle.ADD_COLON_TWO,
        sep=" ",
        sep2="</s>",
    )
)
```

[Share GPT Prompter Template](https://github.com/OpenAccess-AI-Collective/axolotl/blob/b9b7d4ce9292739d7bd3b6113e54786f45db7462/src/axolotl/prompters.py#L262)
```python
        self._conversation = Conversation(
            system=system,
            roles=["USER", "ASSISTANT"],
            messages=[],
            offset=0,
            sep_style=SeparatorStyle.TWO,
            sep=" ",
            sep2=" ",
        )
```

So the sep_style and `sep2` are different, does that make any difference?

## Tokenizers:
[Vicuna](https://github.com/lm-sys/FastChat/blob/da0641e567cf93756b0978ab5a6b092e96f06240/fastchat/train/train.py#L78)
```python
    input_ids = tokenizer(
        conversations,
        return_tensors="pt",
        padding="max_length",
        max_length=tokenizer.model_max_length,
        truncation=True,
    )
```

[Axolotl Tokenizer](https://github.com/OpenAccess-AI-Collective/axolotl/blob/b9b7d4ce9292739d7bd3b6113e54786f45db7462/src/axolotl/prompt_tokenizers.py#L401)
```python
self.tokenizer(
            prompt,
            truncation=True,
            max_length=self.sequence_len,
            padding=False,
            return_tensors=None,
        )
```

But I see there is also some postprocessing happening.

Additionally the code for masking the user input looks different; but this could also be due to the more generalized format.

Did anyone finetune Vicuna with these settings? Many thanks in advance!

**Comment by NanoCode012** [comment]
A user just made a PR for Vicuna 1.1 template https://github.com/OpenAccess-AI-Collective/axolotl/pull/261 in case you're interested.

The one you're referencing in axolotl is original sharegpt.
