### ISSUE TITLE
XGen model

### ISSUE THREAD

**Issue by gururise** [axolotl-ai-cloud/axolotl#267]
Is training SalesForce [XGen](https://huggingface.co/Salesforce/xgen-7b-8k-base) supported w/qlora?

**Comment by NanoCode012** [comment]
Hello @gururise , sorry for the late message here in GH. I think I answered you in Discord (here https://discord.com/channels/1104757954588196865/1111279858136383509/1127729699754344448). Did it work?

**Comment by emmatyping** [comment]
I was successful in finetuning an XGen model with qlora https://huggingface.co/ethanhs/xgen-7b-8k-guanaco using 2 A6000s. I included a sample config in that repo. I put up https://github.com/OpenAccess-AI-Collective/axolotl/pull/306 with the config and updated the README.

**Comment by NanoCode012** [comment]
Closing this thanks to @ethanhs 's PR #306
