### ISSUE TITLE
Discuss: Axolotl CLI, sub-modules, and configuration

### ISSUE THREAD

**Issue by theobjectivedad** [axolotl-ai-cloud/axolotl#292]
Good morning, I want to start a discussion with the community regarding the CLI and how actions can be launched. Axolotl currently supports several actions including: fine-tuning, dataset prep, merge lora, and inferencing. Over time, as more features are added, the logic currently in finetune.py / train could get more complicated as new actions are added. To start a discussion, here are a few thoughts in no particular order:

* Configuration defaults & overrides for example: configuration file, environment variables, CLI options. IMO a consistent hierarchy of configuration defaults & overrides will make it easier for folks to run Axolotl in multiple steps in more complicated pipelines.

* Increase pytest testability: Any refactoring of the CLI should promote as much modularity as possible so individual components can be tested in isolation

* Possible decision: Do we want 1 entrypoint (ex ``finetune.py``) or multiple entrypoints: (ex: ``batch_eval.py``, ``batch_inference.py``, etc.)

* I checked and Fire supports sub-commands and basic help generation, ex:

```python
if __name__ == "__main__":

    fire_config = {
        "train": {
            "function": train,
            "args": {
                "config": {
                    "help": "Path to the configuration file",
                },
            },
            "description": "Invoke finetuning",
        },
        "evaluate": {
            "function": evaluate,
            "args": {...},
            "description": "Perform batch evaluation",
        },
        "inference": {
            "function": inference,
            "args": {...},
            "description": "Interactively perform inferencing",
        },
        "batch_eval": {
            "function": batch_eval,
            "args": {...},
            "description": "Interactively perform inferencing",
        },
    }

    import sys
    if len(sys.argv) >= 2 and sys.argv[1] in ["--help", *fire_config.keys()]:
        # when the first parameter is a command group or "--help" invoke the command group CLI parser
        fire.Fire(fire_config)
    else:
        # Else, invoke backward-compatibility CLI behavior
        fire.Fire(train)
```

* While I personally prefer a single entrypoint with multiple sub-commands, I believe there is a very strong argument to be made that the greater goal is to make it as easy as possible for folks to implement bleeding-edge capabilities quickly. Too much structure in the wrong places could slow things down.

* If there is an appetite to go with multiple sub-commands, maybe [Click](https://click.palletsprojects.com/en/8.1.x/) would be a better option. While I'm currently learning Fire, Click does have good support for subcommands, generating CLI help documentation, validation, CLI option types, and integrating environment variable overrides.

Thanks to the Axolotl community for your hard work and great feedback!

**Comment by theobjectivedad** [comment]
To expand more on a use case I have in mind, I'm imagining that axolotl could support the following 5 major feature areas:

```text
Prepare Dataset(s) -> Finetune -> Quantize/Export -> Benchmark -> Inference (Batch, offline)
```

* The base_config.yaml holds  common configuration / defaults
* Each stage is run as a container and has a reference to base_config.yaml (ideally, this could be 100% parameters + environment variables)
* In each stage, CLI overrides are passed to trigger the desired functionality
* Each stage would be loosely-coupled, have their own CLI/submodule, and cross-stage dependencies would be accessed via well-defined interfaces

**Comment by ashercn97** [comment]
I love Axolotl! I wish there were like docs or something for doing a custom like kind of dataset though. Also, if the falcon presets would work.

**Comment by ashercn97** [comment]
**note** I would love an integration with Gradio !

**Comment by theobjectivedad** [comment]
I've updated #291  with [documentation](https://github.com/OpenAccess-AI-Collective/axolotl/blob/ad995a2c250f8b4834e059c57534e2153dcbdbc4/docs/cli.md)

Please feel free to comment with any feedback!

**Comment by NanoCode012** [comment]
Thank you for this initial discussion. We've migrated to a similar system and will be closing this.
