### ISSUE TITLE
run model.train() on models before training

### ISSUE THREAD

**Issue by winglian** [axolotl-ai-cloud/axolotl#30]
see https://pytorch.org/docs/stable/generated/torch.nn.Module.html#torch.nn.Module.train

**Comment by NanoCode012** [comment]
Do we need this? I never see HF docs asking us to manually set this? I think the Trainer would automatically do this.

**Comment by NanoCode012** [comment]
This might not be needed. Huggingface Trainer sets it at each training step.

https://github.com/huggingface/transformers/blob/8b169142f8b5735f25ad81313ee382350161d993/src/transformers/trainer.py#L2724-L2742
