### ISSUE TITLE
Evaluation, batch inference and inference API

### ISSUE THREAD

**Issue by Ansarimi** [axolotl-ai-cloud/axolotl#303]
I was able to fine-tune a Qlora model. When it comes to inference, I don't see any way do batch inference or APIs. Also no way to evaluation.

Am I missing something or is that part of road map?

**Comment by NanoCode012** [comment]
Maybe this is of interest to you: https://github.com/OpenAccess-AI-Collective/axolotl/pull/291

**Comment by Ansarimi** [comment]
This is it. I will wait for the PR
