### ISSUE TITLE
Using transformers legacy tokenizer

### ISSUE THREAD

**Issue by l3utterfly** [axolotl-ai-cloud/axolotl#305]
When running a full finetune, I get this error: `You are using the legacy behaviour of the <class 'transformers.models.llama.tokenization_llama.LlamaTokenizer'>. This means that tokens that come after special tokens will not be properly handled. We recommend you to read the related pull request available at https://github.com/huggingface/transformers/pull/24565`

Is this an issue? Reading the PR, it seems we can set `Legacy=False` to use the new tokenising behaviour.

**Comment by NanoCode012** [comment]
Feel free to make a PR config for this if you’re interested. I’m not so clear on this even after reading that issue. 

Even llama2 sets legacy to true, so I’m not sure on which case setting to false is good.

**Comment by winglian** [comment]
@l3utterfly This feature was added a few days ago as part of the packing feature. Documentation for YML here https://github.com/OpenAccess-AI-Collective/axolotl/pull/401/files
