### ISSUE TITLE
How to do inference with huggingface with a model that was uploaded with Axolotl.

### ISSUE THREAD

**Issue by ashercn97** [axolotl-ai-cloud/axolotl#309]
I finally got a model on huggingface! This will (hopefully) be my last question so here it goes: i got a model uploaded on huggingface from axolotl, how do i do inference with it from the huggingface thing? I want it to like talk to me like a chatbot like i wanted it to, is there a way to do this through huggingface? Thank yoU!

**Comment by ashercn97** [comment]
Cuz when i do the gradio thing thye have it says there is an error with json. Idk if its on my end or the huggingface thing tho

**Comment by ashercn97** [comment]
Cuz i wanna make a gradio thing

**Comment by ashercn97** [comment]
its saying this on the thing near the model profile::

LlamaConverter requires the protobuf library but it was not found in your environment. Checkout the instructions on the installation page of its repo: https://github.com/protocolbuffers/protobuf/tree/master/python#installation and follow the ones that match your environment. Please note that you may need to restart your runtime after installation.

**Comment by ashercn97** [comment]
Also it said it just uploaded the second epoch model to the hf hub but i dont see the update

**Comment by ashercn97** [comment]
I merged the modle but have no idea how to upload it to the hub...

**Comment by NanoCode012** [comment]
You can just load it using some tool like Ooba, kobold etc

**Comment by ashercn97** [comment]
Im really new to this... What is ooba? (sorry)

**Comment by ashercn97** [comment]
and @NanoCode012 when i try to run it using the like gradio thing huggingface has, it gives me some error about a json file. I put it up over there.

**Comment by ashercn97** [comment]
@NanoCode012  Or about photobuf (?)

**Comment by ashercn97** [comment]
OMG IT WORKS
