### ISSUE TITLE
optionally save as safetensors.

### ISSUE THREAD

**Issue by winglian** [axolotl-ai-cloud/axolotl#31]
might be easier to have a separate option to load a model and re-save it as safetensors

**Comment by NanoCode012** [comment]
I would be interested in working on this PR.

I think it would be easier for separate file for saving. However, for loading, we would need to detect for safe tensors and load differently either way. 

Therefore, should we add a `--safetensor` config into the yml for saving?

```py
from safetensors.torch load_model, save_model

save_model(model, "model.safetensors")
# Instead of save_file(model.state_dict(), "model.safetensors")

load_model(model, "model.safetensors")
# Instead of model.load_state_dict(load_file("model.safetensors"))
```
https://huggingface.co/docs/safetensors/torch_shared_tensors

Also, this won't work for LORA right? Unless we add another script to merge lora with base?

**Comment by NanoCode012** [comment]
In case anyone wants to tackle this instead, it is open. Sorry, I did not get the time to work on this yet.

For saving: https://huggingface.co/docs/transformers/main_classes/trainer#transformers.TrainingArguments.save_safetensors

I am not sure about loading, however, we need to also consider whether to save/load LORA as safe tensors.

**Comment by NanoCode012** [comment]
Seems like peft also support safe tensors now: https://github.com/huggingface/peft/pull/553
