### ISSUE TITLE
Add support for running predictions as part of evals

### ISSUE THREAD

**Issue by winglian** [axolotl-ai-cloud/axolotl#311]
see https://discord.com/channels/1104757954588196865/1111279858136383509/1131920425513914408

Monkey patch code: https://github.com/utensil/llm-playground/blob/main/helper/train.py#L200

**Comment by NanoCode012** [comment]
For future readers, we have eval predictions logging to wandb using `eval_table_size: ` abeit a bit buggy.

There's also `do_bench_eval: ` and `bench_dataset: ` for setting bench dataset.

**Comment by JianbangZ** [comment]
> For future readers, we have eval predictions logging to wandb using `eval_table_size: ` abeit a bit buggy.
> 
> There's also `do_bench_eval: ` and `bench_dataset: ` for setting bench dataset.

I saw mmlu supported, but it takes too long to run it while training. Is there built-in support for other smaller common benchmark like hellaswag etc.?

**Comment by NanoCode012** [comment]
@JianbangZ  I'm not too familiar on this, but we do support custom benchmark dataset: https://github.com/OpenAccess-AI-Collective/axolotl/blob/89134f2143cd3325802813eb97cd05c783932201/src/axolotl/utils/callbacks/__init__.py#L203-L213

An example bench_dataset value can be seen here (look at the HF dataset to see sample): https://github.com/OpenAccess-AI-Collective/axolotl/blob/89134f2143cd3325802813eb97cd05c783932201/src/axolotl/core/trainer_builder.py#L154-L159
