### ISSUE TITLE
Does Axolotl work with a different sized OpenLlama?

### ISSUE THREAD

**Issue by ashercn97** [axolotl-ai-cloud/axolotl#320]
Like if i did openlm-research/openllama-7b would it work? (SORRY IVE MADE SO MANY ISSUES I JUST DONT KNOW WHERE ELSE TO ASK THESE QUESTIONS)

**Comment by NanoCode012** [comment]
Yes, it should. You can use discord for informal questions like this (link in readme). I think there are others who frequently check.

**Comment by ashercn97** [comment]
ok ty!!
