### ISSUE TITLE
How to upload the whole model to the hub, not just the adapters?

### ISSUE THREAD

**Issue by ashercn97** [axolotl-ai-cloud/axolotl#323]
Hi. Ive gotten 3 models on the HuggingFace hub with Axolotl but they have only uploaded the adapters. This was fine except it makes it a little hard to use because I have to load both models and it doesnt let me use some features I would like to use. Is there a way to upload like the whole model after fine tuning when doing a LoRA or QLorA thign but upload it as the whole model so I can use it in the transformers library instead fo the PEFT library? Idk if this is possible but yeah. Thanks!

**Comment by ashercn97** [comment]
cuz i think it would be awesome to just have to use the transformer library to import my model!

**Comment by NanoCode012** [comment]
Hey, sorry for the late reply. I thought I replied.

Do you mean to upload a `merged` model to HF? As I understand, the trainer does upload the trained model (either full or adapters) depending on your training method.

**Comment by ashercn97** [comment]
Yes I meant the merged model, but i figured it out and forgot to close. Sorry! Thanks for your help!!
