### ISSUE TITLE
Peft installation disabled in setup.py

### ISSUE THREAD

**Issue by theobjectivedad** [axolotl-ai-cloud/axolotl#324]
The peft installation in [setup.py](https://github.com/OpenAccess-AI-Collective/axolotl/blob/9f69c4d8c1218904b4b9b1a8e4013009c7fc1863/setup.py#L7) is currently disabled with a note about validating int4 compatibility.

Currently this is causing [an issue](https://github.com/OpenAccess-AI-Collective/axolotl/actions/runs/5661140355/job/15338403291?pr=291) when unit testing #291 since it contains references to peft. As a workaround, I can add peft to ``requirements-tests.txt`` however the permanent solution should be to update ``setup.py``.

**Comment by theobjectivedad** [comment]
Just an update, I decided to work around this by removing peft references in the code that was being unit testing. I recommend leaving this open to remove the logic that disables peft in setup.py when we can but at the moment the urgency is low at last for me.

**Comment by tmm1** [comment]
I think we can simply start depending on peft

**Comment by winglian** [comment]
now that legacy gptq has been dropped, this is no longer an issue
