### ISSUE TITLE
Python 3.11 is not supported for torch.compile

### ISSUE THREAD

**Issue by winglian** [axolotl-ai-cloud/axolotl#352]
add to the readme a disclaimer that torch.compile is not supported with python 3.11
add to the validation a check for python 3.11 and simply warn about this
skip torch.compile if python 3.11

**Comment by tmm1** [comment]
It works with torch 2.1.0 nightly FYI

**Comment by NanoCode012** [comment]
Closing as support was added: https://github.com/pytorch/pytorch/issues/104918
