### ISSUE TITLE
save steps enhancement

### ISSUE THREAD

**Issue by winglian** [axolotl-ai-cloud/axolotl#38]
if save_steps is a fraction, calculate the steps based on floor(save_steps * total_steps_per_epoch).

this way if someone were to say 0.5, they could get a checkpoint at half an epoch and the end of an epoch without having to manually figure  it out

**Comment by NanoCode012** [comment]
Taken from discord: `_ratio` might be interesting as you said.

https://discord.com/channels/1104757954588196865/1111279858136383509/1116366177430667385

**Comment by winglian** [comment]
this has been resolved with #547
