### ISSUE TITLE
Exception: Could not find the transformer layer class to wrap in the model.

### ISSUE THREAD

**Issue by pshivraj** [axolotl-ai-cloud/axolotl#394]
Hello everyone.

I'm trying to train LoRA by using the [examples](https://github.com/OpenAccess-AI-Collective/axolotl/tree/main/examples/llama-2) given for llama-2 using the default config with following changes
 `fp16: true` 
 `flash_attention: false`

When I launched it with command

`accelerate launch scripts/finetune.py examples/llama-2/lora.yml`

It returned this error:

`Traceback (most recent call last):
  File "/data/ebay/notebooks/pshivraj/Experimenting/trainer/axolotl/scripts/finetune.py", line 338, in <module>
    fire.Fire(train)
  File "/home/pshivraj/.local/lib/python3.9/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/pshivraj/.local/lib/python3.9/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/pshivraj/.local/lib/python3.9/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/data/ebay/notebooks/pshivraj/Experimenting/trainer/axolotl/scripts/finetune.py", line 323, in train
    trainer.train(resume_from_checkpoint=resume_from_checkpoint)
  File "/home/pshivraj/.local/lib/python3.9/site-packages/transformers/trainer.py", line 1539, in train
    return inner_training_loop(
  File "/home/pshivraj/.local/lib/python3.9/site-packages/transformers/trainer.py", line 1658, in _inner_training_loop
    self.model = self.accelerator.prepare(self.model)
  File "/home/pshivraj/.local/lib/python3.9/site-packages/accelerate/accelerator.py", line 1251, in prepare
    result = tuple(
  File "/home/pshivraj/.local/lib/python3.9/site-packages/accelerate/accelerator.py", line 1252, in <genexpr>
    self._prepare_one(obj, first_pass=True, device_placement=d) for obj, d in zip(args, device_placement)
  File "/home/pshivraj/.local/lib/python3.9/site-packages/accelerate/accelerator.py", line 1079, in _prepare_one
    return self.prepare_model(obj, device_placement=device_placement)
  File "/home/pshivraj/.local/lib/python3.9/site-packages/accelerate/accelerator.py", line 1398, in prepare_model
    self.state.fsdp_plugin.set_auto_wrap_policy(model)
  File "/home/pshivraj/.local/lib/python3.9/site-packages/accelerate/utils/dataclasses.py", line 928, in set_auto_wrap_policy
    raise Exception("Could not find the transformer layer class to wrap in the model.")
Exception: Could not find the transformer layer class to wrap in the model.`

pip list of the env:

absl-py                  1.4.0
accelerate               0.21.0
addict                   2.4.0
aiohttp                  3.8.5
aiosignal                1.3.1
appdirs                  1.4.4
async-lru                2.0.3
async-timeout            4.0.3
attrs                    23.1.0
axolotl                  0.1        trainer/axolotl/src
bert-score               0.3.13
bitsandbytes             0.41.1
Brotli                   1.0.9
certifi                  2023.5.7
charset-normalizer       3.1.0
click                    8.1.6
cmake                    3.27.2
coloredlogs              15.0.1
contourpy                1.1.0
cycler                   0.11.0
datasets                 2.13.1
dill                     0.3.6
distlib                  0.3.7
docker-pycreds           0.4.0
einops                   0.6.1
evaluate                 0.4.0
filelock                 3.12.2
fire                     0.5.0
fonttools                4.42.0
frozenlist               1.4.0
fsspec                   2023.6.0
gitdb                    4.0.10
GitPython                3.1.32
hf_transfer              0.1.3
huggingface-hub          0.16.4
humanfriendly            10.0
idna                     3.4
importlib-resources      6.0.1
inflate64                0.3.1
ipympl                   0.9.3
ipywidgets               8.0.7
Jinja2                   3.1.2
joblib                   1.3.2
jupyter-lsp              2.2.0
jupyter_server           2.7.0
jupyterlab               4.0.3
jupyterlab_server        2.23.0
jupyterlab-widgets       3.0.8
kiwisolver               1.4.4
lit                      16.0.6
llvmlite                 0.40.1
MarkupSafe               2.1.3
matplotlib               3.7.2
mpmath                   1.3.0
multidict                6.0.4
multiprocess             0.70.14
multivolumefile          0.2.3
mypy-extensions          1.0.0
networkx                 3.1
nltk                     3.8.1
numba                    0.57.1
numpy                    1.24.0
nvidia-cublas-cu11       11.10.3.66
nvidia-cuda-cupti-cu11   11.7.101
nvidia-cuda-nvrtc-cu11   11.7.99
nvidia-cuda-runtime-cu11 11.7.99
nvidia-cudnn-cu11        8.5.0.96
nvidia-cufft-cu11        10.9.0.58
nvidia-curand-cu11       10.2.10.91
nvidia-cusolver-cu11     11.4.0.1
nvidia-cusparse-cu11     11.7.4.91
nvidia-nccl-cu11         2.14.3
nvidia-nvtx-cu11         11.7.91
optimum                  1.11.1
packaging                23.1
pandas                   2.0.3
pathtools                0.1.2
peft                     0.4.0
Pillow                   10.0.0
pip                      23.2.1
protobuf                 4.24.0
psutil                   5.9.5
py4j                     0.10.9.7
py7zr                    0.20.5
pyarrow                  12.0.1
pybcj                    1.0.1
pycryptodome             3.18.0
pycryptodomex            3.18.0
pykrylov                 0.22.0
pynvml                   11.5.0
pyparsing                3.0.9
pyppmd                   1.0.0
pyre-extensions          0.0.29
python-dateutil          2.8.2
pytz                     2023.3
PyYAML                   6.0
pyzstd                   0.15.9
regex                    2023.8.8
requests                 2.31.0
requests-toolbelt        1.0.0
responses                0.18.0
rouge-score              0.1.2
safetensors              0.3.2
scikit-learn             1.2.2
scipy                    1.11.1
sentencepiece            0.1.99
sentry-sdk               1.29.2
setproctitle             1.3.2
setuptools               68.0.0
six                      1.16.0
smmap                    5.0.0
sympy                    1.12
termcolor                2.3.0
texttable                1.6.7
threadpoolctl            3.2.0
tokenizers               0.13.3
torch                    2.0.1
tqdm                     4.65.0
transformers             4.31.0
triton                   2.0.0
typing_extensions        4.7.1
typing-inspect           0.9.0
tzdata                   2023.3
urllib3                  1.26.16
virtualenv               20.24.3
wandb                    0.15.8
wheel                    0.41.1
widgetsnbextension       4.0.8
xformers                 0.0.20
xxhash                   3.3.0
yarl                     1.9.2
zipp                     3.16.2

Do you see something obvious that I am missing out on?

**Comment by winglian** [comment]
Did you enable fsdp by any chance? It looks like fsdp is enabled, but not configured. Or did you run accelerate configure? (We don't recommend that)

**Comment by NanoCode012** [comment]
I tested on latest main and could not replicate the issue on 1 GPU.

**Comment by pshivraj** [comment]
Thanks for your response. I did explicitly set fsdp to false 

<img width="1237" alt="Screenshot 2023-08-14 at 9 50 25 PM" src="https://github.com/OpenAccess-AI-Collective/axolotl/assets/17194636/e09de2eb-3b47-40ae-870b-21efdf92f577">


still I am not sure why I see logger with a warning message which indicates apparently fsdp is still enabled. 

<img width="1231" alt="Screenshot 2023-08-14 at 9 50 47 PM" src="https://github.com/OpenAccess-AI-Collective/axolotl/assets/17194636/e2c3bfe7-c9d4-40ee-b1bf-213ef3fc48f3">

I'll keep digging, incase you are have suggestion that would be great.

**Comment by winglian** [comment]
is there a `~/.cache/default_config.yaml` file on your system? if so delete it please. It definitely looks like FSDP is configured somewhere.

**Comment by pshivraj** [comment]
Yes, it works. There was this file `.cache/huggingface/default_config .yaml` which I deleted, It seems to been present based on my other project. Thanks again for pointing in the right direction.
