### ISSUE TITLE
flash-attn wheels

### ISSUE THREAD

**Issue by winglian** [axolotl-ai-cloud/axolotl#414]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/OpenAccess-AI-Collective/axolotl/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/OpenAccess-AI-Collective/axolotl/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

Now that flash-attn provides wheels, we can remove it from the docker base image and simply install it with requirements.txt

### ✔️ Solution

see above

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by NanoCode012** [comment]
Was the latest fa tested to make sure it works?

**Comment by tmm1** [comment]
I have been testing the new releases
