### ISSUE TITLE
Training run fails to start with error "TypeError: openssl_md5() takes at most 1 argument (2 given)"

### ISSUE THREAD

**Issue by vmay-chegg** [axolotl-ai-cloud/axolotl#416]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/OpenAccess-AI-Collective/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

The training run should start.

### Current behaviour

Getting the error: 
TypeError: openssl_md5() takes at most 1 argument (2 given)

### Steps to reproduce

Follow the Quickstart steps from Readme.md:

git clone https://github.com/OpenAccess-AI-Collective/axolotl

pip3 install -e .
pip3 install -U git+https://github.com/huggingface/peft.git
accelerate launch scripts/finetune.py examples/openllama-3b/lora.yml

Env info:
Ubuntu
8x A100 GPU
Python 3.10.12

### Which Operating Systems are you using?

- [X] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.10.12

### axolotl branch-commit

main/c01015f33f257badd05fbf8e680f22c294e9628e

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by NanoCode012** [comment]
Could you provide stack trace please?

**Comment by winglian** [comment]
Caused by these calls here
https://github.com/OpenAccess-AI-Collective/axolotl/blob/f806e86a6ef253937ec6433884ca1c0ac47d4066/src/axolotl/utils/data.py#L471-L476

The linter required I add `usedforsecurity=False` since we don't need cryptographic hashes. Might be related to the version of openssl

**Comment by winglian** [comment]
perhaps implement something like https://github.com/fabianvf/python/commit/1ac54eff7b7427a4470f642a7e827fe0cd5e5472

**Comment by NanoCode012** [comment]
Weirdly, it says it was added in py3.9 in that linked Issue, but the author uses python 3.10

**Comment by adarshxs** [comment]
Any fix? I encountered the same error

**Comment by NanoCode012** [comment]
@adarshxs , could you provide your env and stack trace? Are you running in docker or conda?
