### ISSUE TITLE
flash attention should be required when using sample_packing

### ISSUE THREAD

**Issue by winglian** [axolotl-ai-cloud/axolotl#449]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/OpenAccess-AI-Collective/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

validation error should occur

### Current behaviour

no validation error

### Steps to reproduce

set sample_packing: false and flash_attention: false

### Possible solution

add validation

### Which Operating Systems are you using?

- [X] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.10

### axolotl branch-commit

main

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by PhilipMay** [comment]
Hi @winglian and @NanoCode012 .

I am using old V100 GPUs and they do not support flash attention.
But it works with sample_packing.

What exactly is wrong on using sample_packing without flash attention?
Why is this a bug?

**Comment by winglian** [comment]
I think this may be less of an issue now that we support 2d attention masks if not using flash attention
