### ISSUE TITLE
question about runpod template

### ISSUE THREAD

**Issue by ashercn97** [axolotl-ai-cloud/axolotl#454]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/OpenAccess-AI-Collective/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

How do I use the runpod axolotl template? It is giving me an error when i run the accelerate launch scripts/finetune.py config/hippo.yml command **note it is config and not configs ( that was already taken. ). It is starting then saying something returned a non zero exit thing. Is the thing stil lworking?

### Current behaviour

*

### Steps to reproduce

*

### Possible solution

*

### Which Operating Systems are you using?

- [X] Linux
- [ ] macOS
- [ ] Windows

### Python Version

whatever hte runpod thing is

### axolotl branch-commit

whatever the runpod thing is

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by NanoCode012** [comment]
Hello, may I ask where you got the config?

**Comment by ashercn97** [comment]
I made it!! It is:

`base_model:` meta-llama/Llama-2-7b-hf
base_model_config: meta-llama/Llama-2-7b-hf
model_type: LlamaForCausalLM
tokenizer_type: LlamaTokenizer

load_in_8bit: false
load_in_4bit: true
strict: false

datasets:
  - path: garage-bAInd/Open-Platypus
    type: alpaca
  - path: ashercn97/OpenOrcaPleaseWork
    type: alpaca
dataset_prepared_path: last_run_prepared
hub_model_id: ashercn97/hippo-7b-QLoRA
val_set_size: 0.005
output_dir: ./hippo-out

adapter: qlora
lora_model_dir:

sequence_len: 4096
max_packed_sequence_len: 4096
lora_r: 32
lora_alpha: 16
lora_dropout: 0.05
lora_target_modules:
lora_target_linear: true
lora_fan_in_fan_out:

wandb_project: hippo-7b
wandb_watch:
wandb_run_id:
wandb_log_model:

gradient_accumulation_steps: 4
micro_batch_size: 4
num_epochs: 1
optimizer: paged_adamw_32bit
lr_scheduler: cosine
learning_rate: 0.0002

train_on_inputs: false
group_by_length: true
bf16: true
fp16: false
tf32: false

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention: true
flash_attention:
rope_scaling:
  type: linear
  factor: 2

warmup_steps: 10
eval_steps: 20
save_steps:
debug:
deepspeed:
weight_decay: 0.0
fsdp:
fsdp_config:
special_tokens:
  bos_token: "<s>"
  eos_token: "</s>"
  unk_token: "<unk>"`

**Comment by ashercn97** [comment]
Also there are some other things @NanoCode012 . First, i tried training a model before and what happened was i stopped it after 1 epohc because it uploaded to hf but then it was a pickle file (first time ever since i started using axolotl) then when i merged the lora to base it worked but then when i tried to use it and stuff it didnt so then i tried to merge it again and it didnt work, thats hwy im doing this!

**Comment by NanoCode012** [comment]
Please provide full error.

**Comment by ashercn97** [comment]
I already got out of the pod but i will do it again and give the full error

**Comment by NanoCode012** [comment]
To use the runpod template, you could load it when creating the pod using the provided docker image on the Readme. It should be just like that. No extra settings.

**Comment by ashercn97** [comment]
I ran it but now when i merge the model using and try to uplaod it to hub, its not working. Im getting this error:

RuntimeError: File /tmp/tmp2h784x4l/pytorch_model-00002-of-00002.bin cannot be opened.

i used this scriptr the merge:

import torch
from peft import PeftModel
import transformers
import os, time
import tempfile
from transformers import AutoModelForCausalLM, AutoTokenizer


BASE_MODEL = "meta-llama/Llama-2-7b-hf"
LORA_WEIGHTS = "ashercn97/hippo-7b-QLoRA-2"

tokenizer = AutoTokenizer.from_pretrained(BASE_MODEL)


model = AutoModelForCausalLM.from_pretrained(
    BASE_MODEL,
    load_in_4bit=False,
    torch_dtype=torch.float16,
    device_map="auto",
    offload_folder="offload",
)

model = PeftModel.from_pretrained(
    model,
    LORA_WEIGHTS,
    torch_dtype=torch.float16,
    device_map="auto",
    offload_folder="offload",

)

model = model.merge_and_unload()

**Comment by ashercn97** [comment]
im trying to upload to hf hub using safetensors, not working

**Comment by ashercn97** [comment]
@NanoCode012  like it wont let me do it as a safetensor, like doing model.push_to_hub("lsdkjflkdfs", use_safetensors=True)

**Comment by ashercn97** [comment]
Actually this is a new issue so im gonna make it a new thing. !!
