### ISSUE TITLE
After training using RoPE scaling, then merging to base and uploading, safe tensors are not working.

### ISSUE THREAD

**Issue by ashercn97** [axolotl-ai-cloud/axolotl#458]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/OpenAccess-AI-Collective/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

I wanted to be able to merge it and upload as safe tensors file as I usually do, but it gave things about something not matching up. I dont have the exact message, but I can get it if needed. It worked as a normal pytorch_model.bin file. Also, it used to work when i didnt do rope scaling, so im wondering if that is the stem of the issue.

### Current behaviour

*

### Steps to reproduce

*

### Possible solution

*

### Which Operating Systems are you using?

- [X] Linux
- [ ] macOS
- [ ] Windows

### Python Version

whatever the runpod thing is

### axolotl branch-commit

runpod thing

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by NanoCode012** [comment]
Hello, rope_scaling has been merged to upstream transformers for a while now. I think this issue should've been fixed already. Closing it.
