### ISSUE TITLE
Way to upload merged LoRAs to hf hub using axolotl

### ISSUE THREAD

**Issue by ashercn97** [axolotl-ai-cloud/axolotl#459]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/OpenAccess-AI-Collective/axolotl/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/OpenAccess-AI-Collective/axolotl/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

A command that would upload the LoRA merged to the base model to the HF hub in an easy way. Ive had a ton of trouble uploading my merged models so this would be super helpful!

### ✔️ Solution

I want there to be a way to use the train command maybe and after merging the LoRA using the merge thing being able ot upload it to hf hub.

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by winglian** [comment]
#460 should resolve this

**Comment by NanoCode012** [comment]
I think the author wants to auto-upload to HF. PR 460 only merges it automatically.

**Comment by ashercn97** [comment]
@NanoCode012  Yes exactly ty

**Comment by NanoCode012** [comment]
I don't know if axolotl should support this (discussion welcome). It seems something simple to write a short script for.

https://huggingface.co/docs/huggingface_hub/v0.16.3/guides/upload#upload-a-folder

**Comment by ashercn97** [comment]
@NanoCode012  Ive had a hard time doing it for some reason, thats why i suggested it. I might be wrong tho

**Comment by NanoCode012** [comment]
Could you please detail what's the problem? @ashercn97 

```py
from huggingface_hub import HfApi
api = HfApi()

api.upload_folder(
    folder_path="/path/to/merged/folder",
    repo_id="username/my-cool-model",
    repo_type="model",
)
```

**Comment by ashercn97** [comment]
@NanoCode012  I forget but maybe ill try again next time i fine tune a model, for now we can close this if you want!!

**Comment by ghost** [comment]
That would be awesome feature. Autotrain advanced supports this
https://github.com/huggingface/autotrain-advanced/blob/cea867576d1189fb6a2c4a9fdcdff4047da7eb0b/src/autotrain/cli/run_llm.py#L252

**Comment by NanoCode012** [comment]
@mimumo , there is a slight issue with merging right after train as stated in PR #460 . I think we can simply reload the model again and merge + upload, though this PR is a bit old by now.

**Comment by monk1337** [comment]
Use 

```
from huggingface_hub import HfApi
api = HfApi()

api.upload_folder(
    folder_path="/path/to/merged/folder",
    repo_id="username/my-cool-model",
    repo_type="model",
)
```

or 

`huggingface-cli upload username/my-cool-model .`
