### ISSUE TITLE
Using the default LoRA config.yml for LLaMA2 results in `cfg.batch_size // cfg.micro_batch_size TypeError: unsupported operand type(s) for //: 'NoneType' and 'NoneType'`

### ISSUE THREAD

**Issue by Saatvik-droid** [axolotl-ai-cloud/axolotl#465]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/OpenAccess-AI-Collective/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

Running the training script as given in the documentation `accelerate launch scripts/finetune.py configs/your_config.yml`.
I used the example config as provided at https://github.com/OpenAccess-AI-Collective/axolotl/blob/main/examples/llama-2/lora.yml.

### Current behaviour

The script results in
```File "/usr/axolotl/src/axolotl/utils/config.py", line 43, in normalize_config
    cfg.batch_size // cfg.micro_batch_size
TypeError: unsupported operand type(s) for //: 'NoneType' and 'NoneType'
```

### Steps to reproduce

1. Clone the repo
2. Create a `configs` directory and create a config.yml file.
3. Run `accelerate launch scripts/finetune.py configs/your_config.yml`.

### Which Operating Systems are you using?

- [X] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.10

### axolotl branch-commit

main/d5dcf9c

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by Saatvik-droid** [comment]
Using the config file directly from the `examples` directory seems to work.

**Comment by NanoCode012** [comment]
Oh, that was just a placeholder path to "your" config. I'll remove the top dir as it's not used yet.

**Comment by Saatvik-droid** [comment]
No no I copy pasted the config from the example to the configs directory but it didn't seem to work but using the examples directory itself worked.

I ended up just copying the example config file over.

Must've been a copy-paste error on my end. Apologize for the inconvenience.
