### ISSUE TITLE
Latest docker images missing axolotl program files 

### ISSUE THREAD

**Issue by dandm1** [axolotl-ai-cloud/axolotl#467]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/OpenAccess-AI-Collective/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

The program directory on the runpod docker images should contain the program files.

### Current behaviour

When I download the latest image from docker hub into runpod, I find that the /workspace/axolotl directory is empty. Tried with both the python 3.9 and python 3.10 images. When we try the 2.0.0 version that was built a month ago the expected files are there, and we beehive they were there yesterday.

### Steps to reproduce

Launch program from docker hub

### Which Operating Systems are you using?

- [X] Linux
- [ ] macOS
- [X] Windows

### Python Version

3.9 and 3.10

### axolotl branch-commit

main, I guess

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by dandm1** [comment]
This may be an issue on runpod rather than the base image. Usually fails, but have managed to get it to run once on a slow download server.

**Comment by Palmik** [comment]
I am also running into this.
