### ISSUE TITLE
layernorm should be in float32 for full weight fine tunes w/o flash attention

### ISSUE THREAD

**Issue by winglian** [axolotl-ai-cloud/axolotl#469]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/OpenAccess-AI-Collective/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

layernorm should be in float32 for full weight fine tunes w/o flash attention

### Current behaviour

currently in bfloat16

### Steps to reproduce

```yaml
flash_attention: 
adapter: 
```

### Possible solution

currently we only fix it back to float32 inside the load_lora function. We should additionally handle this outside of that.

### Which Operating Systems are you using?

- [X] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.10

### axolotl branch-commit

main

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by NanoCode012** [comment]
Closing as this is done. Layer norm is set to fp32 for non-fsdp runs. https://github.com/OpenAccess-AI-Collective/axolotl/blob/89134f2143cd3325802813eb97cd05c783932201/src/axolotl/utils/models.py#L655-L659
