### ISSUE TITLE
ReLoRA example config

### ISSUE THREAD

**Issue by ehartford** [axolotl-ai-cloud/axolotl#470]
### What piece of documentation is affected?

can there please be an example config for ReLoRA?

### What part(s) of the article would you like to see updated?

can there please be an example config for ReLoRA?

### Additional Information

can there please be an example config for ReLoRA?

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by NanoCode012** [comment]
Seems like the author of the PR https://github.com/OpenAccess-AI-Collective/axolotl/pull/322#issue-1819539344 provided some sample

**Comment by ehartford** [comment]
that isn't a full config file though.  I don't know what other things are needed or not needed.

**Comment by ehartford** [comment]
and also - a PR comment isn't documentation, it would be good to have it in a real example file that can be executed and functions

**Comment by NanoCode012** [comment]
That's a good point. Perhaps @cg123 might be interested in a PR to add this config since they already have one.
