### ISSUE TITLE
ShareGPT:chat format doesn't seem to work

### ISSUE THREAD

**Issue by l3utterfly** [axolotl-ai-cloud/axolotl#472]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/OpenAccess-AI-Collective/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

ShareGPTPromptTokenizationStrategy is not being called at all when preparing datasets

### Current behaviour

ShareGPTPromptTokenizationStrategy should be invoked when preparing datasets.

### Steps to reproduce

1. prepare a sharegpt:chat dataset format
2. prepare dataset by using --prepare_ds_only
3. Debugging through the code, the ShareGPTPromptTokenizationStrategy is not being called at all

I did some modifications to the strategy just to test, and the modifications are not applied.

### Possible solution

<img width="368" alt="image" src="https://github.com/OpenAccess-AI-Collective/axolotl/assets/6970347/cd2a2df6-a72c-46fd-907c-36bff402fb55">

Here it seems "features" contains the "conversations" key. Which will drop the column "conversations". The ShareGPT dataset contains only "conversations" key, so everything is dropped.

I tested by changing this part to an empty array `[]`, and the ShareGPT tokenizing strategy will be invoked again.

### Which Operating Systems are you using?

- [ ] Linux
- [ ] macOS
- [X] Windows

### Python Version

0.2.1

### axolotl branch-commit

d5dcf9c

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by NanoCode012** [comment]
Could you provide sample of your dataset?

**Comment by l3utterfly** [comment]
Dataset looks like this:

```
[
    {
        "conversations": [
            {
                "from": "human",
                "value": "I'd like to have a office equipment upgrade on new year's eve, can you schedule that?"
            },
            {
                "from": "gpt",
                "value": "#[layla_schedule(\"office equipment upgrade\",\"on new year's eve\")]"
            }
        ]
    },
    {
        "conversations": [
            {
                "from": "human",
                "value": "Insert a software update into my schedule in a month"
            },
            {
                "from": "gpt",
                "value": "#[layla_schedule(\"software update\",\"in a month\")]"
            }
        ]
    },
    {
        "conversations": [
            {
                "from": "human",
                "value": "Let's put a crisis management meeting on december 25th, 2023, at 12:00 pm in my schedule"
            },
            {
                "from": "gpt",
                "value": "#[layla_schedule(\"crisis management meeting\",\"on december 25th, 2023, at 12:00 pm\")]"
            }
        ]
    },
    {
        "conversations": [
            {
                "from": "human",
                "value": "I'd like to be reminded to walk the dog in two weeks at 10:00 am"
            },
            {
                "from": "gpt",
                "value": "#[layla_schedule(\"walk the dog\",\"in two weeks at 10:00 am\")]"
            }
        ]
    },
    {
        "conversations": [
            {
                "from": "human",
                "value": "Help me schedule a dance class on october 31st, 2023, at 8:00 pm"
            },
            {
                "from": "gpt",
                "value": "#[layla_schedule(\"dance class\",\"on october 31st, 2023, at 8:00 pm\")]"
            }
        ]
    }
]
````

+800,000 rows

**Comment by NanoCode012** [comment]
> Here it seems "features" contains the "conversations" key. Which will drop the column "conversations". The ShareGPT dataset contains only "conversations" key, so everything is dropped.

The dataset is tokenized, then we remove the original data from tokenized set.

Regarding dataset, I have not used `json` based data for a while. Could you try as jsonl? It's just one row per conversations set.
`{"conversations": [{"from": "...", "value": "..."}]}`

**Comment by l3utterfly** [comment]
> The dataset is tokenized, then we remove the original data from tokenized set.

Is this an issue? My data is not tokenized, but it appears that axolotl thinks it's tokenized and removes the "conversation" key.

I'll try jsonl in a bit, thanks

**Comment by NanoCode012** [comment]
> Is this an issue? My data is not tokenized, but it appears that axolotl thinks it's tokenized and removes the "conversation" key.

Oh no. It was just an explanation for what's happening in that code block. Axolotl tokenizes the dataset then remove the source data.

**Comment by NanoCode012** [comment]
Hello, was this solved?

**Comment by l3utterfly** [comment]
As a workaround, I hardcoded `features = []`. That got my data tokenised.

But the root issue still persists.

**Comment by winglian** [comment]
I'm pretty sure the current implementation is correct. it removes the existing features, because upon tokenization, all the features in the dataset are not needed anymore

**Comment by Speedway1** [comment]
Hello, what file did you put the "features = []" into? Because we're having exactly the same issue on the latest code.

**Comment by l3utterfly** [comment]
> Hello, what file did you put the "features = []" into? Because we're having exactly the same issue on the latest code.

It's been quite a while, but as I recall simply removing "features" did solve the root cause (even though it got tokenized, the training failed).

I'm using JSONL, which doesn't seem to have this problem.
