### ISSUE TITLE
can I finetune Llama-2-70B using 16 * A10( 16 * 23G) in one machine

### ISSUE THREAD

**Issue by babytdream** [axolotl-ai-cloud/axolotl#488]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/OpenAccess-AI-Collective/axolotl/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/OpenAccess-AI-Collective/axolotl/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

finetune Llama-2-70B using 16 * A10( 16 * 23G). this is my gpus, 16 GPUs in one machine:
![image](https://github.com/OpenAccess-AI-Collective/axolotl/assets/74184102/c835d7a8-988d-4a89-98b9-9b211405d1fe)

 Maybe it need FSDP.

### ✔️ Solution

none

### ❓ Alternatives

none

### 📝 Additional Context

none

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by ehartford** [comment]
Yes, using qLoRA
