### ISSUE TITLE
No module named axolotl.utils.validation

### ISSUE THREAD

**Issue by kschoos** [axolotl-ai-cloud/axolotl#50]
After pip installing axolotl, and trying to run the provided finetuning command I get:

`Traceback (most recent call last):
  File "/home/someone/axolotl/scripts/finetune.py", line 17, in <module>
    from axolotl.utils.validation import validate_config
ModuleNotFoundError: No module named 'axolotl.utils.validation'`

Can't find validation.py anywhere in the commits either

**Comment by NanoCode012** [comment]
Closed by https://github.com/OpenAccess-AI-Collective/axolotl/pull/55
