### ISSUE TITLE
Trying to retrain on a model that was trained with rope scaling - getting "ValueError: `rope_scaling`'s factor field must be an float > 1, got 4"

### ISSUE THREAD

**Issue by enn-nafnlaus** [axolotl-ai-cloud/axolotl#544]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/OpenAccess-AI-Collective/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

Should continue training.

### Current behaviour

  File "/home/user/.local/lib/python3.10/site-packages/transformers/models/llama/configuration_llama.py", line 149, in __init__
    self._rope_scaling_validation()
  File "/home/user/.local/lib/python3.10/site-packages/transformers/models/llama/configuration_llama.py", line 181, in _rope_scaling_validation
    raise ValueError(f"`rope_scaling`'s factor field must be an float > 1, got {rope_scaling_factor}")
ValueError: `rope_scaling`'s factor field must be an float > 1, got 4

It is getting this from the model, not the yaml - in particular, I believe from the model's config.json:

{
  "_name_or_path": "openlm-research/open_llama_3b_v2",
  "architectures": [
    "LlamaForCausalLM"
  ],
  "bos_token_id": 1,
  "eos_token_id": 2,
  "hidden_act": "silu",
  "hidden_size": 3200,
  "initializer_range": 0.02,
  "intermediate_size": 8640,
  "max_position_embeddings": 8192,
  "model_type": "llama",
  "num_attention_heads": 32,
  "num_hidden_layers": 26,
  "num_key_value_heads": 32,
  "pad_token_id": 0,
  "pretraining_tp": 1,
  "rms_norm_eps": 1e-06,
  "rope_scaling": {
    "factor": 4,
    "type": "dynamic"
  },
  "tie_word_embeddings": false,
  "torch_dtype": "float16",
  "transformers_version": "4.31.0",
  "use_cache": false,
  "vocab_size": 32000
}

### Steps to reproduce

See above

### Possible solution

Line 172 of configuration_llama.py reads:

        rope_scaling_factor = self.rope_scaling.get("factor", None)

... but it has loaded that rope scaling factor as an int, not a float.  To fix this, it should read:

        rope_scaling_factor = float(self.rope_scaling.get("factor", None))

### Which Operating Systems are you using?

- [X] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.10

### axolotl branch-commit

commit 6c0886a9915f512cf655fc339cbec42766ce85b5

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by winglian** [comment]
Try setting 
```yaml
rope_scaling:
  factor: 4.0
  type: dynamic
```

4 gets interpreted by python as an int.

**Comment by enn-nafnlaus** [comment]
Yes, that 

> Try setting
> 
> ```yaml
> rope_scaling:
>   factor: 4.0
>   type: dynamic
> ```
> 
> 4 gets interpreted by python as an int.

Yes, that is a hack that gets past it.  But that's not the issue - axolotl wrote out that "4", not me. It wrote out something that it itself can't read.

**Comment by Napuh** [comment]
@enn-nafnlaus What's the model you are trying to finetune? Is it still failing?

**Comment by enn-nafnlaus** [comment]
Yes, and as mentioned, the model is one I trained in axolotl, which I'm then trying to use as a basis to train further.  That "factor: 4" was written out by axolotl.  But it can't then read it back in.  This is a problem.  If axolotl writes out a model, it should be able to read it back in!  :)  And the fix is very simple, and provided above.

**Comment by Napuh** [comment]
Is this still a problem in the current version of axolotl? That file you mention does not exist now, and I have not been able to reproduce the issue.
