### ISSUE TITLE
Error When Trying to Resume from Checkpoint: "No such file or directory: 'completed-model/checkpoint-600/pytorch_model_0/.metadata'"

### ISSUE THREAD

**Issue by jerryjalapeno** [axolotl-ai-cloud/axolotl#554]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/OpenAccess-AI-Collective/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

When enabling auto_resume_from_checkpoints in the configuration, I expect the model to resume training from the specified checkpoint without any issues.

### Current behaviour

When I attempt to resume from a checkpoint, I'm faced with a FileNotFoundError, specifically indicating that the '.metadata' file within the 'completed-model/checkpoint-600/pytorch_model_0/' directory cannot be found. This error seems consistent across ranks (from RANK 0 to RANK 4).

Error trace:
Traceback (most recent call last): (RANK 0)
  File ".../torch/distributed/checkpoint/utils.py", line 171, in reduce_scatter
    local_data = map_fun()
  ...
  File ".../torch/distributed/checkpoint/filesystem.py", line 511, in read_metadata
    with (self.path / ".metadata").open("rb") as metadata_file:
FileNotFoundError: [Errno 2] No such file or directory: 'completed-model/checkpoint-600/pytorch_model_0/.metadata'
...

I am training on a Runpod 8xA100 80GB instance, with Cuda version 11.7 and Torch 2.0.1. 

### Steps to reproduce

Clone the repository and set up the environment as per the provided instructions.

Modify the configuration to enable auto_resume_from_checkpoints:

yaml:
auto_resume_from_checkpoints: true

Begin training and allow the model to save a checkpoint.

Terminate the training process and attempt to resume from the previously saved checkpoint.

### Which Operating Systems are you using?

- [X] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.10

### axolotl branch-commit

main/c1921c9

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by NanoCode012** [comment]
Hello, sorry for checking in late. I was wondering if you got this solved? It would be appreciated if you would attach yaml if you still get this issue.

**Comment by jerryjalapeno** [comment]
The issue was with transformers library itself, they fixed it already. Thanks
