### ISSUE TITLE
please add type: sharegpt:chatml

### ISSUE THREAD

**Issue by ehartford** [axolotl-ai-cloud/axolotl#560]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/OpenAccess-AI-Collective/axolotl/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/OpenAccess-AI-Collective/axolotl/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

Please add support for `type: sharegpt:chatml`

```ValueError: unsupported prompt_style for ShareGPTPrompter(chatml)```

https://github.com/OpenAccess-AI-Collective/axolotl/blob/2f586d18dbf89189834a2bd8815f93011b435b25/src/axolotl/prompters.py#L291

### ✔️ Solution

Please add support for `type: sharegpt:chatml`

```ValueError: unsupported prompt_style for ShareGPTPrompter(chatml)```

https://github.com/OpenAccess-AI-Collective/axolotl/blob/2f586d18dbf89189834a2bd8815f93011b435b25/src/axolotl/prompters.py#L291

### ❓ Alternatives

Please add support for `type: sharegpt:chatml`

```ValueError: unsupported prompt_style for ShareGPTPrompter(chatml)```

https://github.com/OpenAccess-AI-Collective/axolotl/blob/2f586d18dbf89189834a2bd8815f93011b435b25/src/axolotl/prompters.py#L291

### 📝 Additional Context

Please add support for `type: sharegpt:chatml`

```ValueError: unsupported prompt_style for ShareGPTPrompter(chatml)```

https://github.com/OpenAccess-AI-Collective/axolotl/blob/2f586d18dbf89189834a2bd8815f93011b435b25/src/axolotl/prompters.py#L291

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by NanoCode012** [comment]
This is now possible via:

```yml
datasets:
  - path: 
    type: sharegpt
    conversation: chatml
```

Also mentioned here: https://discordapp.com/channels/1104757954588196865/1104758010959634503/1158762774147633173
