### ISSUE TITLE
Dataset merging in axolotl

### ISSUE THREAD

**Issue by adarshxs** [axolotl-ai-cloud/axolotl#573]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/OpenAccess-AI-Collective/axolotl/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/OpenAccess-AI-Collective/axolotl/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

As suggested, can there be anyway where we pass in multiple datasets, and have the functionality to fine tune? 

### ✔️ Solution

add dataset1+dataset2 = big dataset lmao

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by adarshxs** [comment]
for eg:
I would like to merge both:
> Open-Orca/OpenOrca 
> garage-bAInd/Open-Platypus

and then run a fine tuning job

**Comment by winglian** [comment]
This already exists:
```yaml
datasets:
  - path: ...
    type: ...
  - path: ...
    type: ...
```

**Comment by adarshxs** [comment]
ah sorry my bad
