### ISSUE TITLE
Quickstart does not work on google colab with GPU instance Paid and free

### ISSUE THREAD

**Issue by RitvikShandilya** [axolotl-ai-cloud/axolotl#627]
### What piece of documentation is affected?

I'm getting this error while running the quickstart commands: The following values were not passed to `accelerate launch` and had defaults used instead:
	`--num_processes` was set to a value of `1`
	`--num_machines` was set to a value of `1`
	`--mixed_precision` was set to a value of `'no'`
	`--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
/usr/bin/python3: Error while finding module specification for 'axolotl.cli.train' (ModuleNotFoundError: No module named 'axolotl.cli')
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 986, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'axolotl.cli.train', 'examples/openllama-3b/lora.yml']' returned non-zero exit status 1.

colab link for quick check: https://colab.research.google.com/drive/1cFqQFc4JfJu_0uZAHcHZgFy0ryO6tPev?usp=sharing

### What part(s) of the article would you like to see updated?

A quickstart for colab needs to be added

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by Napuh** [comment]
You are changing directories wrong in Colab.

See [this](https://stackoverflow.com/questions/48298146/changing-directory-in-google-colab-breaking-out-of-the-python-interpreter), and once you change the `!cd` to `%cd`, the notebook works and the model should train fine. 
Bear in mind free Colab has T4 GPU's, so some things may not work as expected, like flash-attn (not supported for GPU's <Ampere)

**Comment by winglian** [comment]
Thanks @Napuh ! I did a quick check and can confirm that `!cd axolotl` on it's own does not work as expected.

<img width="1453" alt="Screenshot 2023-09-23 at 6 37 27 PM" src="https://github.com/OpenAccess-AI-Collective/axolotl/assets/381258/ed3a75a9-ed30-4b1d-917e-1b7411bbd468">
<img width="1026" alt="Screenshot 2023-09-23 at 6 37 00 PM" src="https://github.com/OpenAccess-AI-Collective/axolotl/assets/381258/55040e74-07ab-4104-b70a-dbf06d1ed14d">

But, Napuh's recommendation of using `%cd` is probably the best way to handle this.
