### ISSUE TITLE
Error : "No module 'axolotl' found" for phi 1.5 finetuning on Ubuntu WSL

### ISSUE THREAD

**Issue by axel588** [axolotl-ai-cloud/axolotl#628]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/OpenAccess-AI-Collective/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

It should finetune phi 1.5 using my alpaca instruction dataset. Currently it just doesnt even start

### Current behaviour

( Note I have the extact same issue on windows 11 and ubuntu WSL 22.0 ), here this is on ubuntu WSL 22.0
I am using a virtuel environment, and followed quickstart installation which is :
```
git clone https://github.com/OpenAccess-AI-Collective/axolotl
cd axolotl

pip3 install packaging
pip3 install -e .[flash-attn,deepspeed]
pip3 install -U git+https://github.com/huggingface/peft.git
```

The current behaviour is the following :
```
The following values were not passed to accelerate launch and had defaults used instead:
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
/home/axel/training/superenv/bin/python3: Error while finding module specification for 'axolotl.cli.train' (ModuleNotFoundError: No module named 'axolotl')
Traceback (most recent call last):
  File "/home/axel/training/superenv/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/axel/training/superenv/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/home/axel/training/superenv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 986, in launch_command
    simple_launcher(args)
  File "/home/axel/training/superenv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/axel/training/superenv/bin/python3', '-m', 'axolotl.cli.train', 'examples/phi/phi-ft.yml', '--deepspeed', 'deepspeed/zero1.json']' returned non-zero exit status 1.
```

### Steps to reproduce

Just follow these steps on Ubuntu WSL 22 on windows 11:
1.
```
python -m venv newenv
cd newenv
chmod u+x ./bin/activate
source ./bin/activate
```

Then just do :
```
git clone https://github.com/OpenAccess-AI-Collective/axolotl
cd axolotl

pip3 install packaging
pip3 install -e .[flash-attn,deepspeed]
pip3 install -U git+https://github.com/huggingface/peft.git
```

Then run:
```accelerate launch -m axolotl.cli.train examples/phi/phi-ft.yml --deepspeed deepspeed/zero1.json```

### Possible solution

I dont have any idea, anyway a quickstart not working is always a bad signal

### Which Operating Systems are you using?

- [X] Linux
- [ ] macOS
- [X] Windows

### Python Version

3.10.12 (Ubuntu WSL) & 3.10.9 (Windows 11)

### axolotl branch-commit

main/67b98886306aba93232cb8766f95126566c23a9d

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by winglian** [comment]
Try with accelerate launch scripts/finetune.py...

**Comment by winglian** [comment]
Also, saying things like "anyway a quickstart not working is always a bad signal" comes off as passive aggressive. More than likely there is something wrong with your specific environment that we'd be happy to help you out with, but no need for the negativity. Thanks.

**Comment by winglian** [comment]
When running `pip3 install -e .[flash-attn,deepspeed]` what is the output from that command?

**Comment by axel588** [comment]
Sorry for the passive agressive,

I was extremely tired, and its the second project with failure with phi,
Maybe a more convenient way of developing project is using Github CI/CD for regression test, it helps a lot assuring the project stability and avoid package errors.

I will look into your proposition ths week end, thank your for your time anyway.
