### ISSUE TITLE
Discord link is not working - congrats on a great project!

### ISSUE THREAD

**Issue by duarteocarmo** [axolotl-ai-cloud/axolotl#635]
I wanted to tell you guys about [something](https://duarteocarmo.com/blog/fine-tune-llama-2-telegram) I recently built with axolotl. But your discord server link invite is not working. 

Congrats on a great project!!!!

**Comment by winglian** [comment]
@duarteocarmo Are you sure this link https://discord.gg/HhrNrHJPRb doesn't work?

**Comment by duarteocarmo** [comment]
@winglian  - yup

![image](https://github.com/OpenAccess-AI-Collective/axolotl/assets/26342344/aef87116-c6b9-454f-b7c2-606a85e251f6)

**Comment by winglian** [comment]
🤔 <img width="526" alt="Screenshot 2023-09-26 at 9 57 58 AM" src="https://github.com/OpenAccess-AI-Collective/axolotl/assets/381258/4a884ff7-e1fa-4441-bacf-3c6c630c44ac">
It's an unlimited joins/no expiration link.  Can you join from a mobile device maybe? Or try an incognito window?

**Comment by duarteocarmo** [comment]
Ah got it! Working now! Not sure what happened!
