### ISSUE TITLE
Support Qwen type llm's

### ISSUE THREAD

**Issue by CyberTimon** [axolotl-ai-cloud/axolotl#638]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/OpenAccess-AI-Collective/axolotl/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/OpenAccess-AI-Collective/axolotl/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

With the new qwen 14b model it would be very nice to have axolotl support.

### ✔️ Solution

-Support finetuning of Qwen type llm's

### ❓ Alternatives

Normal finetuning but it's unoptimized

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by NanoCode012** [comment]
Could you please try with `trust_remote_code: true` and using AutoModelCausalLM and AutoTokenizer? Is there an error?

**Comment by Peter-Devine** [comment]
I'd like to second this. `trust_remote_code: true` seems to work for full finetuning, but I get errors for qlora training. Is fully tested support for Qwen on the roadmap for this project? It would be really useful for CJK languages!

**Comment by CheshireAI** [comment]
I get errors:  raise ValueError("Adding unknown special tokens is not supported")
ValueError: Adding unknown special tokens is not supported
trying to use qlora with qwen

**Comment by kostum123** [comment]
Has anyone been able to fine-tune it with qlora?

**Comment by NanoCode012** [comment]
> I get errors: raise ValueError("Adding unknown special tokens is not supported") ValueError: Adding unknown special tokens is not supported trying to use qlora with qwen

@CheshireAI , Hm, this is an upstream problem. If you want this feature, you should ask at `transformers`.

@Peter-Devine @kostum123 , what's the error with running qlora?

**Comment by NanoCode012** [comment]
Hello, I apologize for the long delay. This should be fixed here: https://github.com/OpenAccess-AI-Collective/axolotl/pull/894

Please let me know how it goes.

**Comment by CyberTimon** [comment]
Thank you very much! Will try it out soon.
