### ISSUE TITLE
I've found "MAKEFLAGS="-j$(nproc)" pip3 install -e '.[flash-attn,deepspeed]'" is much faster if you need to build wheels for flash-attn the first time

### ISSUE THREAD

**Issue by l3utterfly** [axolotl-ai-cloud/axolotl#640]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/OpenAccess-AI-Collective/axolotl/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/OpenAccess-AI-Collective/axolotl/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

Update ReadMe.md to include this command when installing `axolotl`:

`MAKEFLAGS="-j$(nproc)" pip3 install -e '.[flash-attn,deepspeed]'`

I've found it to be much faster when you need to build flash-attn wheel from source as it utilises all CPUs.

### ✔️ Solution

Update ReadMe.md to include this command when installing `axolotl`:

`MAKEFLAGS="-j$(nproc)" pip3 install -e '.[flash-attn,deepspeed]'`

I've found it to be much faster when you need to build flash-attn wheel from source as it utilises all CPUs.

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by NanoCode012** [comment]
Please correct me if I'm wrong, but doesn't FA already build the binaries?
