### ISSUE TITLE
AttributeError: 'DatasetDict' object has no attribute 'features'

### ISSUE THREAD

**Issue by Phasor** [axolotl-ai-cloud/axolotl#653]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/OpenAccess-AI-Collective/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

The model should be fine tuned using my .yml file config.

### Current behaviour

I am running this on Colab. 

When I run:

```
!git clone https://github.com/OpenAccess-AI-Collective/axolotl
%cd axolotl

!pip3 install packaging
!pip3 install -e '.[flash-attn,deepspeed]'
!pip3 install -U git+https://github.com/huggingface/peft.git
```

and then try and train the model using a .yml file which uses a hugging face data set as follows:

`!accelerate launch -m axolotl.cli.train sql.yml`

I get the following error: 

`AttributeError: 'DatasetDict' object has no attribute 'features'`

### Steps to reproduce

On colab run:

```
!git clone https://github.com/OpenAccess-AI-Collective/axolotl
%cd axolotl

!pip3 install packaging
!pip3 install -e '.[flash-attn,deepspeed]'
!pip3 install -U git+https://github.com/huggingface/peft.git
```
Create a sql.yml file and upload it.

and then try and train the model using a .yml file using the HF data set (https://huggingface.co/datasets/knowrohit07/know_sql) as follows:

`!accelerate launch -m axolotl.cli.train sql.yml`

### Which Operating Systems are you using?

- [X] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.10

### axolotl branch-commit

!git clone https://github.com/OpenAccess-AI-Collective/axolotl

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by winglian** [comment]
@Phasor please see the linked pr that was closed. That should help.
