### ISSUE TITLE
Error in lora: Target module Dropout(p=0.05, inplace=False) is not supported. 

### ISSUE THREAD

**Issue by githubbar** [axolotl-ai-cloud/axolotl#657]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/OpenAccess-AI-Collective/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

Inference should run from examples

### Current behaviour

    raise ValueError(
ValueError: Target module Dropout(p=0.05, inplace=False) is not supported. Currently, only the following modules are supported: `torch.nn.Linear`, `torch.nn.Embedding`, `torch.nn.Conv2d`, `transformers.pytorch_utils.Conv1D`.
        new_module = self._create_new_module(lora_config, adapter_name, target, **kwargs)
  File "/N/u/oleykin/BigRed200/.local/lib/python3.9/site-packages/peft/tuners/lora/model.py", line 331, in _create_new_module
self._create_and_replace(peft_config, adapter_name, target, target_name, parent, **optional_kwargs)
  File "/N/u/oleykin/BigRed200/.local/lib/python3.9/site-packages/peft/tuners/lora/model.py", line 217, in _create_and_replace
    raise ValueError(
ValueError: Target module Dropout(p=0.05, inplace=False) is not supported. Currently, only the following modules are supported: `torch.nn.Linear`, `torch.nn.Embedding`, `torch.nn.Conv2d`, `transformers.pytorch_utils.Conv1D`.
    new_module = self._create_new_module(lora_config, adapter_name, target, **kwargs)
  File "/N/u/oleykin/BigRed200/.local/lib/python3.9/site-packages/peft/tuners/lora/model.py", line 331, in _create_new_module
    raise ValueError(
ValueError: Target module Dropout(p=0.05, inplace=False) is not supported. Currently, only the following modules are supported: `torch.nn.Linear`, `torch.nn.Embedding`, `torch.nn.Conv2d`, `transformers.pytorch_utils.Conv1D`.
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 113389 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 113388) of binary: /N/u/oleykin/BigRed200/.conda/envs/axolotl/bin/python3.9

### Steps to reproduce

1. use lora.yml from examples
2. run inference accelerate launch --multi_gpu --num_processes=4 --num_machines=1 --mixed_precision='no' --dynamo_backend='no' --module axolotl.cli.inference lora.yml --base_model="mymodel"	

### Which Operating Systems are you using?

- [X] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.9

### axolotl branch-commit

main/5b0bc48

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by NanoCode012** [comment]
Could you share your yaml?

**Comment by winglian** [comment]
I think what's happening is that when inferencing on the lora, you don't want to specify the base_model, but the `--lora_model_dir=...`

**Comment by githubbar** [comment]
So, how do I change my yaml (pasted below)? Thanks!

----------------------
base_model: NousResearch/Llama-2-7b-hf
base_model_config: NousResearch/Llama-2-7b-hf
model_type: LlamaForCausalLM
tokenizer_type: LlamaTokenizer
is_llama_derived_model: true
hub_model_id: AdvertLlama-7b

load_in_8bit: true
load_in_4bit: false
strict: false

datasets:
  - path: rossiter_chapter1.json
    type: completion
dataset_prepared_path: last_run_prepared
val_set_size: 0.01
output_dir: ./lora-out

sequence_len: 4096
sample_packing: true
pad_to_sequence_len: true

adapter: lora
lora_r: 32
lora_alpha: 16
lora_dropout: 0.05
lora_target_linear: true
lora_model_dir:
lora_fan_in_fan_out:

wandb_project: AdvertLlama
wandb_entity:
wandb_watch:
wandb_run_id:
wandb_log_model:

gradient_accumulation_steps: 4
micro_batch_size: 2
num_epochs: 30
optimizer: adamw_bnb_8bit
lr_scheduler: cosine
learning_rate: 0.0002

train_on_inputs: false
group_by_length: false
bf16: true
fp16: false
tf32: false

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true

warmup_steps: 10
eval_steps: 20
eval_table_size:
eval_table_max_new_tokens: 128
save_steps:
debug:
deepspeed:
weight_decay: 0.0
fsdp:
fsdp_config:
special_tokens:
  bos_token: "<s>"
  eos_token: "</s>"
  unk_token: "<unk>"

**Comment by githubbar** [comment]
Seems to work if I specify a model_dir instead of a yaml file.

**Comment by githubbar** [comment]
What if I want to run inference on a base model (to test against the finetuned)? The readme suggests "--base_model" switch, but I'm getting the above error?

**Comment by NanoCode012** [comment]
Could I clarify for the original problem if you mean that you've already trained a fine-tuned model and want to inference on that or just running against our default examples?

Secondly, to inference on a base model, you can just call 
```
CUDA_VISIBLE_DEVICES=0 python -m axolotl.cli.inference examples/your_config.yml
```

**Comment by githubbar** [comment]
> Could I clarify for the original problem if you mean that you've already trained a fine-tuned model and want to inference on that or just running against our default examples?
Yes, already trained a model and want to run inference. 

> Secondly, to inference on a base model, you can just call
> ```
> CUDA_VISIBLE_DEVICES=0 python -m axolotl.cli.inference examples/your_config.yml
> ```

What is the "--base_model" for in readme.md section about inference?

**Comment by NanoCode012** [comment]
@githubbar , `--base_model` just overrides the 
```yml
base_model: NousResearch/Llama-2-7b-hf
```
in your config. 

The meaning in that section is for fullfinetune. You would then load the fullfinetuned weights instead of the base model.

**Comment by githubbar** [comment]
Ok, thank you. The naming was a bit confusing :-)

**Comment by NanoCode012** [comment]
@githubbar , if there's any way you think it can be improved, please let us know or make a PR to help improve :)
