### ISSUE TITLE
[Question] Should inference instruction have stripped last new line?

### ISSUE THREAD

**Issue by NanoCode012** [axolotl-ai-cloud/axolotl#66]
https://github.com/OpenAccess-AI-Collective/axolotl/blob/bbfc333a0136bfcf3f2129986253a8141c6c64d5/scripts/finetune.py#L68-L71

The inference script requires typing enter to pass the input even it's only one line. The result is that a `\n` is appended to that line.

```python
>>> get_multi_line_input()
Give me an instruction (Ctrl + D to finish): 
test
'test\n'
```

Should this be changed to `instruction=instruction.strip('\n')`?

I am not sure about other prompting style, but for `completion`, we want the text to be continued `test is a word`. Instead of having a `\n` after the input `test\n is a word`.

An alternative solution would be to add strip inside of the `CompletionPrompter`.

**Comment by winglian** [comment]
sounds like a good idea.
