### ISSUE TITLE
Flash Attention 1 request

### ISSUE THREAD

**Issue by techar** [axolotl-ai-cloud/axolotl#676]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/OpenAccess-AI-Collective/axolotl/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/OpenAccess-AI-Collective/axolotl/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

I couldn't find how to enable flash attention 1. Is it possible? Can you add it?

### ✔️ Solution

I'd like to train faster on my T4 (ex models I'm running TinyLlama, Mistral, Phi-1.5.)

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by NanoCode012** [comment]
FA 1 has been deprecated in favor of FA2. Unfortunately, the only place for FA 1 would be in an older commit. However, that would not work with Mistral out of the box.

**Comment by adivoj** [comment]
Thanks 👍

**Comment by ehartford** [comment]
But it's not a huge change.
You could easily patch your local axolotl
