### ISSUE TITLE
Runpod template will loop endlessly if restarted

### ISSUE THREAD

**Issue by ghost** [axolotl-ai-cloud/axolotl#684]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/OpenAccess-AI-Collective/axolotl/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/OpenAccess-AI-Collective/axolotl/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

It gets stuck trying to clone axolotl to axolotl update and failing when the directory already exists. 

### ✔️ Solution

An if statement should be put in place that checks if the directory already exists and if so deletes it before trying to clone.

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by NanoCode012** [comment]
Could you please point out how to reproduce?

**Comment by ghost** [comment]
> Could you please point out how to reproduce?

All I did was restart the pod using the axolotl jupyter runpod template on runpod

**Comment by NanoCode012** [comment]
@cvinker , axolotl official image does not have Jupyter built in. Could you try the one on readme? There's a direct link.
