### ISSUE TITLE
weight tying

### ISSUE THREAD

**Issue by thistleknot** [axolotl-ai-cloud/axolotl#689]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/OpenAccess-AI-Collective/axolotl/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/OpenAccess-AI-Collective/axolotl/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

weight tying which is implemented in nanogpt merges some layers near the final output layer

https://arxiv.org/abs/1608.05859

reduces # of trainable parameter's and increases quality

### ✔️ Solution

https://arxiv.org/abs/1608.05859

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by thistleknot** [comment]
![Weight Tying 1695408221895](https://github.com/OpenAccess-AI-Collective/axolotl/assets/5154106/5958393a-130c-4173-8faa-ba88c78bf469)

**Comment by NanoCode012** [comment]
May I ask if this is what you mean?

https://github.com/OpenAccess-AI-Collective/axolotl/blob/d4a88e4eca44240b531b64ec9373bb7ac06a1bbb/src/axolotl/utils/models.py#L359-L362

`resize` function calls `tie_weights` internally.

**Comment by thistleknot** [comment]
maybe it is.  the technique is kind of old.  So I would be surprised if it wasn't implemented by transformers... but I wasn't sure.  Thanks.

**Comment by NanoCode012** [comment]
Closing this as completed. If there's anything missing, feel free to leave a comment.
