### ISSUE TITLE
Config validation should warn when full fine tune w load_in_*bit is used

### ISSUE THREAD

**Issue by winglian** [axolotl-ai-cloud/axolotl#717]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/OpenAccess-AI-Collective/axolotl/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/OpenAccess-AI-Collective/axolotl/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

full fine tunes in 8/4 bit is not supported, but we don't warn the user

### ✔️ Solution

add validation to warn

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by NanoCode012** [comment]
Solved in #770
