### ISSUE TITLE
Unusable early_stopping_patience param

### ISSUE THREAD

**Issue by Thytu** [axolotl-ai-cloud/axolotl#73]
Whenever user uses `early_stopping_patience` it results in the following error: `AssertionError: EarlyStoppingCallback requires load_best_model_at_end = True`

**Comment by NanoCode012** [comment]
Related to https://github.com/OpenAccess-AI-Collective/axolotl/issues/28 and this comment https://github.com/OpenAccess-AI-Collective/axolotl/issues/24#issuecomment-1541337225

**Comment by winglian** [comment]
commented on your pr. lmk if that sounds reasonable. https://github.com/OpenAccess-AI-Collective/axolotl/pull/74#issuecomment-1565424811

**Comment by NanoCode012** [comment]
Please use #28  for this problem.
