### ISSUE TITLE
ValueError: Using `fp8` precision requires `transformer_engine` to be installed.

### ISSUE THREAD

**Issue by thistleknot** [axolotl-ai-cloud/axolotl#760]
Fuller error

```
[2023-10-21 19:58:27,666] [INFO] [comm.py:662:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
Traceback (most recent call last):
  File "/data/axolotl/scripts/finetune.py", line 54, in <module>
    fire.Fire(do_cli)
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/data/axolotl/scripts/finetune.py", line 25, in do_cli
    print_axolotl_text_art()
  File "/data/axolotl/src/axolotl/cli/__init__.py", line 49, in print_axolotl_text_art
    if is_main_process():
  File "/data/axolotl/src/axolotl/utils/distributed.py", line 44, in is_main_process
    if not is_distributed():
  File "/data/axolotl/src/axolotl/utils/distributed.py", line 26, in is_distributed
    accelerate = Accelerator()
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/accelerate/accelerator.py", line 369, in __init__
    self.state = AcceleratorState(
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/accelerate/state.py", line 744, in __init__
    raise ValueError("Using `fp8` precision requires `transformer_engine` to be installed.")
ValueError: Using `fp8` precision requires `transformer_engine` to be installed.

```

### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/OpenAccess-AI-Collective/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

run finetune without asking me to install

### Current behaviour

unable to start training

### Steps to reproduce

                pip3 install packaging
                pip3 install -e '.[flash-attn,deepspeed]'
                pip3 install -U git+https://github.com/huggingface/peft.git
accelerate launch scripts/finetune.py examples/llama-2/tiny-llama.yml

### Config yaml

base_model: PY007/TinyLlama-1.1B-intermediate-step-480k-1T
base_model_config: PY007/TinyLlama-1.1B-intermediate-step-480k-1T

model_type: LlamaForCausalLM
tokenizer_type: LlamaTokenizer
is_llama_derived_model: true

load_in_8bit: false
load_in_4bit: true
strict: false
push_dataset_to_hub:
datasets:
  - path: /data/TrainLLMv3/responses/spo_open_qa/output.jsonl
    type:
      system_prompt: ""
      system_format: ""
      field_system:
      field_instruction: instruction
      field_input: input
      field_output: output

      format: |-
        ### Instruction: {instruction}
        ### Context: {input}
        ### Answer: 
      no_input_format: |-
        ### Instruction: {instruction}
        ### Answer: 
datasets:
  - path: /data/TrainLLMv3/responses/scientific_create_analogy/data-noid.jsonl
    type:
      system_prompt: "Perform a relation mapping task, which is a task to choose optimal combination of word pairs.  Relation mapping M is the set of bijective map in between two sets of terms (source and target)."
      system_format: ""
      field_system:
      field_instruction: reference
      field_input: source
      field_output: target

      format: |-
        ### System: {system_prompt}
        ### Reference: {reference}
        ### Source: {source}
        ### Target: 
      no_input_format: |-
        ### Source: {instruction}
        ### Target: 
datasets:
  - path: /data/TrainLLMv3/responses/spo_triplets/spo.jsonl
    type:
      system_prompt: ""
      system_format: ""
      field_system:
      field_instruction: instruction
      field_input: input
      field_output: output

      format: |-
        ### Instruction: {instruction}
        ### Context: {input}
        ### Answer: 
      no_input_format: |-
        ### Instruction: {instruction}
        ### Answer: 
datasets:
  - path: /data/TrainLLMv3/responses/databricks-dolly-15k/databricks-dolly-15k-nocat.jsonl
    type:
      system_prompt: ""
      system_format: ""
      field_system:
      field_instruction: instruction
      field_input: input
      field_output: output

      format: |-
        ### Instruction: {instruction}
        ### Context: {input}
        ### Answer: 
      no_input_format: |-
        ### Instruction: {instruction}
        ### Answer: 
dataset_prepared_path:
val_set_size: 0.01
output_dir: ./qlora-out

adapter: qlora
lora_model_dir:

sequence_len: 2048
sample_packing: true

adapter: qlora
lora_model_dir:
lora_r: 32
lora_alpha: 16
lora_dropout: 0.05
lora_target_modules:
lora_target_linear: true
lora_fan_in_fan_out:

wandb_project:
wandb_entity:
wandb_watch:
wandb_run_id:
wandb_log_model:

gradient_accumulation_steps: 4
micro_batch_size: 1
num_epochs: 3
optimizer: adamw_bnb_8bit
lr_scheduler: cosine
learning_rate: 0.0002

train_on_inputs: false
group_by_length: false
bf16: false
fp16: true
tf32: false

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true

warmup_steps: 10
eval_steps: 20
eval_table_size:
save_steps:
debug:
deepspeed:
weight_decay: 0.0
fsdp:
fsdp_config:
special_tokens:
  bos_token: "<s>"
  eos_token: "</s>"
  unk_token: "<unk>"

### Possible solution

it's an error thrown by accelerate is all I know

works on my rockyl linux 9 environment, but not on my oracle linux 8, both with same pytho 3.10.9

### Which Operating Systems are you using?

- [X] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.10.9

### axolotl branch-commit

15d3a654bfdc572a3bf44b9b0a74b47f8688d33c

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by casper-hansen** [comment]
How did you get FP8 to activate?

**Comment by thistleknot** [comment]
I have no idea.  I don't recall ever setting anything related to that.

**Comment by thistleknot** [comment]
```base_model: /data/text-generation-webui/models//TinyLlama-1.1B-intermediate-step-715k-1.5T

model_type: LlamaForCausalLM
tokenizer_type: LlamaTokenizer
is_llama_derived_model: true

load_in_8bit: false
load_in_4bit: true
strict: false
datasets:
  - path: /data/datasets/mine/orca_100.jsonl
    type:
      system_prompt: ""
      system_format: ""
      field_system:
      field_instruction: instruction
      field_input: input
      field_output: output
      format: |-
        ### System: {input}
        ### Instruction: {instruction}
        ### Answer: 
      no_input_format: |-
        ### Instruction: {instruction}
        ### Answer: 
      #format: "[INST]System:\n\n{input}\n\nInstruction:\n\n{instruction}\n\nAnswer:\n\n[/INST]"
      #no_input_format: "[INST]Instruction:\n\n{instruction}\n\nAnswer:\n\n[/INST]"
  - path: /home/user/datasets/mine/Philosophy.jsonl
    type: completion
  - path: /data/datasets/mine/spo.jsonl
    type:
      system_prompt: ""
      system_format: ""
      field_system:
      field_instruction: instruction
      field_input: input
      field_output: output
      format: |-
        ### Context: {input}
        ### Instruction: {instruction}
        ### Answer: 
      no_input_format: |-
        ### Instruction: {instruction}
        ### Answer: 
#      system_prompt: ""
#      field_system:
#      format: "[INST]Context:{input}\n\nInstruction:\n\n{instruction}\n\nAnswer:\n\n[/INST]"
  - path: /data/datasets/mine/aa.jsonl
    type:
      system_prompt: ""
      system_format: ""
      field_system:
      field_instruction: instruction
      field_input: input
      field_output: output
      format: |-
        ### Context: {input}
        ### Instruction: {instruction}
        ### Answer: 
      no_input_format: |-
        ### Instruction: {instruction}
        ### Answer: 
  - path: /data/datasets/mine/final_triplets.jsonl
    type:
      system_prompt: ""
      system_format: ""
      field_system:
      field_instruction: instruction
      field_input: input
      field_output: output
      format: |-
        ### Context: {input}
        ### Instruction: {instruction}
        ### Answer: 
      no_input_format: |-
        ### Instruction: {instruction}
        ### Answer: 
dataset_prepared_path:
val_set_size: 0.01
output_dir: ./qlora-out

sequence_len: 2048
sample_packing: true

adapter: qlora
lora_model_dir:
lora_r: 8
lora_alpha: 16
lora_dropout: 0.05
lora_target_linear: true
lora_fan_in_fan_out:
lora_bias: true
wandb_project:
wandb_entity:
wandb_watch:
wandb_run_id:
wandb_log_model:

gradient_accumulation_steps: 4
micro_batch_size: 2
num_epochs: 4
optimizer: paged_adamw_32bit
lr_scheduler: cosine
learning_rate: 0.002

train_on_inputs: false
group_by_length: false
bf16: false
fp16: true
tf32: false

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: false

warmup_steps: 10
eval_steps: 686
eval_table_size:
save_steps: 686
debug:
#deepspeed: false
weight_decay: 0.0
fsdp:
fsdp_config:
special_tokens:
  bos_token: "<s>"
  eos_token: "</s>"
  unk_token: "<unk>"

```

**Comment by thistleknot** [comment]
nano +26 /data/axolotl/src/axolotl/utils/distributed.py

if I do
![image](https://github.com/OpenAccess-AI-Collective/axolotl/assets/5154106/5695873c-ea28-4c40-b69d-1e1da09d8f34)

I can get past the error

**Comment by thistleknot** [comment]
apparently when I run the code from /data/dev/axolotl, it references /data/axolotl/src instead of /data/dev/axolotl/src

which has been causing me no end of confusion (I guess I need to install from the dev path)

**Comment by thistleknot** [comment]
the error happens here
  File "/data/dev/axolotl/src/axolotl/core/trainer_builder.py", line 670, in build
    trainer = trainer_cls(
  File "/data/dev/axolotl/src/axolotl/core/trainer_builder.py", line 117, in init
    super().init(*args, **kwargs)
  File "/root/miniconda3/envs/axolotyl/lib/python3.10/site-packages/transformers/trainer.py", line 347, in init
    self.create_accelerator_and_postprocess()
  File "/root/miniconda3/envs/axolotyl/lib/python3.10/site-packages/transformers/trainer.py", line 3981, in create_accelerator_and_postprocess
    self.accelerator = Accelerator(
  File "/root/miniconda3/envs/axolotyl/lib/python3.10/site-packages/accelerate/accelerator.py", line 369, in init
    self.state = AcceleratorState(
  File "/root/miniconda3/envs/axolotyl/lib/python3.10/site-packages/accelerate/state.py", line 744, in init
    raise ValueError("Using fp8 precision requires transformer_engine to be installed.")

with kwargs or args... when the trainer is called

**Comment by thistleknot** [comment]
if I modiff accelerator(mixed_precision="no")
I get
```
ValueError: Please correct the following DeepSpeed config values that mismatch TrainingArguments values:
- ds gradient_accumulation_steps=32 vs hf gradient_accumulation_steps=1
The easiest method is to set these DeepSpeed config values to 'auto'.

```

**Comment by thistleknot** [comment]
run accelerate config and just configure
