### ISSUE TITLE
Support tensorboard

### ISSUE THREAD

**Issue by ein-ich** [axolotl-ai-cloud/axolotl#763]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/OpenAccess-AI-Collective/axolotl/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/OpenAccess-AI-Collective/axolotl/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

Support tensorboard as an alternative to wandb.

### ✔️ Solution

Before I started using axolotl I swore never to use wandb again. Needs access to server, annoying retry loop that sometimes breaks, doesn't log all steps and misses spikes. I was just reminded that I'd like to use tensorboard when it couldn't save the trained model because no memory left on device (wandb .cache folder is 500GB).

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by NanoCode012** [comment]
It should be as simple as adding a config for that:

https://github.com/OpenAccess-AI-Collective/axolotl/blob/21cf09b60840ee03ba3ee4e57c2707d2296f532c/src/axolotl/utils/trainer.py#L691

`report_to="tensorboard"`

or alternatively, we can set it to default to `tensorboard` if not using wandb.

**Comment by NanoCode012** [comment]
@ein-ich , could you please try #768 if it helps for you?

**Comment by ein-ich** [comment]
Thank you, I'll try it tomorrow.
