### ISSUE TITLE
Example `examples/openllama-3b/lora.yml` crashes with SIGTERM 15.

### ISSUE THREAD

**Issue by davidleejy** [axolotl-ai-cloud/axolotl#779]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/OpenAccess-AI-Collective/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

Example should exit gracefully?

### Current behaviour

The example `accelerate launch -m axolotl.cli.train examples/openllama-3b/lora.yml` crashes with SIGTERM 15. 

stdout output:
```
[... earlier output omitted ...]

{'loss': 1.2015, 'learning_rate': 0.00019993832553916283, 'epoch': 0.05}       
{'loss': 1.2385, 'learning_rate': 0.00019993782921867346, 'epoch': 0.05}       
{'loss': 0.8851, 'learning_rate': 0.0001999373309097499, 'epoch': 0.05}        
{'loss': 1.2749, 'learning_rate': 0.00019993683061240205, 'epoch': 0.05}       
  1%|▍                                   | 272/22292 [03:40<4:26:46,  1.38it/s]Traceback (most recent call last):
  File "/home/david/miniconda3/envs/axo3/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/david/miniconda3/envs/axo3/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/home/david/miniconda3/envs/axo3/lib/python3.10/site-packages/accelerate/commands/launch.py", line 986, in launch_command
    simple_launcher(args)
  File "/home/david/miniconda3/envs/axo3/lib/python3.10/site-packages/accelerate/commands/launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/david/miniconda3/envs/axo3/bin/python', '-m', 'axolotl.cli.train', 'examples/openllama-3b/lora.yml']' died with <Signals.SIGTERM: 15>.
```

### Steps to reproduce

Run `accelerate launch -m axolotl.cli.train examples/openllama-3b/lora.yml`

### Which Operating Systems are you using?

- [X] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.10

### axolotl branch-commit

main

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by NanoCode012** [comment]
Would you be able to try the Docker container? Is this single gpu or multi?

**Comment by davidleejy** [comment]
Hey hello there, thanks for weighing in. 

My current situation has me logging into what I believe to be a virtual machine equipped with a single GPU.

Would you happen to be able to share why using a Docker container might help?

**Comment by NanoCode012** [comment]
@davidleejy , ah, usually, docker container would rule out env issue.

> My current situation has me logging into what I believe to be a virtual machine equipped with a single GPU.

Is this local or cloud?

**Comment by winglian** [comment]
The host is probably killing the process for some unknown reason that doesn't get exposed in the VM. if using a cloud GPU service, you may want to consider a different provider. Can you provide any additional details about your setup/cloud service? We can't help more without that.

**Comment by NanoCode012** [comment]
Closing as this can be a machine issue.
