### ISSUE TITLE
flash_attn ImportError

### ISSUE THREAD

**Issue by kelsey-um** [axolotl-ai-cloud/axolotl#784]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/OpenAccess-AI-Collective/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

I'm trying to fine-tune the Mistral model using the example script on the free tier of Google Colab.

### Current behaviour

Getting the following error related to flash attention

```
The following values were not passed to `accelerate launch` and had defaults used instead:
	`--num_processes` was set to a value of `1`
	`--num_machines` was set to a value of `1`
	`--mixed_precision` was set to a value of `'no'`
	`--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
2023-10-25 15:38:42.945005: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-10-25 15:38:42.945068: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-10-25 15:38:42.948363: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-10-25 15:38:45.475489: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/content/axolotl/axolotl/src/axolotl/cli/__init__.py", line 21, in <module>
    from axolotl.common.cli import TrainerCliArgs, load_model_and_tokenizer
  File "/content/axolotl/axolotl/src/axolotl/common/cli.py", line 11, in <module>
    from axolotl.utils.models import load_model, load_tokenizer
  File "/content/axolotl/axolotl/src/axolotl/utils/models.py", line 10, in <module>
    from optimum.bettertransformer import BetterTransformer
  File "/usr/local/lib/python3.10/dist-packages/optimum/bettertransformer/__init__.py", line 14, in <module>
    from .models import BetterTransformerManager
  File "/usr/local/lib/python3.10/dist-packages/optimum/bettertransformer/models/__init__.py", line 17, in <module>
    from .decoder_models import (
  File "/usr/local/lib/python3.10/dist-packages/optimum/bettertransformer/models/decoder_models.py", line 38, in <module>
    from transformers.models.llama.modeling_llama import LlamaAttention
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/llama/modeling_llama.py", line 45, in <module>
    from flash_attn import flash_attn_func, flash_attn_varlen_func
  File "/usr/local/lib/python3.10/dist-packages/flash_attn/__init__.py", line 3, in <module>
    from flash_attn.flash_attn_interface import (
  File "/usr/local/lib/python3.10/dist-packages/flash_attn/flash_attn_interface.py", line 8, in <module>
    import flash_attn_2_cuda as flash_attn_cuda
ImportError: /usr/local/lib/python3.10/dist-packages/flash_attn_2_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c104cuda9SetDeviceEi
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 33, in <module>
    sys.exit(load_entry_point('accelerate==0.24.0.dev0', 'console_scripts', 'accelerate')())
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 986, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'axolotl.cli.train', '/content/axolotl/examples/mistral/config.yml']' returned non-zero exit status 1.
``` 

### Steps to reproduce

Run the example script of the Mistral model

```
!accelerate launch -m axolotl.cli.train /content/axolotl/examples/mistral/config.yml
```

### Config yaml

Same as the one at examples/mistral/config.yml

### Possible solution

 Saw someone else with an issue with flash attention and the solution was to use Docker but this is not available on Colab.

### Which Operating Systems are you using?

- [ ] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.10.12

### axolotl branch-commit

main/20aa4b5

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by kostum123** [comment]
same

**Comment by dongxiaolong** [comment]
> ### Please check that this issue hasn't been reported before.
> * [x]  I searched previous [Bug Reports](https://github.com/OpenAccess-AI-Collective/axolotl/labels/bug) didn't find any similar reports.
> 
> ### Expected Behavior
> I'm trying to fine-tune the Mistral model using the example script on the free tier of Google Colab.
> 
> ### Current behaviour
> Getting the following error related to flash attention
> 
> ```
> The following values were not passed to `accelerate launch` and had defaults used instead:
> 	`--num_processes` was set to a value of `1`
> 	`--num_machines` was set to a value of `1`
> 	`--mixed_precision` was set to a value of `'no'`
> 	`--dynamo_backend` was set to a value of `'no'`
> To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
> 2023-10-25 15:38:42.945005: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
> 2023-10-25 15:38:42.945068: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
> 2023-10-25 15:38:42.948363: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
> 2023-10-25 15:38:45.475489: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
> Traceback (most recent call last):
>   File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
>     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
>   File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
>     __import__(pkg_name)
>   File "/content/axolotl/axolotl/src/axolotl/cli/__init__.py", line 21, in <module>
>     from axolotl.common.cli import TrainerCliArgs, load_model_and_tokenizer
>   File "/content/axolotl/axolotl/src/axolotl/common/cli.py", line 11, in <module>
>     from axolotl.utils.models import load_model, load_tokenizer
>   File "/content/axolotl/axolotl/src/axolotl/utils/models.py", line 10, in <module>
>     from optimum.bettertransformer import BetterTransformer
>   File "/usr/local/lib/python3.10/dist-packages/optimum/bettertransformer/__init__.py", line 14, in <module>
>     from .models import BetterTransformerManager
>   File "/usr/local/lib/python3.10/dist-packages/optimum/bettertransformer/models/__init__.py", line 17, in <module>
>     from .decoder_models import (
>   File "/usr/local/lib/python3.10/dist-packages/optimum/bettertransformer/models/decoder_models.py", line 38, in <module>
>     from transformers.models.llama.modeling_llama import LlamaAttention
>   File "/usr/local/lib/python3.10/dist-packages/transformers/models/llama/modeling_llama.py", line 45, in <module>
>     from flash_attn import flash_attn_func, flash_attn_varlen_func
>   File "/usr/local/lib/python3.10/dist-packages/flash_attn/__init__.py", line 3, in <module>
>     from flash_attn.flash_attn_interface import (
>   File "/usr/local/lib/python3.10/dist-packages/flash_attn/flash_attn_interface.py", line 8, in <module>
>     import flash_attn_2_cuda as flash_attn_cuda
> ImportError: /usr/local/lib/python3.10/dist-packages/flash_attn_2_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c104cuda9SetDeviceEi
> Traceback (most recent call last):
>   File "/usr/local/bin/accelerate", line 33, in <module>
>     sys.exit(load_entry_point('accelerate==0.24.0.dev0', 'console_scripts', 'accelerate')())
>   File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/accelerate_cli.py", line 47, in main
>     args.func(args)
>   File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 986, in launch_command
>     simple_launcher(args)
>   File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 628, in simple_launcher
>     raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
> subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'axolotl.cli.train', '/content/axolotl/examples/mistral/config.yml']' returned non-zero exit status 1.
> ```
> 
> ### Steps to reproduce
> Run the example script of the Mistral model
> 
> ```
> !accelerate launch -m axolotl.cli.train /content/axolotl/examples/mistral/config.yml
> ```
> 
> ### Config yaml
> Same as the one at examples/mistral/config.yml
> 
> ### Possible solution
> Saw someone else with an issue with flash attention and the solution was to use Docker but this is not available on Colab.
> 
> ### Which Operating Systems are you using?
> * [ ]  Linux
> * [ ]  macOS
> * [ ]  Windows
> 
> ### Python Version
> 3.10.12
> 
> ### axolotl branch-commit
> main/20aa4b5
> 
> ### Acknowledgements
> * [x]  My issue title is concise, descriptive, and in title casing.
> * [x]  I have searched the existing issues to make sure this bug has not been reported yet.
> * [x]  I am using the latest version of axolotl.
> * [x]  I have provided enough information for the maintainers to reproduce and diagnose the issue.

flash_attn can only be used on certain versions of the gpu. Check your environment.

**Comment by winglian** [comment]
This can be resolved by uninstalling flash-attn and reinstalling the latest flash-attn
