### ISSUE TITLE
Add Suport for mlflow

### ISSUE THREAD

**Issue by AmgadHasan** [axolotl-ai-cloud/axolotl#790]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/OpenAccess-AI-Collective/axolotl/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/OpenAccess-AI-Collective/axolotl/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

It would be great to add support to MLFlow for experiment tracking and model versioning.

### ✔️ Solution

It would be great to add support to MLFlow for experiment tracking and model versioning.

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by AmgadHasan** [comment]
Can someone point me to where I should add the mlflow support in the code?

**Comment by JohanWork** [comment]
Hi sorry haven't seen this. I have started adding mlflow see this merged [pr](https://github.com/OpenAccess-AI-Collective/axolotl/commit/090c24dcb08bf3a751efb4a19bbf29f59f4a193e) and this [pr](https://github.com/OpenAccess-AI-Collective/axolotl/pull/1125). Feel free to take a look and help out or test it :)

**Comment by NanoCode012** [comment]
The PR has been merged. Thanks Johan!
