### ISSUE TITLE
[Feature] Add tests

### ISSUE THREAD

**Issue by NanoCode012** [axolotl-ai-cloud/axolotl#80]
We need to also think about adding some tests to ensure more stability. I do not have much experience on the matter, however, I think at the very least, we should test the following:

Functional
- [x] Test `validate_config` for conflicting configs

End to end for each architecture in Readme for one or two global_step:
- [ ] fp16/fp32
- [ ] 4bit
- [ ] 8bit
- [ ] gptq

**Comment by winglian** [comment]
https://github.com/huggingface/peft/blob/main/tests/test_adaption_prompt.py#L62-L72 has examples of creating small models ad hoc for tests

**Comment by winglian** [comment]
we've added e2e tests now
