### ISSUE TITLE
Include UltraChat format

### ISSUE THREAD

**Issue by Haoxiang-Wang** [axolotl-ai-cloud/axolotl#815]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/OpenAccess-AI-Collective/axolotl/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/OpenAccess-AI-Collective/axolotl/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

UltraChat is a new high-quality dataset that is used to train the SoTA 7B model, [Zephyr beta](https://huggingface.co/HuggingFaceH4/zephyr-7b-beta).

https://huggingface.co/datasets/stingning/ultrachat
https://huggingface.co/datasets/HuggingFaceH4/ultrachat_200k

I believe tt would attract more users if `axolotl` can include UltraChat format for fine-tuning. 

### ✔️ Solution

UltraChat is just multi-round ChatGPT conversations. Should be easy to integrate into the current repo.

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by Haoxiang-Wang** [comment]
Since UltraChat is multi-round conversation data, I think it's best to convert it to ShareGPT format. I am trying to convert https://huggingface.co/datasets/stingning/ultrachat to ShareGPT format. Will update in this thread.

**Comment by ehartford** [comment]
> Since UltraChat is multi-round conversation data, I think it's best to convert it to ShareGPT format. I am trying to convert https://huggingface.co/datasets/stingning/ultrachat to ShareGPT format. Will update in this thread.

Please note that ultrachat has a lot of bad data

1) empty questions or responses
2) questions that seem like responses instead of questions
3) questions that are nonsense
4) answers that are nonsense
5) conversations that have missing turns
6) refusals
7) questions that are malformed or truncated

I highly recommend filtering this dataset for quality while you are converting it.

**Comment by Haoxiang-Wang** [comment]
> > Since UltraChat is multi-round conversation data, I think it's best to convert it to ShareGPT format. I am trying to convert https://huggingface.co/datasets/stingning/ultrachat to ShareGPT format. Will update in this thread.
> 
> Please note that ultrachat has a lot of bad data
> 
> 1. empty questions or responses
> 2. questions that seem like responses instead of questions
> 3. questions that are nonsense
> 4. answers that are nonsense
> 5. conversations that have missing turns
> 6. refusals
> 7. questions that are malformed or truncated
> 
> I highly recommend filtering this dataset for quality while you are converting it.

Thank you @ehartford for letting me know about these tricky issues of UltraChat! I indeed found some empty responses.

**Comment by Haoxiang-Wang** [comment]
I realise it is pretty easy to reformat UltraChat to the ShareGPT format. One can simply apply the following function to each sample and then write the data into a JSON file. 
```python
def reformat_sample(sample):
    new_sample = {'id': sample['id']}
    conversation = []
    roles = ['human', 'gpt']
    for i, sentence in enumerate(sample['data']):
        role = roles[i % 2]
        conversation.append({"from":role, "value": sentence})
    new_sample['conversations'] = conversation
    return new_sample
```

**Comment by gardner** [comment]
This may be of interest: https://github.com/OpenAccess-AI-Collective/axolotl/commit/ba043a361e233d53fa82348ccaf6e3d7f13ee5c6

It appears ultrachat datasets can now be used in a similar fashion to `sharegpt.load_role` as described in the [README.md](https://github.com/OpenAccess-AI-Collective/axolotl/blob/main/README.md)
