### ISSUE TITLE
VRAM usage significantly higher when sample_packing=True

### ISSUE THREAD

**Issue by kallewoof** [axolotl-ai-cloud/axolotl#849]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/OpenAccess-AI-Collective/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

The VRAM usage when running with sample_packing=True should not be affected.

### Current behaviour

The trainer runs out of VRAM in `flash_attn_cuda.varlen_bwd()` inside flash_attn:
```
  File "...python3.11/site-packages/flash_attn/flash_attn_interface.py", line 165, in _flash_attn_varlen_backward
    dq, dk, dv, softmax_d, = flash_attn_cuda.varlen_bwd(
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 8.81 GiB (GPU 1; 23.68 GiB total capacity; 14.97 GiB already allocated; 7.56 GiB free; 15.71 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```
It appears to want an additional 8.8 GB of VRAM on GPU 1, suggesting it needs over ~32 GB of VRAM, whereas the trainer is able to train on the same hardware with sample_packing=False.

The crash only happens when the sample is filling up the context (4096 tokens, in this case). Running with sample_packing=False with samples at 4096 tokens does not trigger the OOM crash.

It crashes with LoRA rank 32, whereas it can do LoRA rank 64 with sample_packing=False without OOMing.

### Steps to reproduce

Use provided yml and dataset can anything. If checking for no crash on sample_packing=false, it must have 4096+ token entries.

Running on dual 3090 ti in linux.

### Config yaml

base_model: chargoddard/Yi-34B-Llama
model_type: LlamaForCausalLM
tokenizer_type: LlamaTokenizer
tokenizer_padding_side: left
is_llama_derived_model: true

load_in_8bit: false
load_in_4bit: true
strict: false
device_map: auto

datasets:
[... some dataset with 4096+ token entries...]

adapter: qlora
sequence_len: 4096

sample_packing: false # true = boom
pad_to_sequence_len: true

lora_r: 64
lora_alpha: 32
lora_dropout: 0.0
lora_target_modules:
lora_target_linear: true
lora_fan_in_fan_out:

gradient_accumulation_steps: 1
micro_batch_size: 1
num_epochs: 1
optimizer: paged_adamw_32bit
lr_scheduler: cosine
learning_rate: 0.0002

train_on_inputs: true
group_by_length: false
bf16: true
fp16: false
tf32: false

gradient_checkpointing: true
early_stopping_patience:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true
safe_serialization: true

warmup_steps: 5
eval_steps: 32
eval_table_size:
save_steps: 32
debug:
deepspeed:
weight_decay: 0.0
fsdp:
fsdp_config:
special_tokens:
  bos_token: "<s>"
  eos_token: "</s>"
  unk_token: "<unk>"

### Which Operating Systems are you using?

- [X] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.10.12

### axolotl branch-commit

main/1a6309c8a633a6fe17b2ffebbbc0353565f376e5

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by winglian** [comment]
I would fully expect a 34B model to OOM with qlora on 24GB VRAM. Keep in mind, the default configuration is data parallel, so a copy of each 34B model parameters are loaded on each GPU.

**Comment by winglian** [comment]
qq, are you launching this with accelerate or python? if you use `device_map: auto`, I assume you're trying to do model parallel, in which case you only want a single process, so should be using `python -m axolotl.cli.train ...`

**Comment by kallewoof** [comment]
I have 2x3090 ti cards (48 GB VRAM). I am launching with `python -m`, not accelerate. The `device_map` part is leftover from before. Will try without it and see if it makes a difference.

Edit: no change. Crashes as soon as it hits a 4096 token sample.

**Comment by NanoCode012** [comment]
Was wondering if you've tried deepspeed as shown on readme? use accelerate for launch

**Comment by kallewoof** [comment]
> Was wondering if you've tried deepspeed as shown on readme? use accelerate for launch

Whenever I use accelerate launch it tries to load the whole model on each card. Is there a way to make it split the model over the cards with accelerate launch?

**Comment by NanoCode012** [comment]
@kallewoof  this should help https://github.com/OpenAccess-AI-Collective/axolotl#deepspeed

**Comment by kallewoof** [comment]
> @kallewoof this should help https://github.com/OpenAccess-AI-Collective/axolotl#deepspeed

I tried zero1, 2, and 3. It OOMs on all of them. It is also using ~15 GB of VRAM on each GPU, which to me indicates it is loading the entire model on both cards. (4-bit 34B should be ~17 GB in total -- it is using over 30 GB during checkpoint shard loading):

```
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:42<00:00,  6.04s/it]
[2023-11-16 13:04:04,595] [INFO] [axolotl.load_model:414] [PID:188792] [RANK:0] GPU memory usage after model load: 19.653GB (+0.362GB cache, +2.174GB misc)
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/user/workspace/axolotl/src/axolotl/cli/train.py", line 38, in <module>
    fire.Fire(do_cli)
  File "/home/user/workspace/miniconda3/envs/axolotl/lib/python3.11/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/workspace/miniconda3/envs/axolotl/lib/python3.11/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "/home/user/workspace/miniconda3/envs/axolotl/lib/python3.11/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/workspace/axolotl/src/axolotl/cli/train.py", line 34, in do_cli
    train(cfg=parsed_cfg, cli_args=parsed_cli_args, dataset_meta=dataset_meta)
  File "/home/user/workspace/axolotl/src/axolotl/train.py", line 62, in train
    model, peft_config = load_model(cfg, tokenizer, inference=cli_args.inference)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/workspace/axolotl/src/axolotl/utils/models.py", line 425, in load_model
    module.to(torch.float32)
  File "/home/user/workspace/miniconda3/envs/axolotl/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1145, in to
    return self._apply(convert)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/user/workspace/miniconda3/envs/axolotl/lib/python3.11/site-packages/torch/nn/modules/module.py", line 820, in _apply
    param_applied = fn(param)
                    ^^^^^^^^^
  File "/home/user/workspace/miniconda3/envs/axolotl/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.71 GiB (GPU 0; 23.68 GiB total capacity; 20.51 GiB already allocated; 965.75 MiB free; 20.87 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 188793 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 188792) of binary: /home/user/workspace/miniconda3/envs/axolotl/bin/python
Traceback (most recent call last):
  File "/home/user/workspace/miniconda3/envs/axolotl/bin/accelerate", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/user/workspace/miniconda3/envs/axolotl/lib/python3.11/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/home/user/workspace/miniconda3/envs/axolotl/lib/python3.11/site-packages/accelerate/commands/launch.py", line 985, in launch_command
    multi_gpu_launcher(args)
  File "/home/user/workspace/miniconda3/envs/axolotl/lib/python3.11/site-packages/accelerate/commands/launch.py", line 654, in multi_gpu_launcher
    distrib_run.run(args)
  File "/home/user/workspace/miniconda3/envs/axolotl/lib/python3.11/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/user/workspace/miniconda3/envs/axolotl/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/workspace/miniconda3/envs/axolotl/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
axolotl.cli.train FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : current_time
  host      : this_machine
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 188792)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

The nvidia-smi right before OOMing the last time:
```
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.129.03             Driver Version: 535.129.03   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3090 Ti     Off | 00000000:01:00.0  On |                  Off |
| 31%   61C    P2             119W / 480W |  23103MiB / 24564MiB |     52%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce RTX 3090 Ti     Off | 00000000:07:00.0 Off |                  Off |
|  0%   45C    P2             107W / 450W |  18477MiB / 24564MiB |     30%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      2424      G   /usr/lib/xorg/Xorg                          638MiB |
|    0   N/A  N/A      2635      G   /usr/bin/gnome-shell                        268MiB |
|    0   N/A  N/A      5227      G   ...2121931,18333136748858586278,262144      150MiB |
|    0   N/A  N/A     25525      G   ...sion,SpareRendererForSitePerProcess      183MiB |
|    0   N/A  N/A    100682      G   ...,WinRetrieveSuggestionsOnlyOnDemand       71MiB |
|    0   N/A  N/A    191079      C   .../miniconda3/envs/axolotl/bin/python    21768MiB |
|    1   N/A  N/A      2424      G   /usr/lib/xorg/Xorg                            4MiB |
|    1   N/A  N/A    191080      C   .../miniconda3/envs/axolotl/bin/python    18460MiB |
+---------------------------------------------------------------------------------------+
```

**Comment by NanoCode012** [comment]
Do you notice this spike during model loading or during the training process?

How long are you training sequences?

**Comment by kallewoof** [comment]
> Do you notice this spike during model loading or during the training process?

For python -m [...], the model loads fine, and every sample after that trains ok until it hits a 4096 token sample, and then it OOMs.

For accelerate launch -m [...], the OOM happens right after the last checkpoint shard has been loaded, as you can see in the above log.

> How long are you training sequences?

This is mostly the `no_robot` dataset, so it is very mixed.

**Comment by adamo1139** [comment]
Flash Attention will be enabled only if sample packing is turned off. I believe that flash attention reduces memory usage significantly. I can do qlora of 34B model with context size around 1300 on single 24GB rtx 3090 ti with flash attention enabled and sample_packing disabled. If sample packing is enabled, it OOMs even with ctx 100. According to comment near the relevant piece of code, sample_packing uses custom FA2 patch. Apparently, this seems to make sample_packing incompatible with FA2, which is a big loss since it makes things faster and frees up memory.

**Comment by NanoCode012** [comment]
> Flash Attention will be enabled only if sample packing is turned off

This should not be.

---

For the original issue, sample packing method has been updated. Is it still possible to reproduce this?

**Comment by kallewoof** [comment]
@NanoCode012 I will reopen this if I am able to reproduce. Not sure when I will be able to test, so closing for now.
