### ISSUE TITLE
Please add support for - neftune_noise_alpha

### ISSUE THREAD

**Issue by apt-team-018** [axolotl-ai-cloud/axolotl#869]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/OpenAccess-AI-Collective/axolotl/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/OpenAccess-AI-Collective/axolotl/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

Add support for neftune_noise_alpha.

https://huggingface.co/docs/transformers/main_classes/trainer#boost-your-fine-tuning-performances-using-neftune

### ✔️ Solution

Add support for neftune_noise_alpha. It can help to prevent model overfit during fine-tuning.  

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by NanoCode012** [comment]
I think we have this already using our patch, not HF.

```yaml
# Augmentation techniques
# NEFT https://arxiv.org/abs/2310.05914, set this to a number (paper default is 5) to add noise to embeddings
# currently only supported on Llama and Mistral
noisy_embedding_alpha:
```

**Comment by mauryaland** [comment]
@NanoCode012 indeed but it is broken as mentioned in https://github.com/OpenAccess-AI-Collective/axolotl/issues/811

**Comment by NanoCode012** [comment]
@mauryaland , oh I see. I wasn't aware. I think, last winglian said, we should swap to HF's nefttune. Would you like to PR this change?

**Comment by mauryaland** [comment]
@NanoCode012 I could take a look to the code!

**Comment by NanoCode012** [comment]
@mauryaland , I can help point you in the required files.

1. You would need to delete this `src/axolotl/monkeypatch/neft_embeddings.py`
2. delete this line: https://github.com/OpenAccess-AI-Collective/axolotl/blob/575a082aae3c38762aa66680d9b4657db8b397c4/src/axolotl/train.py#L184
3. delete this line: https://github.com/OpenAccess-AI-Collective/axolotl/blob/575a082aae3c38762aa66680d9b4657db8b397c4/src/axolotl/train.py#L194
4. add an if cfg.noisy_embedding_alpha is passed to pass it to args : https://github.com/OpenAccess-AI-Collective/axolotl/blob/575a082aae3c38762aa66680d9b4657db8b397c4/src/axolotl/core/trainer_builder.py#L672

Edit: I don't know if neft applies to all model etc, so if it's limited to only some subset. You would need to check the model.

**Comment by mauryaland** [comment]
Thanks for the guidance @NanoCode012, I finally got time to take a look at the code. Should we go back to this implementation https://github.com/OpenAccess-AI-Collective/axolotl/pull/721/files, i.e. I recreate the files `llama_embeddings_hijack.py` and  `mistral_embeddings_hijack.py`? Maybe @winglian can help on this too!

**Comment by NanoCode012** [comment]
@mauryaland , I think using the upstream lib instead of maintaining our own patch would be better.

**Comment by gururise** [comment]
Any further progress on this? Would be amazing to be able to use NEFT.

**Comment by NanoCode012** [comment]
@gururise , I think current implementation works, but it uses axolotl patch. If you want to use the official neft, you'll need to make those changes I mentioned above.

**Comment by kallewoof** [comment]
> @gururise , I think current implementation works, but it uses axolotl patch. If you want to use the official neft, you'll need to make those changes I mentioned above.

`RecursionError: maximum recursion depth exceeded in comparison`

It's been broken for weeks, I believe.

**Comment by NanoCode012** [comment]
Thanks to @kallewoof  for the PR.
