### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement auto-gptq==0.4.2 (from axolotl[deepspeed,flash-attn]) (from versions: 0.0.4, 0.0.5, 0.1.0, 0.2.0, 0.2.1, 0.2.2, 0.3.0, 0.3.1, 0.3.2, 0.5.0, 0.5.1) ERROR: No matching distribution found for auto-gptq==0.4.2

### ISSUE THREAD

**Issue by Fluxionsdx** [axolotl-ai-cloud/axolotl#872]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/OpenAccess-AI-Collective/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

Installation should work

### Current behaviour

When running the command pip3 install -e '.[flash-attn,deepspeed]'
Get error: ERROR: Could not find a version that satisfies the requirement auto-gptq==0.4.2 (from axolotl[deepspeed,flash-attn]) (from versions: 0.0.4, 0.0.5, 0.1.0, 0.2.0, 0.2.1, 0.2.2, 0.3.0, 0.3.1, 0.3.2, 0.5.0, 0.5.1) ERROR: No matching distribution found for auto-gptq==0.4.2

I found this closed issue https://github.com/OpenAccess-AI-Collective/axolotl/issues/835 from a week ago where it looks like there was a problem with people having 0.4.2 installed. It looks like that was fixed by requiring 0.4.2, but that version now seems to be no longer available?

### Steps to reproduce

pip3 install packaging
pip3 install -e '.[flash-attn,deepspeed]'

### Which Operating Systems are you using?

- [ ] Linux
- [X] macOS
- [ ] Windows

### Python Version

3.11.5

### axolotl branch-commit

commit 3cc67d2cdd95196e4e9ae28fe2c6512092100e21 (HEAD -> main, origin/main, origin/HEAD)

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by winglian** [comment]
This will be fixed once we merge #867

**Comment by Fluxionsdx** [comment]
I just tried to install auto-gptq==0.5.1 and got this error
<img width="742" alt="Screenshot 2023-11-16 at 9 50 24 AM" src="https://github.com/OpenAccess-AI-Collective/axolotl/assets/7825989/4fde9cc6-fca3-42c7-b21f-4283836fbfdb">

looks like it's expecting a cuda version, but I'm on a macbook.

**Comment by winglian** [comment]
@Fluxionsdx unfortunately I don't think axolotl is well supported on Mac since it relies on a lot of libraries that are pretty nvidia/cuda specific.
