### ISSUE TITLE
[Feature Request]: qlora finetuning example for stablelm-3b-4e1t

### ISSUE THREAD

**Issue by BarfingLemurs** [axolotl-ai-cloud/axolotl#882]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/OpenAccess-AI-Collective/axolotl/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/OpenAccess-AI-Collective/axolotl/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

This model matches falcon 7B in performance, would be great to add a training config.

### ✔️ Solution

Adding an example for finetuning with Lora and qlora.

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by NanoCode012** [comment]
May I ask what happens when you just take a different model's config then swap the base model (with trust remote code)? Does it work?

**Comment by bubbabug** [comment]
I have been unable to train LoRAs based on this architecture. I have tried several confiigs and all have failed in the same way.

**Comment by BarfingLemurs** [comment]
Hi, I found you can train this model

With llama-2/qlora.yml or lora.yml, and these applied settings on a 3090:

```
trust_remote_code: true
model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer
xformers_attention: true
```

**Comment by bubbabug** [comment]
> Hi, I found you can train this model
> 
> With llama-2/qlora.yml or lora.yml, and these applied settings on a 3090:
> 
> ```
> trust_remote_code: true
> model_type: AutoModelForCausalLM
> tokenizer_type: AutoTokenizer
> xformers_attention: true
> ```

I have attempted using these settings to train a qlora for StableLM, but they do not work. Can you please provide your entire yaml so that I can replicate your results?

This is the error received:

AttributeError: 'StableLMEpochForCausalLM' object has no attribute 'transformer'
