### ISSUE TITLE
Cache issue for same tokenizer class

### ISSUE THREAD

**Issue by pocca2048** [axolotl-ai-cloud/axolotl#885]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/OpenAccess-AI-Collective/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

Different tokenizer -> different hash key

### Current behaviour

Different tokenizer -> same hash key
ex) LlamaTokenizer & Mistral tokenizer
- https://huggingface.co/mistralai/Mistral-7B-v0.1/blob/main/tokenizer_config.json
- https://huggingface.co/hf-internal-testing/llama-tokenizer/blob/main/tokenizer_config.json

### Steps to reproduce

1. use llama tokenizer to make dataset
2. use mistral tokenizer to make dataset

https://github.com/OpenAccess-AI-Collective/axolotl/blob/575a082aae3c38762aa66680d9b4657db8b397c4/src/axolotl/utils/data.py#L103-L121
https://github.com/OpenAccess-AI-Collective/axolotl/blob/575a082aae3c38762aa66680d9b4657db8b397c4/src/axolotl/utils/data.py#L412-L431

### Possible solution

Temporarily use `tokenizer.vocab_file` instead of `tokenizer.__class__.__name__`.
But vocab_file may not exist?

### Which Operating Systems are you using?

- [ ] Linux
- [ ] macOS
- [ ] Windows

### Python Version

4.8

### axolotl branch-commit

575a082

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by NanoCode012** [comment]
Thanks for the bug report. It would seem that the temporary workaround would be to not load tokenized dataset (if your sample size is small) or to use different `dataset_prepared_path` for different classes..

**Comment by winglian** [comment]
Thanks! That's a great idea to use the vocabulary file. Perhaps we could hash the vocabulary file data?

**Comment by pocca2048** [comment]
Nice! Or using the md5sum of the vocab file could be a solution.

**Comment by NanoCode012** [comment]
Just want to leave comment: it is possible to not load from cache by leaving `dataset_prepared_path` empty.

**Comment by NanoCode012** [comment]
Hey, this should be solved with PR https://github.com/OpenAccess-AI-Collective/axolotl/pull/1298
