### ISSUE TITLE
installation bugs

### ISSUE THREAD

**Issue by 152334H** [axolotl-ai-cloud/axolotl#892]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/OpenAccess-AI-Collective/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

using python==3.10.12 with a fresh venv:
```bash
$ python --version
Python 3.10.12
$ python -m venv axo
$ . axo/bin/activate
```

These are the current installation instructions given:
```python
$ git clone https://github.com/OpenAccess-AI-Collective/axolotl
$ cd axolotl
~/axolotl$ pip3 install packaging
~/axolotl$ pip3 install -e '.[flash-attn,deepspeed]'
```

they should work

### Current behaviour

# problem 1. install fails immediately

this occurs due to flash-attn

this can be solved by pre-installing `wheel`
```
~/axolotl$ pip3 install wheel
```

# 2. flash attention fails

this occurs because the pinned version of 2.3.3 doesn't stick, and flash-attn=2.3.4 is incompat with torch=2.0.1 (which is pinned)

```
$ python3 -c 'import torch;import flash_attn_2_cuda as flash_attn_cuda'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: /home/a/axolotl/venv/lib/python3.10/site-packages/flash_attn_2_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c104cuda9SetDeviceEi
```

this can be solved by forcing 2.3.3

```
~/axolotl$ pip install flash-attn==2.3.3
```

# 3. gradient checkpointing doesn't work
i use the first default example config provided:
```
~/axolotl$ accelerate launch -m axolotl.cli.train examples/openllama-3b/lora.yml
```
it does not work

```
  File "/home/a/axolotl/src/axolotl/cli/train.py", line 34, in do_cli
    train(cfg=parsed_cfg, cli_args=parsed_cli_args, dataset_meta=dataset_meta)
  File "/home/a/axolotl/src/axolotl/train.py", line 124, in train
    trainer.train(resume_from_checkpoint=resume_from_checkpoint)
  File "/home/a/axolotl/axo/lib/python3.10/site-packages/transformers/trainer.py", line 1555, in train
    return inner_training_loop(
  File "/home/a/axolotl/axo/lib/python3.10/site-packages/transformers/trainer.py", line 1860, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/home/a/axolotl/axo/lib/python3.10/site-packages/transformers/trainer.py", line 2734, in training_step
    self.accelerator.backward(loss)
  File "/home/a/axolotl/axo/lib/python3.10/site-packages/accelerate/accelerator.py", line 1987, in backward
    self.scaler.scale(loss).backward(**kwargs)
  File "/home/a/axolotl/axo/lib/python3.10/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/home/a/axolotl/axo/lib/python3.10/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/home/a/axolotl/axo/lib/python3.10/site-packages/torch/autograd/function.py", line 274, in apply
    return user_fn(self, *args)
  File "/home/a/axolotl/axo/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 157, in backward
    torch.autograd.backward(outputs_with_grad, args_with_grad)
  File "/home/a/axolotl/axo/lib/python3.10/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: Expected to mark a variable ready only once. This error is caused by one of the following reasons: 1) Use of a module parameter outside the `forward` function. Please make sure model parameters are not shared across multiple concurrent forward-backward passes. or try to use _set_static_graph() as a workaround if this module graph does not change during training loop.2) Reused parameters in multiple reentrant backward passes. For example, if you use multiple `checkpoint` functions to wrap the same part of your model, it would result in the same set of parameters been used by different reentrant backward passes multiple times, and hence marking a variable ready multiple times. DDP does not support such use cases in default. You can try to use _set_static_graph() as a workaround if your module graph does not change over iterations.
Parameter at index 363 has been marked as ready twice. This means that multiple autograd engine  hooks have fired for this particular parameter during this iteration. You can set the environment variable TORCH_DISTRIBUTED_DEBUG to either INFO or DETAIL to print parameter names for further debugging.
  0%|                                                           
```

i don't particularly know why this happens. i do know that it is linked to gradient checkpointing, and disappears without it. i also know that it doesn't occur if use_reentrant=False (a different error occurs then)

### Steps to reproduce

it is the default installation instructions in the repo with no changes

### Config yaml

it is the default config in the repo with no changes

### Which Operating Systems are you using?

- [X] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.10

### axolotl branch-commit

main/9fc29e082bcd220943f436a82affb2a4a3d3db78

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by NanoCode012** [comment]
Hey, I ran your third command in Colab
```
accelerate launch -m axolotl.cli.train examples/openllama-3b/lora.yml --bf16=False --fp16 True --tf32 False --flash_attention False
```

and it worked. I didn't mess with gradient checkpointing. I turned off those configs above because I was using a T4 .

---

Regarding 1+2, I don't have a machine to test it right now, but that looks weird..

**Comment by 152334H** [comment]
yeah I am deeply confused as to why I am solely experiencing this & others are not, despite using a fresh venv

i will try to replicate this on a separate machine later

**Comment by NanoCode012** [comment]
Could you try with conda? Also, did you install torch before the rest of those? We encourage using docker as it should just work :)

**Comment by 152334H** [comment]
I don't particularly want to use conda because it fucks over the location of cuda/cudnn (among other reasons)

docker's my last ditch option. it would be a pain to make seamless with my current dev env (no simple remote ssh passthrough, mount volumes would have conflicting UIDs, etc), but it would at least run

**Comment by NanoCode012** [comment]
Hey, could you please let us know if this was fixed?
