### ISSUE TITLE
Checkpoints not postprocessed

### ISSUE THREAD

**Issue by enn-nafnlaus** [axolotl-ai-cloud/axolotl#916]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/OpenAccess-AI-Collective/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

Checkpoints should be postprocessed.

### Current behaviour

Checkpoints are not postprocessed. This is somewhat insidious, as they'll still work for inferences in some circumstances, but not others.

### Steps to reproduce

Train a checkpoint. Try then, say, converting it to GGUF and running inference on it.

convert.py "${model_path}" --outtype f16 --outfile "${fp16_path}"
quantize "${fp16}" "${model_path}/${prefix}.Q4_0.gguf" "q4_0"
server --model "${model_path}/${prefix}.Q4_0.gguf" .... (other flags here)

It'll complain about bad characters - something like:

```
[user@server llama.cpp]$ CUDA_VISIBLE_DEVICES=1 ./server --model /path/output/summarize/checkpoint-22800 --port 5678 --n-gpu-layers 1000000000 --batch-size 2048 --threads 4 --threads-batch 1 --numa --mlock --ctx-size 2048
ggml_init_cublas: GGML_CUDA_FORCE_MMQ:   no
ggml_init_cublas: CUDA_USE_TENSOR_CORES: yes
ggml_init_cublas: found 1 CUDA devices:
  Device 0: NVIDIA GeForce RTX 3060, compute capability 8.6
{"timestamp":1701771143,"level":"INFO","function":"main","line":2534,"message":"build info","build":1577,"commit":"1f5cd83"}
{"timestamp":1701771143,"level":"INFO","function":"main","line":2537,"message":"system info","n_threads":4,"n_threads_batch":1,"total_threads":12,"system_info":"AVX = 1 | AVX2 = 1 | AVX512 = 1 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 | "}
gguf_init_from_file: invalid magic characters .
error loading model: llama_model_loader: failed to load model from /path/output/summarize/checkpoint-22800

llama_load_model_from_file: failed to load model
llama_init_from_gpt_params: error: failed to load model '/path/output/summarize/checkpoint-22800'
{"timestamp":1701771143,"level":"ERROR","function":"load_model","line":569,"message":"unable to load model","model":"/path/output/summarize/checkpoint-22800"}

```

However, if you postprocess it first - I was given a postprocessing script on the discord to run on a modified yml - , it'll work just fine.  The script:

```
from pathlib import Path

import fire
import transformers

from axolotl.cli import do_merge_lora, load_cfg, print_axolotl_text_art
from axolotl.common.cli import TrainerCliArgs, load_model_and_tokenizer


def do_cli(config: Path = Path("examples/"), **kwargs):
    # pylint: disable=duplicate-code
    print_axolotl_text_art()
    parser = transformers.HfArgumentParser((TrainerCliArgs))
    parsed_cli_args, _ = parser.parse_args_into_dataclasses(
        return_remaining_strings=True
    )
    parsed_cli_args.merge_lora = True
    parsed_cfg = load_cfg(config, merge_lora=True, **kwargs)

    model, tokenizer = load_model_and_tokenizer(cfg=parsed_cfg, cli_args=parsed_cli_args)
    for name, module in model.named_modules():
        if hasattr(module, "_post_training"):
            module._post_training(model, name)  # pylint: disable=protected-access
    model.save_pretrained(
        str(Path(parsed_cfg.output_dir) / "post_processed"),
        safe_serialization=True,
    )


if __name__ == "__main__":
    fire.Fire(do_cli)
```

I then have to copy over the tokenizer files to the checkpoint dir, make a modified yml that points to the checkpoint instead of the base model, then run:

python  -m axolotl.cli.post_process summarize_postprocess.yaml

... then everything ends up in post_processed rather than the checkpoint dir.  But it'll work then .

Postprocessing isn't slow compared to other training aspects.  If one's going to write out a checkpoint, IMHO, they should be postprocessed.

### Config yaml

Any

### Possible solution

See above

### Which Operating Systems are you using?

- [X] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.10.11

### axolotl branch-commit

a48dbf6561cc74c275a48070f397334a2c367dd5

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by NanoCode012** [comment]
Would you be interested in adding a PR for this?

**Comment by enn-nafnlaus** [comment]
> Would you be interested in adding a PR for this?

I only have a manual workaround, using the (above) code I was given on the discord and multiple steps in bash and editing config files.

**Comment by NanoCode012** [comment]
Note for future ref: This below could probably be added to the end of the finetuning script. Perhaps with a check for llama models only.
```py
    for name, module in model.named_modules():
        if hasattr(module, "_post_training"):
            module._post_training(model, name)  # pylint: disable=protected-access
```

**Comment by NanoCode012** [comment]
This should now be fixed: https://github.com/OpenAccess-AI-Collective/axolotl/blob/d25c34caa6f324cdd7521138f4515e6ed7dc258d/src/axolotl/train.py#L135-L137

**Comment by enn-nafnlaus** [comment]
> This should now be fixed:
> 
> https://github.com/OpenAccess-AI-Collective/axolotl/blob/d25c34caa6f324cdd7521138f4515e6ed7dc258d/src/axolotl/train.py#L135-L137

Awesome, thanks!  :)
