### ISSUE TITLE
RuntimeError: Expected to mark a variable ready only once.

### ISSUE THREAD

**Issue by minouei-kl** [axolotl-ai-cloud/axolotl#923]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/OpenAccess-AI-Collective/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

not sure if this a bug or a exception in my setup environment (docker and 1 gpu)

### Current behaviour

this the error I got:
RuntimeError: Expected to mark a variable ready only once. This error is caused by one of the following reasons: 1) Use of a module parameter outside the `forward` function. Please make sure model parameters are not shared across multiple concurrent forward-backward passes. or try to use _set_static_graph() as a workaround if this module graph does not change during training loop.2) Reused parameters in multiple reentrant backward passes. For example, if you use multiple `checkpoint` functions to wrap the same part of your model, it would result in the same set of parameters been used by different reentrant backward passes multiple times, and hence marking a variable ready multiple times. DDP does not support such use cases in default. You can try to use _set_static_graph() as a workaround if your module graph does not change over iterations.
Parameter at index 447 has been marked as ready twice. This means that multiple autograd engine  hooks have fired for this particular parameter during this iteration. You can set the environment variable TORCH_DISTRIBUTED_DEBUG to either INFO or DETAIL to print parameter names for further debugging.

### Steps to reproduce

accelerate launch -m axolotl.cli.train qlora.yml

### Possible solution

I did a search regarding the problem and figure the ddp_find_unused_parameters should be false. so I had to put ddp: true in my config file that makes the ddp_find_unused_parameters false.
see here:
https://github.com/OpenAccess-AI-Collective/axolotl/blob/06ae39200b60d3482af8bd8bfc1a823c1b24e1da/src/axolotl/core/trainer_builder.py#L644
it's working now.

### Which Operating Systems are you using?

- [X] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.10

### axolotl branch-commit

0.3.0

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by NanoCode012** [comment]
Could you please provide your config to reproduce?

Iirc, setting that parameter would slow multigpu training a bit.

**Comment by NanoCode012** [comment]
Will close due to inactivity. Please leave a comment if the issue reoccurs.
