### ISSUE TITLE
disable checkpoint for wandb_log_model:

### ISSUE THREAD

**Issue by winglian** [axolotl-ai-cloud/axolotl#94]
update all the configs / examples and change `wandb_log_model: checkpoint` => `wandb_log_model: `

this will prevent uploading obscenely large artifacts to wandb by default and using quota

**Comment by viktoriussuwandi** [comment]
Hi [winglian](https://github.com/winglian), do you want to change `wandb_log_model: checkpoint` to just `wandb_log_model:` (delete `checkpoint`) on all files inside `axolotl/configs/` ? I will try to help

For example on [axolotl/configs/sample.yml](https://github.com/OpenAccess-AI-Collective/axolotl/blob/main/configs/sample.yml)

![Screenshot](https://github.com/OpenAccess-AI-Collective/axolotl/assets/68414300/561d4f7e-9f87-4a86-a270-194b19452c05)

**Comment by winglian** [comment]
@viktoriussuwandi correct. for most people using this, having checkpoint as the default is wasteful on bandwidth. thanks!

**Comment by winglian** [comment]
if you tackle this, please check the `examples` folder too

**Comment by viktoriussuwandi** [comment]
Yes, no problem
