### ISSUE TITLE
When I try to Mixtral 7B Full finetuning, I got an error message about  Flash Attention 2.

### ISSUE THREAD

**Issue by DopeorNope-Lee** [axolotl-ai-cloud/axolotl#955]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/OpenAccess-AI-Collective/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

I got a this error when I try to full fine-tuning mixtral 7bx8

### Current behaviour

  File "/home/jovyan/fileviewer/LLM/axolotl/src/axolotl/utils/models.py", line 453, in load_model
    model = AutoModelForCausalLM.from_pretrained(
  File "/home/jovyan/.local/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 566, in from_pretrained
    return model_class.from_pretrained(
  File "/home/jovyan/.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3444, in from_pretrained
    config = cls._autoset_attn_implementation(
  File "/home/jovyan/.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 1302, in _autoset_attn_implementation
    cls._check_and_enable_flash_attn_2(
  File "/home/jovyan/.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 1401, in _check_and_enable_flash_attn_2
    raise ImportError(f"{preface} Flash Attention 2 is not available. {install_message}")
ImportError: FlashAttention2 has been toggled on, but it cannot be used due to the following error: Flash Attention 2 is not available. Please refer to the documentation of https://huggingface.co/docs/transformers/perf_infer_gpu_one#flashattention-2 to install Flash Attention 2.

### Steps to reproduce

I install your package for full-finetuning mixtral 7B x 8.

However, I encountered above issue.

How can I solve it?

### Config yaml

base_model: mistralai/Mixtral-8x7B-Instruct-v0.1
model_type: AutoModelForCausalLM
tokenizer_type: LlamaTokenizer
trust_remote_code: true

load_in_8bit: false
load_in_4bit: false
strict: false

datasets:
  - path: DopeorNope/Robustness_Ko_data-v1
    type: alpaca
dataset_prepared_path: last_run_prepared
val_set_size: 0.0
output_dir: ./mixtral-ko-v1

## You can optionally freeze the entire model and unfreeze a subset of parameters
unfrozen_parameters:
#  - lm_head.*
#  - model.embed_tokens.*
#  - model.layers.2[0-9]+.block_sparse_moe.gate.*
#  - model.layers.2[0-9]+.block_sparse_moe.experts.*
#  - model.layers.3[0-9]+.block_sparse_moe.gate.*
#  - model.layers.3[0-9]+.block_sparse_moe.experts.*

sequence_len: 32768
sample_packing: true
pad_to_sequence_len: true

# adapter: 
# lora_model_dir:
# lora_r: 32
# lora_alpha: 16
# lora_dropout: 0.05
# lora_target_linear: true
# lora_fan_in_fan_out:
# #lora_target_modules:
# #  - gate
# #  - q_proj
# #  - k_proj
# #  - v_proj
# #  - o_proj
# #  - w1
# #  - w2
#  - w3

adapter:
lora_model_dir:
lora_r:
lora_alpha:
lora_dropout:
lora_target_linear:
lora_fan_in_fan_out:

wandb_project:
wandb_entity:
wandb_watch:
wandb_name:
wandb_log_model:

wandb_project:
wandb_entity:
wandb_watch:
wandb_name:
wandb_log_model:

gradient_accumulation_steps: 64
micro_batch_size: 1
num_epochs: 5
optimizer: adamw_bnb_8bit
lr_scheduler: cosine
learning_rate: 0.0002

train_on_inputs: false
group_by_length: false
bf16: false
fp16: True
tf32: false

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: True

loss_watchdog_threshold: 5.0
loss_watchdog_patience: 3

warmup_steps: 10
evals_per_epoch: 4
eval_table_size:
eval_table_max_new_tokens: 128
saves_per_epoch: 1
debug:
deepspeed: deepspeed/zero2.json
weight_decay: 0.1
fsdp:
fsdp_config:
special_tokens:

### Which Operating Systems are you using?

- [X] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.10

### axolotl branch-commit

rescent

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by winglian** [comment]
Can you provide the output of running pip list ?

**Comment by NanoCode012** [comment]
Please also check that `nvidia-smi` shows your GPU and you properly set `CUDA_VISIBLE_DEVICES`.

**Comment by NanoCode012** [comment]
Should be solved by re-creating new env and re-running following readme. Closing.
