### ISSUE TITLE
Include a guide on how to upload the training data and config yaml to the Runpod version.

### ISSUE THREAD

**Issue by LeMemeDream** [axolotl-ai-cloud/axolotl#974]
### What piece of documentation is affected?

The Runpod guide, which is currently severely lacking, only having a direct link to the Axolotl Runpod without any instructions on how to utilize it. 

### What part(s) of the article would you like to see updated?

Step-by-step documentation on how to use any of the SSH methods on Runpod to upload the needed training data and config to Runpod. Virtually every method throws errors/doesn't work, and not everyone has the technical expertise to get the files on there (Google proves unhelpful in resolving this). Alternatively, having some way to load files from the local disk would be extremely helpful and solve the issue entirely. I saw that someone requested that functionality, and it was implemented about 3 days ago on the commit here, so it seems doable.

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by NanoCode012** [comment]
Hey, I saw someone replied to your question in Discord. If you've got it working, do you mind adding a PR to the docs about this?

> Alternatively, having some way to load files from the local disk would be extremely helpful and solve the issue entirely. 

What do you mean here? Local disk on run pod instance? That should already work?

**Comment by LeMemeDream** [comment]
> Hey, I saw someone replied to your question in Discord. If you've got it working, do you mind adding a PR to the docs about this?
> 
> > Alternatively, having some way to load files from the local disk would be extremely helpful and solve the issue entirely.
> 
> What do you mean here? Local disk on run pod instance? That should already work?

Hi! Yeah, I could try to add something. I meant more "ability to interact with local machine files on runpod", which seems to be working fine for everyone except me. The HTTP Service Port (8888) says that it's "not ready", and won't open at all. Clicking it just leads to a Cloudflare error. From what I've heard, this is the reason I don't have access to the Jupyter-style file explorer on Runpod. Not sure what the deal is, but I'm including a picture of both the errored out button and Cloudflare error. 

<img width="448" alt="Screenshot 2023-12-18 102650" src="https://github.com/OpenAccess-AI-Collective/axolotl/assets/113479539/7688e656-a879-4bd1-8ee6-525bbfa86598">
<img width="746" alt="Screenshot 2023-12-18 102527" src="https://github.com/OpenAccess-AI-Collective/axolotl/assets/113479539/4cbeef19-e25e-4264-976d-c40d35f027ed">

**Comment by NanoCode012** [comment]
Hey, I think I saw caseus reply to you about this in Discord about waiting a bit for the server to load. Did that fix it for you? are you still having this issue?

**Comment by NanoCode012** [comment]
Closing as this was a runpod issue that should've been resolved per discord conversation.
