### ISSUE TITLE
Add axoltl tag to created model cards

### ISSUE THREAD

**Issue by osanseviero** [axolotl-ai-cloud/axolotl#979]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/OpenAccess-AI-Collective/axolotl/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/OpenAccess-AI-Collective/axolotl/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

We can have a tag that marks that a project was trained with Axoltl, that way we can easily filter for models trained with it, e.g. https://huggingface.co/models?other=axoltl

### ✔️ Solution

Add something like

```
tags:
  - axoltl
```

This can be done with the `huggingface_hub` library quite easily

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by osanseviero** [comment]
Fixed in #1004

**Comment by filippo82** [comment]
Hi @osanseviero 👋🏻 can you please reopen this?

Why you ask? 😅 Unfortunately the logic added in #1004 by @younesbelkada is not leveraged by the recently introduced RL training capabilities of `axolotl`.

I am giving it a try with PR #1209

**Comment by winglian** [comment]
Pretty sure this works. https://huggingface.co/models?other=axolotl

**Comment by filippo82** [comment]
Unfortunately, it does not work if you use, for example, `rl: dpo`.

This is an example: https://huggingface.co/Filippo/distilabeled-Hermes-2.5-Mistral-7B
