### ISSUE TITLE
Phi 2 2.7B Support

### ISSUE THREAD

**Issue by jFkd1** [axolotl-ai-cloud/axolotl#980]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/OpenAccess-AI-Collective/axolotl/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/OpenAccess-AI-Collective/axolotl/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

Please close this if it is already supported, but I would like to request phi 2 support with axolotl. 

### ✔️ Solution

Implement phi 2 ft support

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by NanoCode012** [comment]
Could you try see if you can use the phi 1 config and point to the phi2 model?

**Comment by ehartford** [comment]
Hey it works for me

https://huggingface.co/cognitivecomputations/dolphin-2_6-phi-2/blob/main/configs/phi-dolphin-qlora.yml

**Comment by stangirala** [comment]
I tried using the existing phi config for phi2 and it looks like there might be an issue with `save_safetensors` config. I set it to False explicitly and this allowed my run to complete. If I don't set anything (assuming it picks up true for this config) I get a runtime error, 
```
Some tensors share memory, this will lead to duplicate memory on disk and potential differences when loading them again
```

see, https://github.com/huggingface/transformers/issues/27613

**Comment by NanoCode012** [comment]
@stangirala , yes I think Eric had this issue before. Turning off safetensor seemed to fix it. Thanks for linking that issue.

**Comment by NanoCode012** [comment]
Closed thanks to @ehartford 's shared yaml above!
