### ISSUE TITLE
Expose `llm_int8_has_fp16_weight` for `BitsAndBytesConfig`

### ISSUE THREAD

**Issue by peterjc123** [axolotl-ai-cloud/axolotl#984]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/OpenAccess-AI-Collective/axolotl/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/OpenAccess-AI-Collective/axolotl/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

As can be seen [here](https://github.com/OpenAccess-AI-Collective/axolotl/blob/main/src/axolotl/utils/models.py#L309C13-L309C37), axolotl uses `llm_int8_has_fp16_weight=False` and it aligns with the example [code](https://github.com/artidoro/qlora/blob/main/qlora.py#L322) in the QLora repo. But another training framework xllm defaults to `llm_int8_has_fp16_weight=True` ([code](https://github.com/BobaZooba/xllm/blob/main/src/xllm/core/config.py#L512)). Also, according to the [FAQ](https://github.com/TimDettmers/bitsandbytes/blob/main/README.md#tldr) of bitsandbytes, it says 
> There are two modes:
Mixed 8-bit training with 16-bit main weights. Pass the argument has_fp16_weights=True (default)
Int8 inference. Pass the argument has_fp16_weights=False

So, which one should I use? Or maybe it should be exposed as an option to the yaml configuration?

### ✔️ Solution

Let's expose this as an option, or more fields from the BitsAndBytesConfig including `bnb_4bit_use_double_quant`.

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by winglian** [comment]
this is probably best solved by having a `bnb_config_kwargs` option exposed
