### ISSUE TITLE
Docker image appear to be broken due to flash_atten

### ISSUE THREAD

**Issue by tcapelle** [axolotl-ai-cloud/axolotl#985]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/OpenAccess-AI-Collective/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

It should run.

### Current behaviour

<img width="1167" alt="image" src="https://github.com/OpenAccess-AI-Collective/axolotl/assets/18441985/dee3f77f-e3a4-4759-8ebf-efa1da7cbcfe">

### Steps to reproduce

You just pull latest docker image and run it.
```
sudo docker run --gpus '"all"' --rm -it winglian/axolotl:main-py3.10-cu118-2.1.0
```
Tried on 2 different machines.

### Possible solution

Also the image should have pytorch 2.1 and has 2.0.1

### Which Operating Systems are you using?

- [X] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.10

### axolotl branch-commit

docker images

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by hamelsmu** [comment]
What is your base CUDA env?  I could not repro this.  Can you try the following:

- Upgrade your base CUDA (not through conda)
- Install a newer version of [nvidia-docker-toolkit](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html)

**Comment by tcapelle** [comment]
In 2 different machines I get the same error. One with A100 the other with H100.
- Also, the installed PyTorch is `2.0.1+cu117` on the image instead of the mentioned 2.1

**Comment by winglian** [comment]
Once the docker images from #987 finish, this should be resolved.
